import json, sys
sys.stdout.reconfigure(encoding="utf-8")

# n=title, fa=fact (general population health statistics, text-only)
facts = [
    {"n":"Left-handedness","fa":"About 10 percent of the world's population is left-handed, a proportion that has stayed remarkably stable across history"},
    {"n":"Heart rate","fa":"The average adult heart beats around 100,000 times per day, pumping roughly 7,500 liters of blood"},
    {"n":"Human height variation","fa":"Average adult height varies by up to 20 centimeters between countries, largely due to nutrition and genetics"},
    {"n":"Blood type distribution","fa":"Type O is the most common blood type worldwide, while type AB is the rarest"},
    {"n":"Sleep needs","fa":"Most adults need between 7 and 9 hours of sleep per night, though individual needs vary"},
    {"n":"Color blindness","fa":"About 1 in 12 men and 1 in 200 women have some form of color vision deficiency"},
    {"n":"Twin births","fa":"Roughly 1 in every 42 births worldwide results in twins, with rates varying significantly by region"},
    {"n":"Human body water content","fa":"The adult human body is roughly 60 percent water by weight, though this varies with age and body composition"},
    {"n":"Yawning contagion","fa":"About 6 in 10 people yawn after seeing or hearing someone else yawn, a phenomenon still not fully understood"},
    {"n":"Handedness and the brain","fa":"Left-handed people often have more evenly distributed language processing between both brain hemispheres"},
    {"n":"Average resting heart rate","fa":"A typical resting heart rate for adults ranges from 60 to 100 beats per minute"},
    {"n":"Human taste buds","fa":"An adult has around 10,000 taste buds, which are fully replaced roughly every two weeks"},
    {"n":"Nearsightedness prevalence","fa":"Nearsightedness affects roughly 3 in 10 people worldwide, with notably higher rates in East Asia"},
    {"n":"Body temperature variation","fa":"Average human body temperature has gradually decreased over the past two centuries, with modern averages closer to 36.6 degrees Celsius than the traditional 37"},
    {"n":"Handwashing and illness","fa":"Regular handwashing with soap can meaningfully reduce the risk of catching respiratory infections"},
    {"n":"Human skin as an organ","fa":"Skin is the body's largest organ, accounting for a significant share of total adult body weight"},
    {"n":"Blinking frequency","fa":"Humans blink an average of 15 to 20 times per minute, far more often than needed just to keep the eyes moist"},
    {"n":"Left-handed sports advantage","fa":"Left-handed athletes are statistically overrepresented in interactive sports like fencing and boxing, likely due to opponents' unfamiliarity"},
    {"n":"Human gut bacteria","fa":"The average human gut hosts trillions of bacteria, collectively weighing around 200 grams"},
    {"n":"Average lifespan increase","fa":"Global average life expectancy has more than doubled over the past 150 years, largely due to public health advances"},
    {"n":"Hiccups","fa":"Nearly everyone experiences hiccups, which are caused by involuntary spasms of the diaphragm muscle"},
    {"n":"Redheads and pain sensitivity","fa":"People with naturally red hair may require higher doses of certain anesthetics, linked to a gene affecting pain receptors"},
    {"n":"Human bone count changes","fa":"Babies are born with about 300 bones, while adults have 206, as many bones fuse together during growth"},
    {"n":"Fingernail growth rate","fa":"Fingernails grow about 3 millimeters per month on average, roughly four times faster than toenails"},
    {"n":"Left-eye dominance","fa":"About 1 in 3 people are left-eye dominant, a trait that is independent of being left- or right-handed"},
    {"n":"Common cold frequency","fa":"Adults catch an average of 2 to 3 colds per year, while young children may catch significantly more"},
    {"n":"Human smell receptors","fa":"Humans can distinguish an enormous number of different scents according to modern olfactory research"},
    {"n":"Average human blinking during conversation","fa":"People tend to blink more frequently while speaking than while listening"},
    {"n":"Ambidexterity rarity","fa":"True ambidexterity, equal skill with both hands, is estimated to occur in only about 1 in 100 people"},
    {"n":"Human height and time of day","fa":"People are measurably taller in the morning than in the evening due to spinal disc compression over the day"},
    {"n":"Global smoking rates decline","fa":"Global smoking rates have fallen significantly since the 1980s, though rates remain high in some regions"},
    {"n":"Dominant blood type by region","fa":"Blood type distribution varies significantly by region, with type B notably more common in parts of Asia"},
    {"n":"Average steps per day","fa":"Health guidelines commonly cite 7,000 to 10,000 steps per day as a general activity target for adults"},
    {"n":"Human hair growth rate","fa":"Scalp hair grows at an average rate of about 1.25 centimeters per month"},
    {"n":"Vision and night driving","fa":"Human night vision takes about 20 to 30 minutes to fully adjust after exposure to bright light"},
    {"n":"Global vaccination impact","fa":"Widespread vaccination is estimated to prevent millions of deaths globally every year"},
    {"n":"Sneezing speed","fa":"A sneeze can expel droplets at surprisingly high speeds, measured at several meters per second"},
    {"n":"Average number of daily breaths","fa":"An adult breathes an average of about 20,000 times per day at rest"},
    {"n":"Left-handedness and famous historical figures","fa":"Several historical figures across science, art and politics have been documented as left-handed, though estimates for specific individuals vary"},
    {"n":"Human tears","fa":"Humans produce basal tears constantly to keep the eyes lubricated, separate from emotional or reflex tears"},
    {"n":"Growth spurts","fa":"Adolescents can grow several centimeters in a single year during their peak pubertal growth spurt"},
    {"n":"Global handedness by gender","fa":"Rates of left-handedness are slightly higher among males than females in most studied populations"},
    {"n":"Average human blood volume","fa":"An adult body contains roughly 5 liters of blood, a small but vital fraction of total body weight"},
    {"n":"Common allergy prevalence","fa":"Seasonal pollen allergies affect a significant share of the population in many countries, with rates believed to be rising"},
    {"n":"Human reaction time","fa":"Average human visual reaction time to a simple stimulus is roughly a fifth of a second"},
    {"n":"Global obesity trend data","fa":"Global obesity rates have risen substantially since the 1970s according to long-term public health tracking"},
    {"n":"Average number of dreams per night","fa":"Most people have multiple dreams per night during REM sleep, though many are forgotten upon waking"},
    {"n":"Vitamin D and sunlight","fa":"Moderate sun exposure allows the skin to produce vitamin D, though excessive exposure carries other health risks"},
    {"n":"Left-handedness and language","fa":"Rates of left-handedness vary slightly across cultures, partly influenced by historical social pressure to use the right hand"},
    {"n":"Average resting breaths during sleep","fa":"Breathing rate typically slows somewhat during deep sleep compared to waking hours"},
    {"n":"Human eye resolution","fa":"The human eye can distinguish an enormous range of colors, with estimates commonly citing several million distinguishable shades"},
    {"n":"Global life expectancy gap","fa":"Life expectancy can differ by two decades or more between the highest and lowest ranked countries"},
    {"n":"Common food allergy prevalence","fa":"Peanut, tree nut, milk and egg allergies are among the most common food allergies reported in children"},
    {"n":"Average number of muscles used to smile","fa":"Smiling is often said to use fewer facial muscles than frowning, though the exact count is debated among researchers"},
    {"n":"Height loss with age","fa":"Adults can lose a centimeter or more in height over their lifetime due to spinal disc compression"},
    {"n":"Global handwashing habits","fa":"Public health surveys have found that handwashing with soap after using the toilet is inconsistent in many parts of the world"},
    {"n":"Human body cell replacement","fa":"Most cells in the human body are replaced on varying cycles, though neurons and some other cells last a lifetime"},
    {"n":"Average number of hairs on the human head","fa":"The average scalp holds around 100,000 hair follicles, though counts vary by natural hair color"},
    {"n":"Left-handed writing adaptations","fa":"Specialized left-handed scissors, pens and other tools have been developed to reduce friction-related smudging and discomfort"},
    {"n":"Global diabetes prevalence","fa":"Diabetes rates have risen substantially worldwide in recent decades, linked to diet, lifestyle and aging populations"},
]

with open("assets/health/common_health_facts.json", "w", encoding="utf-8") as f:
    json.dump(facts, f, ensure_ascii=False, separators=(',', ':'))

print(f"{len(facts)} common health facts generated.")
