import json, sys
sys.stdout.reconfigure(encoding="utf-8")

# n=INN/generic name (DCI), fam=drug class/family, yr=discovery/first use year,
# moa=mechanism of action, adm=route of administration, ind=main indications,
# se=most common side effects, fa=fact
# Psychiatric medications, split out from generate_medication.py to sit under
# the Mental Health branch alongside commonMentalDisorder.
# No brand names — generic/INN names only, text-only (no images)
mental_medications = [
    {"n":"Fluoxetine","fam":"Antidepressant (SSRI)","yr":"1987","moa":"Blocks serotonin reabsorption in the brain, increasing its availability","adm":"Oral","ind":"Depression, anxiety disorders, OCD","se":"Nausea, insomnia, sexual side effects","fa":"One of the first SSRIs approved, helping popularize this entire class of antidepressants from the late 1980s onward"},
    {"n":"Sertraline","fam":"Antidepressant (SSRI)","yr":"1991","moa":"Blocks serotonin reabsorption in the brain","adm":"Oral","ind":"Depression, anxiety disorders, PTSD","se":"Nausea, sexual side effects","fa":"One of the most frequently prescribed antidepressants, also used for several anxiety-related conditions"},
    {"n":"Citalopram","fam":"Antidepressant (SSRI)","yr":"1989","moa":"Blocks serotonin reabsorption in the brain","adm":"Oral","ind":"Depression","se":"Nausea, drowsiness","fa":"Known for a relatively simple dosing profile compared to some other SSRIs"},
    {"n":"Amitriptyline","fam":"Antidepressant (tricyclic)","yr":"1961","moa":"Blocks reabsorption of serotonin and noradrenaline in the brain","adm":"Oral","ind":"Depression, chronic pain, migraine prevention","se":"Drowsiness, dry mouth, weight gain","fa":"An older antidepressant now also commonly used off-label for chronic pain and migraine prevention"},
    {"n":"Venlafaxine","fam":"Antidepressant (SNRI)","yr":"1993","moa":"Blocks reabsorption of serotonin and noradrenaline in the brain","adm":"Oral","ind":"Depression, anxiety disorders","se":"Nausea, elevated blood pressure at higher doses","fa":"Affects two different brain chemical pathways, distinguishing it from single-pathway SSRIs"},
    {"n":"Bupropion","fam":"Antidepressant (atypical)","yr":"1985","moa":"Affects dopamine and noradrenaline pathways in the brain","adm":"Oral","ind":"Depression, smoking cessation","se":"Insomnia, dry mouth","fa":"Also approved as a smoking cessation aid, distinct from its use as an antidepressant"},
    {"n":"Chlorpromazine","fam":"Antipsychotic (first-generation)","yr":"1952","moa":"Blocks dopamine receptors in the brain","adm":"Oral, injectable","ind":"Schizophrenia, severe agitation","se":"Drowsiness, movement-related side effects","fa":"The first antipsychotic medication, introduced in the early 1950s and transforming psychiatric care"},
    {"n":"Haloperidol","fam":"Antipsychotic (first-generation)","yr":"1958","moa":"Blocks dopamine receptors in the brain","adm":"Oral, injectable","ind":"Schizophrenia, acute agitation","se":"Movement-related side effects, drowsiness","fa":"Remains widely used decades after its introduction, including in emergency psychiatric settings"},
    {"n":"Risperidone","fam":"Antipsychotic (second-generation)","yr":"1993","moa":"Blocks dopamine and serotonin receptors in the brain","adm":"Oral, injectable","ind":"Schizophrenia, bipolar disorder","se":"Weight gain, drowsiness","fa":"One of the earlier second-generation antipsychotics, designed to reduce certain movement-related side effects"},
    {"n":"Olanzapine","fam":"Antipsychotic (second-generation)","yr":"1996","moa":"Blocks dopamine and serotonin receptors in the brain","adm":"Oral, injectable","ind":"Schizophrenia, bipolar disorder","se":"Significant weight gain, drowsiness","fa":"Effective for both psychotic and mood symptoms, though associated with notable weight gain in many patients"},
    {"n":"Clozapine","fam":"Antipsychotic (second-generation)","yr":"1972 (developed), 1989 (reintroduced with monitoring)","moa":"Blocks dopamine and serotonin receptors in the brain","adm":"Oral","ind":"Treatment-resistant schizophrenia","se":"Low white blood cell count (requires monitoring), drowsiness","fa":"Often reserved for treatment-resistant cases and requires regular blood monitoring due to a rare side effect"},
    {"n":"Quetiapine","fam":"Antipsychotic (second-generation)","yr":"1997","moa":"Blocks dopamine and serotonin receptors in the brain","adm":"Oral","ind":"Schizophrenia, bipolar disorder, depression (adjunct)","se":"Drowsiness, weight gain","fa":"Used both for psychotic disorders and, at lower doses, sometimes for sleep or mood symptoms"},
    {"n":"Aripiprazole","fam":"Antipsychotic (second-generation)","yr":"2002","moa":"Partially activates dopamine receptors rather than fully blocking them","adm":"Oral, injectable","ind":"Schizophrenia, bipolar disorder","se":"Restlessness, headache, less weight gain than some alternatives","fa":"Works differently from most antipsychotics by partially activating certain dopamine receptors rather than fully blocking them"},
    {"n":"Diazepam","fam":"Anxiolytic (benzodiazepine)","yr":"1963","moa":"Enhances the calming effect of a natural brain chemical called GABA","adm":"Oral, injectable, rectal","ind":"Anxiety, muscle spasms, seizures","se":"Drowsiness, dependence risk with prolonged use","fa":"One of the best-known benzodiazepines, introduced in the 1960s"},
    {"n":"Lorazepam","fam":"Anxiolytic (benzodiazepine)","yr":"1971","moa":"Enhances the calming effect of GABA in the brain","adm":"Oral, injectable","ind":"Anxiety, seizures","se":"Drowsiness, dependence risk with prolonged use","fa":"Often preferred in certain medical settings due to a more predictable duration of effect"},
    {"n":"Alprazolam","fam":"Anxiolytic (benzodiazepine)","yr":"1981","moa":"Enhances the calming effect of GABA in the brain","adm":"Oral","ind":"Anxiety, panic disorder","se":"Drowsiness, dependence risk with prolonged use","fa":"Fast-acting, which contributes to it being closely monitored for dependence risk"},
    {"n":"Zolpidem","fam":"Hypnotic (non-benzodiazepine)","yr":"1988","moa":"Enhances the calming effect of GABA in the brain, targeting sleep-specific receptors","adm":"Oral","ind":"Short-term insomnia","se":"Drowsiness, dizziness","fa":"Designed specifically for short-term sleep difficulties rather than general anxiety"},
    {"n":"Lithium","fam":"Mood stabilizer","yr":"1949","moa":"Not fully understood; affects multiple brain signaling pathways","adm":"Oral","ind":"Bipolar disorder","se":"Tremor, increased thirst, requires blood level monitoring","fa":"One of the simplest chemical elements ever used as a psychiatric medication, in use since the mid-20th century"},
    {"n":"Valproate","fam":"Mood stabilizer/anticonvulsant","yr":"1967","moa":"Increases levels of the calming brain chemical GABA","adm":"Oral, injectable","ind":"Bipolar disorder, epilepsy","se":"Weight gain, tremor","fa":"Used both to prevent seizures and to stabilize mood in certain psychiatric conditions"},
    {"n":"Lamotrigine","fam":"Mood stabilizer/anticonvulsant","yr":"1990","moa":"Stabilizes electrical activity in nerve cells","adm":"Oral","ind":"Bipolar disorder, epilepsy","se":"Skin rash (requires slow dose increase), headache","fa":"Requires a slow dose increase to reduce the risk of a rare but serious skin reaction"},
    {"n":"Carbamazepine","fam":"Mood stabilizer/anticonvulsant","yr":"1963","moa":"Stabilizes electrical activity in nerve cells","adm":"Oral","ind":"Epilepsy, bipolar disorder, nerve pain","se":"Dizziness, drowsiness","fa":"Also commonly used to treat a specific type of severe facial nerve pain"},
    {"n":"Methylphenidate","fam":"Stimulant (ADHD)","yr":"1944","moa":"Increases dopamine and noradrenaline availability in the brain","adm":"Oral","ind":"ADHD, narcolepsy","se":"Reduced appetite, insomnia","fa":"Despite being a stimulant, it has a calming, focus-improving effect in people with ADHD"},
    {"n":"Amphetamine","fam":"Stimulant (ADHD)","yr":"1887 (synthesized), 1930s (medical use)","moa":"Increases dopamine and noradrenaline availability in the brain","adm":"Oral","ind":"ADHD, narcolepsy","se":"Reduced appetite, insomnia, increased heart rate","fa":"Used medicinally since the early 20th century, now primarily prescribed for ADHD and narcolepsy"},
]

with open("assets/health/mental_medications.json", "w", encoding="utf-8") as f:
    json.dump(mental_medications, f, ensure_ascii=False, separators=(',', ':'))

print(f"{len(mental_medications)} mental health medications generated.")
