import json

islands = [
    # POLYNÉSIE FRANÇAISE — Society Islands
    {"n":"Tahiti","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":1045,"po":189517},
    {"n":"Moorea","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":134,"po":17191},
    {"n":"Bora Bora","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":38,"po":10605},
    {"n":"Raiatea","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":171,"po":12272},
    {"n":"Taha'a","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":88,"po":5000},
    {"n":"Huahine","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":75,"po":6075},
    {"n":"Maupiti","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":11,"po":1200},
    {"n":"Tetiaroa","ar":"Society Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":5,"po":0},
    # POLYNÉSIE FRANÇAISE — Marquises
    {"n":"Nuku Hiva","ar":"Marquesas Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":339,"po":3380},
    {"n":"Hiva Oa","ar":"Marquesas Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":315,"po":2190},
    {"n":"Ua Pou","ar":"Marquesas Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":105,"po":2200},
    {"n":"Ua Huka","ar":"Marquesas Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":83,"po":580},
    {"n":"Fatu Hiva","ar":"Marquesas Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":84,"po":631},
    {"n":"Tahuata","ar":"Marquesas Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":61,"po":668},
    # POLYNÉSIE FRANÇAISE — Tuamotu
    {"n":"Rangiroa","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":79,"po":2730},
    {"n":"Fakarava","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":16,"po":855},
    {"n":"Tikehau","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":21,"po":507},
    {"n":"Manihi","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":14,"po":900},
    {"n":"Makatea","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":28,"po":80},
    {"n":"Mataiva","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":26,"po":271},
    {"n":"Ahe","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":12,"po":500},
    {"n":"Niau","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":47,"po":200},
    {"n":"Hao","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":47,"po":1100},
    {"n":"Anaa","ar":"Tuamotu Archipelago","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":38,"po":400},
    # POLYNÉSIE FRANÇAISE — Australes
    {"n":"Rurutu","ar":"Austral Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":36,"po":2200},
    {"n":"Tubuai","ar":"Austral Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":45,"po":2100},
    {"n":"Raivavae","ar":"Austral Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":18,"po":900},
    {"n":"Rapa Iti","ar":"Austral Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":40,"po":484},
    {"n":"Rimatara","ar":"Austral Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":9,"po":800},
    # POLYNÉSIE FRANÇAISE — Gambier
    {"n":"Mangareva","ar":"Gambier Islands","te":"French Polynesia","co":"France","oc":"South Pacific","ar_km2":15,"po":1239},
    # NOUVELLE-CALÉDONIE
    {"n":"Grande Terre","ar":"New Caledonia","te":"New Caledonia","co":"France","oc":"South Pacific","ar_km2":16372,"po":213679},
    {"n":"Île des Pins","ar":"New Caledonia","te":"New Caledonia","co":"France","oc":"South Pacific","ar_km2":152,"po":2165},
    {"n":"Lifou","ar":"Loyalty Islands","te":"New Caledonia","co":"France","oc":"South Pacific","ar_km2":1150,"po":9275},
    {"n":"Maré","ar":"Loyalty Islands","te":"New Caledonia","co":"France","oc":"South Pacific","ar_km2":650,"po":7393},
    {"n":"Ouvéa","ar":"Loyalty Islands","te":"New Caledonia","co":"France","oc":"South Pacific","ar_km2":132,"po":3720},
    # WALLIS-ET-FUTUNA
    {"n":"Wallis","ar":"Wallis and Futuna","te":"Wallis and Futuna","co":"France","oc":"South Pacific","ar_km2":77,"po":9448},
    {"n":"Futuna","ar":"Wallis and Futuna","te":"Wallis and Futuna","co":"France","oc":"South Pacific","ar_km2":46,"po":4500},
    # VANUATU
    {"n":"Efate","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":900,"po":65790},
    {"n":"Espiritu Santo","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":3956,"po":36722},
    {"n":"Malekula","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":2053,"po":25241},
    {"n":"Tanna","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":550,"po":30000},
    {"n":"Ambrym","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":665,"po":7600},
    {"n":"Pentecost","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":490,"po":16000},
    {"n":"Epi","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":444,"po":5000},
    {"n":"Erromango","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":888,"po":1558},
    {"n":"Ambae","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":402,"po":9600},
    {"n":"Gaua","ar":"Banks Islands","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":341,"po":2800},
    {"n":"Maewo","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":304,"po":3600},
    {"n":"Aneityum","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":159,"po":865},
    {"n":"Tongoa","ar":"Shepherd Islands","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":62,"po":1800},
    {"n":"Malo","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":180,"po":5000},
    {"n":"Paama","ar":"Vanuatu","te":"Vanuatu","co":"Vanuatu","oc":"South Pacific","ar_km2":32,"po":2400},
    # FIDJI
    {"n":"Viti Levu","ar":"Fiji","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":10429,"po":600000},
    {"n":"Vanua Levu","ar":"Fiji","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":5587,"po":130000},
    {"n":"Taveuni","ar":"Fiji","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":470,"po":15000},
    {"n":"Kadavu","ar":"Fiji","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":411,"po":10000},
    {"n":"Ovalau","ar":"Lomaiviti","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":100,"po":8000},
    {"n":"Gau","ar":"Lomaiviti","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":140,"po":3300},
    {"n":"Koro","ar":"Lomaiviti","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":104,"po":4000},
    {"n":"Rotuma","ar":"Rotuma","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":44,"po":2000},
    {"n":"Yasawa","ar":"Yasawa Islands","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":33,"po":3000},
    {"n":"Qamea","ar":"Fiji","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":57,"po":3500},
    {"n":"Beqa","ar":"Fiji","te":"Fiji","co":"Fiji","oc":"South Pacific","ar_km2":36,"po":2500},
    # ÎLES SALOMON
    {"n":"Guadalcanal","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":5302,"po":93613},
    {"n":"Malaita","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":4307,"po":137596},
    {"n":"Makira","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":3188,"po":40400},
    {"n":"Santa Isabel","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":2999,"po":26370},
    {"n":"New Georgia","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":2145,"po":30000},
    {"n":"Choiseul","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":2971,"po":26372},
    {"n":"Rennell","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":660,"po":3000},
    {"n":"Kolombangara","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":190,"po":7000},
    {"n":"Vangunu","ar":"Solomon Islands","te":"Solomon Islands","co":"Solomon Islands","oc":"South Pacific","ar_km2":496,"po":5000},
    # PAPOUASIE-NOUVELLE-GUINÉE
    {"n":"New Britain","ar":"Papua New Guinea","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":35145,"po":544000},
    {"n":"New Ireland","ar":"Papua New Guinea","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":9600,"po":190000},
    {"n":"Bougainville","ar":"Papua New Guinea","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":9318,"po":300000},
    {"n":"Manus","ar":"Admiralty Islands","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":2100,"po":60000},
    {"n":"Fergusson","ar":"D'Entrecasteaux Islands","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":1437,"po":60000},
    {"n":"Goodenough","ar":"D'Entrecasteaux Islands","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":690,"po":27000},
    {"n":"Normanby","ar":"D'Entrecasteaux Islands","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":1011,"po":30000},
    {"n":"Kiriwina","ar":"Trobriand Islands","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":286,"po":30000},
    {"n":"Karkar","ar":"Papua New Guinea","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":362,"po":30000},
    {"n":"Woodlark","ar":"Papua New Guinea","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":835,"po":15000},
    {"n":"Long Island","ar":"Papua New Guinea","te":"Papua New Guinea","co":"Papua New Guinea","oc":"South Pacific","ar_km2":368,"po":5500},
    # SAMOA
    {"n":"Upolu","ar":"Samoa","te":"Samoa","co":"Samoa","oc":"South Pacific","ar_km2":1110,"po":134400},
    {"n":"Savai'i","ar":"Samoa","te":"Samoa","co":"Samoa","oc":"South Pacific","ar_km2":1694,"po":45000},
    {"n":"Manono","ar":"Samoa","te":"Samoa","co":"Samoa","oc":"South Pacific","ar_km2":3,"po":800},
    {"n":"Apolima","ar":"Samoa","te":"Samoa","co":"Samoa","oc":"South Pacific","ar_km2":1.5,"po":75},
    # TONGA
    {"n":"Tongatapu","ar":"Tonga","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":259,"po":74611},
    {"n":"'Eua","ar":"Tonga","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":87,"po":5100},
    {"n":"Vava'u","ar":"Vava'u Group","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":90,"po":15505},
    {"n":"Ha'apai","ar":"Ha'apai Group","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":110,"po":6616},
    {"n":"Niuafo'ou","ar":"Niuas","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":52,"po":578},
    {"n":"Niuatoputapu","ar":"Niuas","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":16,"po":1500},
    {"n":"Foa","ar":"Ha'apai Group","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":14,"po":2400},
    {"n":"Late","ar":"Vava'u Group","te":"Tonga","co":"Tonga","oc":"South Pacific","ar_km2":36,"po":0},
    # HAWAÏ
    {"n":"Hawaii (Big Island)","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":10432,"po":200629},
    {"n":"Maui","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":1883,"po":167417},
    {"n":"Oahu","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":1545,"po":1016508},
    {"n":"Kauai","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":1430,"po":72293},
    {"n":"Molokai","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":673,"po":7345},
    {"n":"Lanai","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":364,"po":3135},
    {"n":"Niihau","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":180,"po":130},
    {"n":"Kahoolawe","ar":"Hawaiian Islands","te":"Hawaii","co":"United States","oc":"North Pacific","ar_km2":115,"po":0},
    # GUAM & MARIANNES DU NORD
    {"n":"Guam","ar":"Mariana Islands","te":"Guam","co":"United States","oc":"Western Pacific","ar_km2":544,"po":153836},
    {"n":"Saipan","ar":"Mariana Islands","te":"Northern Mariana Islands","co":"United States","oc":"Western Pacific","ar_km2":115,"po":48220},
    {"n":"Rota","ar":"Mariana Islands","te":"Northern Mariana Islands","co":"United States","oc":"Western Pacific","ar_km2":85,"po":2572},
    {"n":"Tinian","ar":"Mariana Islands","te":"Northern Mariana Islands","co":"United States","oc":"Western Pacific","ar_km2":101,"po":3136},
    {"n":"Pagan","ar":"Mariana Islands","te":"Northern Mariana Islands","co":"United States","oc":"Western Pacific","ar_km2":47,"po":0},
    {"n":"Agrihan","ar":"Mariana Islands","te":"Northern Mariana Islands","co":"United States","oc":"Western Pacific","ar_km2":44,"po":0},
    # SAMOA AMÉRICAINES
    {"n":"Tutuila","ar":"American Samoa","te":"American Samoa","co":"United States","oc":"South Pacific","ar_km2":142,"po":55641},
    {"n":"Ta'u","ar":"Manu'a Islands","te":"American Samoa","co":"United States","oc":"South Pacific","ar_km2":44,"po":790},
    {"n":"Ofu","ar":"Manu'a Islands","te":"American Samoa","co":"United States","oc":"South Pacific","ar_km2":7.2,"po":300},
    {"n":"Rose Atoll","ar":"American Samoa","te":"American Samoa","co":"United States","oc":"South Pacific","ar_km2":0.7,"po":0},
    # MICRONÉSIE FSM
    {"n":"Pohnpei","ar":"Caroline Islands","te":"Micronesia","co":"Micronesia","oc":"Western Pacific","ar_km2":334,"po":34000},
    {"n":"Chuuk (Truk)","ar":"Caroline Islands","te":"Micronesia","co":"Micronesia","oc":"Western Pacific","ar_km2":127,"po":48654},
    {"n":"Yap","ar":"Caroline Islands","te":"Micronesia","co":"Micronesia","oc":"Western Pacific","ar_km2":102,"po":11000},
    {"n":"Kosrae","ar":"Caroline Islands","te":"Micronesia","co":"Micronesia","oc":"Western Pacific","ar_km2":110,"po":6200},
    # PALAOS
    {"n":"Babeldaob","ar":"Palau","te":"Palau","co":"Palau","oc":"Western Pacific","ar_km2":362,"po":6000},
    {"n":"Koror","ar":"Palau","te":"Palau","co":"Palau","oc":"Western Pacific","ar_km2":11,"po":11000},
    {"n":"Peleliu","ar":"Palau","te":"Palau","co":"Palau","oc":"Western Pacific","ar_km2":13,"po":700},
    {"n":"Angaur","ar":"Palau","te":"Palau","co":"Palau","oc":"Western Pacific","ar_km2":8,"po":300},
    {"n":"Kayangel","ar":"Palau","te":"Palau","co":"Palau","oc":"Western Pacific","ar_km2":1.8,"po":50},
    # ÎLES MARSHALL
    {"n":"Majuro","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":9.7,"po":27797},
    {"n":"Kwajalein","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":16,"po":11408},
    {"n":"Jaluit","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":11,"po":1600},
    {"n":"Mili","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":6,"po":800},
    {"n":"Wotje","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":7.8,"po":800},
    {"n":"Bikini Atoll","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":6,"po":0},
    {"n":"Enewetak","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":5.8,"po":650},
    {"n":"Rongelap","ar":"Marshall Islands","te":"Marshall Islands","co":"Marshall Islands","oc":"Central Pacific","ar_km2":7.9,"po":0},
    # KIRIBATI
    {"n":"Tarawa","ar":"Kiribati","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":31,"po":63017},
    {"n":"Kiritimati (Christmas)","ar":"Line Islands","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":321,"po":6447},
    {"n":"Abaiang","ar":"Gilbert Islands","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":16,"po":5500},
    {"n":"Butaritari","ar":"Gilbert Islands","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":14,"po":4600},
    {"n":"Banaba (Ocean)","ar":"Kiribati","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":6,"po":300},
    {"n":"Tabiteuea","ar":"Gilbert Islands","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":38,"po":4600},
    {"n":"Marakei","ar":"Gilbert Islands","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":13,"po":2600},
    {"n":"Nonouti","ar":"Gilbert Islands","te":"Kiribati","co":"Kiribati","oc":"Central Pacific","ar_km2":30,"po":3200},
    # TUVALU
    {"n":"Funafuti","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":2.4,"po":6025},
    {"n":"Nanumea","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":3.9,"po":700},
    {"n":"Nanumanga","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":3.0,"po":600},
    {"n":"Nui","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":2.8,"po":548},
    {"n":"Vaitupu","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":5.6,"po":1591},
    {"n":"Niutao","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":2.5,"po":663},
    {"n":"Nukufetau","ar":"Tuvalu","te":"Tuvalu","co":"Tuvalu","oc":"Central Pacific","ar_km2":2.9,"po":586},
    # NAURU
    {"n":"Nauru","ar":"Nauru","te":"Nauru","co":"Nauru","oc":"Central Pacific","ar_km2":21,"po":10873},
    # ÎLES COOK
    {"n":"Rarotonga","ar":"Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":67,"po":14974},
    {"n":"Aitutaki","ar":"Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":18,"po":2038},
    {"n":"Atiu","ar":"Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":27,"po":480},
    {"n":"Ma'uke","ar":"Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":18,"po":300},
    {"n":"Mitiaro","ar":"Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":22,"po":200},
    {"n":"Mangaia","ar":"Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":52,"po":500},
    {"n":"Manihiki","ar":"Northern Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":5.4,"po":238},
    {"n":"Penrhyn (Tongareva)","ar":"Northern Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":9.8,"po":357},
    {"n":"Nassau","ar":"Northern Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":1.2,"po":70},
    {"n":"Suwarrow","ar":"Northern Cook Islands","te":"Cook Islands","co":"New Zealand","oc":"South Pacific","ar_km2":0.4,"po":0},
    # NIUE
    {"n":"Niue","ar":"Niue","te":"Niue","co":"New Zealand","oc":"South Pacific","ar_km2":260,"po":1549},
    # TOKELAU
    {"n":"Atafu","ar":"Tokelau","te":"Tokelau","co":"New Zealand","oc":"South Pacific","ar_km2":2.0,"po":500},
    {"n":"Fakaofo","ar":"Tokelau","te":"Tokelau","co":"New Zealand","oc":"South Pacific","ar_km2":2.6,"po":500},
    {"n":"Nukunonu","ar":"Tokelau","te":"Tokelau","co":"New Zealand","oc":"South Pacific","ar_km2":4.7,"po":400},
    # ÎLE DE PÂQUES
    {"n":"Easter Island (Rapa Nui)","ar":"Easter Island","te":"Valparaíso Region","co":"Chile","oc":"South Pacific","ar_km2":163,"po":7750},
    # NORFOLK & LORD HOWE
    {"n":"Norfolk Island","ar":"Norfolk Island","te":"Norfolk Island","co":"Australia","oc":"South Pacific","ar_km2":35,"po":2188},
    {"n":"Lord Howe Island","ar":"Lord Howe Island","te":"New South Wales","co":"Australia","oc":"Tasman Sea","ar_km2":14,"po":382},
    # ÎLES CHATHAM
    {"n":"Chatham Island","ar":"Chatham Islands","te":"Chatham Islands","co":"New Zealand","oc":"South Pacific","ar_km2":900,"po":663},
    {"n":"Pitt Island","ar":"Chatham Islands","te":"Chatham Islands","co":"New Zealand","oc":"South Pacific","ar_km2":62,"po":40},
    # PITCAIRN
    {"n":"Pitcairn","ar":"Pitcairn Islands","te":"Pitcairn Islands","co":"United Kingdom","oc":"South Pacific","ar_km2":47,"po":50},
    # ÎLES MINEURES US
    {"n":"Midway Atoll","ar":"US Minor Outlying Islands","te":"Midway Atoll","co":"United States","oc":"North Pacific","ar_km2":6.2,"po":40},
    {"n":"Wake Island","ar":"US Minor Outlying Islands","te":"Wake Island","co":"United States","oc":"North Pacific","ar_km2":7.8,"po":150},
    {"n":"Johnston Atoll","ar":"US Minor Outlying Islands","te":"Johnston Atoll","co":"United States","oc":"North Pacific","ar_km2":2.8,"po":0},
    {"n":"Jarvis Island","ar":"US Minor Outlying Islands","te":"Jarvis Island","co":"United States","oc":"South Pacific","ar_km2":4.5,"po":0},
    {"n":"Howland Island","ar":"US Minor Outlying Islands","te":"Howland Island","co":"United States","oc":"Central Pacific","ar_km2":1.6,"po":0},
    {"n":"Baker Island","ar":"US Minor Outlying Islands","te":"Baker Island","co":"United States","oc":"Central Pacific","ar_km2":1.4,"po":0},
    # JAPON — Ryukyu & Ogasawara
    {"n":"Okinawa","ar":"Ryukyu Islands","te":"Okinawa Prefecture","co":"Japan","oc":"Western Pacific","ar_km2":1207,"po":1472480},
    {"n":"Miyako-jima","ar":"Miyako Islands","te":"Okinawa Prefecture","co":"Japan","oc":"Western Pacific","ar_km2":158,"po":55000},
    {"n":"Ishigaki","ar":"Yaeyama Islands","te":"Okinawa Prefecture","co":"Japan","oc":"Western Pacific","ar_km2":223,"po":48000},
    {"n":"Iriomote","ar":"Yaeyama Islands","te":"Okinawa Prefecture","co":"Japan","oc":"Western Pacific","ar_km2":289,"po":2432},
    {"n":"Amami Oshima","ar":"Amami Islands","te":"Kagoshima Prefecture","co":"Japan","oc":"Western Pacific","ar_km2":712,"po":58000},
    {"n":"Iwo Jima","ar":"Volcano Islands","te":"Tokyo Metropolis","co":"Japan","oc":"North Pacific","ar_km2":21,"po":0},
    {"n":"Chichijima","ar":"Ogasawara Islands","te":"Tokyo Metropolis","co":"Japan","oc":"North Pacific","ar_km2":24,"po":2017},
    {"n":"Hahajima","ar":"Ogasawara Islands","te":"Tokyo Metropolis","co":"Japan","oc":"North Pacific","ar_km2":19,"po":450},
    # TAÏWAN
    {"n":"Green Island","ar":"Taiwan","te":"Taitung County","co":"Taiwan","oc":"Western Pacific","ar_km2":15,"po":3000},
    {"n":"Orchid Island","ar":"Taiwan","te":"Taitung County","co":"Taiwan","oc":"Western Pacific","ar_km2":45,"po":4500},
    # INDONÉSIE
    {"n":"Halmahera","ar":"Maluku Islands","te":"North Maluku","co":"Indonesia","oc":"Western Pacific","ar_km2":17780,"po":162000},
    {"n":"Morotai","ar":"Maluku Islands","te":"North Maluku","co":"Indonesia","oc":"Western Pacific","ar_km2":1800,"po":60000},
    {"n":"Biak","ar":"Cenderawasih Bay","te":"Papua","co":"Indonesia","oc":"Western Pacific","ar_km2":1900,"po":100000},
    {"n":"Seram","ar":"Maluku Islands","te":"Maluku","co":"Indonesia","oc":"Western Pacific","ar_km2":17100,"po":400000},
    {"n":"Ambon","ar":"Maluku Islands","te":"Maluku","co":"Indonesia","oc":"Western Pacific","ar_km2":761,"po":331000},
    # PHILIPPINES
    {"n":"Luzon","ar":"Philippines","te":"Multiple provinces","co":"Philippines","oc":"Western Pacific","ar_km2":109964,"po":64000000},
    {"n":"Mindanao","ar":"Philippines","te":"Multiple provinces","co":"Philippines","oc":"Western Pacific","ar_km2":97530,"po":25000000},
    {"n":"Samar","ar":"Philippines","te":"Eastern Visayas","co":"Philippines","oc":"Western Pacific","ar_km2":13429,"po":1700000},
    {"n":"Leyte","ar":"Philippines","te":"Eastern Visayas","co":"Philippines","oc":"Western Pacific","ar_km2":7214,"po":2000000},
    {"n":"Negros","ar":"Philippines","te":"Western Visayas","co":"Philippines","oc":"Western Pacific","ar_km2":13309,"po":4000000},
    {"n":"Cebu","ar":"Philippines","te":"Central Visayas","co":"Philippines","oc":"Western Pacific","ar_km2":4468,"po":5000000},
    {"n":"Palawan","ar":"Philippines","te":"Palawan Province","co":"Philippines","oc":"Western Pacific","ar_km2":14650,"po":1000000},
]

with open("assets/pacific_islands.json", "w", encoding="utf-8") as f:
    json.dump(islands, f, ensure_ascii=False, separators=(',', ':'))

print(f"{len(islands)} iles générées.")