import 'package:flutter/material.dart';
import '../../generated/app_localizations.dart';

part './content_type_labels.dart';
part './content_type_icons.dart';
part './content_type_colors.dart';
part './content_type_gradients.dart';
part './content_type_accent_colors.dart';
part './content_type_api.dart';

enum ContentType {
  anecdote,
  chuckNorris,
  celebrityQuote,
  history,
  kingOfFrance,
  americanPresident,
  historyHub,
  animals,
  country,
  frenchDepartment,
  pacificIsland,
  world,
  exoplanet,
  star,
  solarSystemMoon,
  space,
  cinemaHub,
  classicCinema,
  cinema80s90s,
  modernCinema,
  celebrityHub,
  scienceHub,
  dinosaur,
  spaceMission,
  battle,
  artHub,
  painting,
  sculpture,
  architecture,
  famousArtist,
  photographer,
  classicalComposer,
  nobelPrize,
  frenchCommune,
  americanState,
  scienceLivingHub,
  scienceNonLivingHub,
  artWorksHub,
  artArtistsHub,
  chemicalElement,
  volcano,
  insect,
  bird,
  mineral,
  cloud,
  humanBone,
  territoriesHub,
  naturalWondersHub,
  humorHub,
  personalityHub,
  lgbtqiaPersonality,
  pioneerWoman,
  legendaryAthlete,
}
