part of 'content_type.dart';

extension ContentTypeLabels on ContentType {
  String get title {
    switch (this) {
      case ContentType.anecdote:           return 'Anecdote';
      case ContentType.chuckNorris:        return 'Chuck Norris';
      case ContentType.celebrityQuote:     return 'Celebrity Quote';
      case ContentType.history:            return 'Day of History';
      case ContentType.kingOfFrance:       return 'Kings of France';
      case ContentType.americanPresident:  return 'American Presidents';
      case ContentType.historyHub:         return 'History';
      case ContentType.animals:            return 'Animals';
      case ContentType.frenchDepartment:   return 'French Department';
      case ContentType.pacificIsland:      return 'Pacific Island';
      case ContentType.country:            return 'Countries';
      case ContentType.world:              return 'World';
      case ContentType.exoplanet:          return 'Exoplanet';
      case ContentType.star:               return 'Star';
      case ContentType.solarSystemMoon:    return 'Moon';
      case ContentType.space:              return 'Space';
      case ContentType.cinemaHub:          return 'Cinema';
      case ContentType.classicCinema:      return 'Classic Hollywood';
      case ContentType.cinema80s90s:       return '80s & 90s Movies';
      case ContentType.modernCinema:       return 'Modern Cinema';
      case ContentType.celebrityHub:       return 'Celebrity';
      case ContentType.scienceHub:         return 'Science & Nature';
      case ContentType.dinosaur:           return 'Dinosaurs';
      case ContentType.spaceMission:       return 'Space Missions';
      case ContentType.battle:             return 'Historical Battles';
      case ContentType.artHub:             return 'Art & Culture';
      case ContentType.painting:           return 'Famous Paintings';
      case ContentType.sculpture:          return 'Famous Sculptures';
      case ContentType.architecture:       return 'Iconic Architecture';
      case ContentType.famousArtist:       return 'Famous Artists';
      case ContentType.photographer:       return 'Photographers';
      case ContentType.classicalComposer:  return 'Classical Composers';
      case ContentType.nobelPrize:         return 'Nobel Prize';
      case ContentType.frenchCommune:      return 'French Communes';
      case ContentType.americanState:      return 'American States';
      case ContentType.scienceLivingHub:   return 'Living World';
      case ContentType.scienceNonLivingHub: return 'Non-Living';
      case ContentType.artWorksHub:        return 'Art Works';
      case ContentType.artArtistsHub:      return 'Artists';
      case ContentType.chemicalElement:    return 'Chemical Elements';
      case ContentType.volcano:            return 'Volcanoes';
      case ContentType.insect:             return 'Insects';
      case ContentType.bird:               return 'Birds';
      case ContentType.mineral:            return 'Minerals';
      case ContentType.cloud:              return 'Clouds';
      case ContentType.humanBone:          return 'Human Bones';
      case ContentType.territoriesHub:     return 'Territories';
      case ContentType.naturalWondersHub:  return 'Natural Wonders';
      case ContentType.humorHub:           return 'Humor';
      case ContentType.personalityHub:     return 'Personalities';
      case ContentType.lgbtqiaPersonality: return 'LGBTQIA+';
      case ContentType.pioneerWoman:       return 'Pioneer Women';
      case ContentType.legendaryAthlete:   return 'Legendary Athletes';
      case ContentType.desert:             return 'Deserts';
      case ContentType.river:              return 'Rivers';
      case ContentType.sea:                return 'Seas';
      case ContentType.gamingHub:          return 'Gaming';
      case ContentType.gamesHub:           return 'Games';
      case ContentType.gamersHub:          return 'Gamers';
      case ContentType.gamingAnecdote:     return 'Gaming Trivia';
      case ContentType.gamingNomination:   return 'Game Awards';
      case ContentType.classicGame:        return 'Classic Games';
      case ContentType.worstGame:          return 'Worst Games';
      case ContentType.bannedGame:         return 'Banned Games';
      case ContentType.gamingLegend:       return 'Gaming Legends';
      case ContentType.musicHub:           return 'Music';
      case ContentType.musicLegend:        return 'Music Legends';
      case ContentType.album:              return 'Iconic Albums';
      case ContentType.instrument:         return 'Instruments';
      case ContentType.musicFestival:      return 'Music Festivals';
      case ContentType.musicAward:         return 'Music Awards';
      case ContentType.mythologyHub:       return 'Mythology';
      case ContentType.greekMythology:     return 'Greek & Roman Mythology';
      case ContentType.norseMythology:     return 'Norse Mythology';
      case ContentType.egyptianMythology:  return 'Egyptian Mythology';
      case ContentType.mythologicalCreature: return 'Mythological Creatures';
    }
  }

  String localizedTitle(AppLocalizations loc) {
    switch (this) {
      case ContentType.anecdote:           return loc.categoryAnecdote;
      case ContentType.chuckNorris:        return loc.categoryChuckNorris;
      case ContentType.celebrityQuote:     return loc.categoryAdvice;
      case ContentType.history:            return loc.categoryDayOfHistory;
      case ContentType.kingOfFrance:       return loc.categoryKingOfFrance;
      case ContentType.americanPresident:  return loc.categoryAmericanPresident;
      case ContentType.historyHub:         return loc.categoryHistoryHub;
      case ContentType.animals:            return loc.categoryAnimals;
      case ContentType.country:            return loc.categoryCountry;
      case ContentType.frenchDepartment:   return loc.categoryFrenchDepartment;
      case ContentType.pacificIsland:      return loc.categoryPacificIsland;
      case ContentType.world:              return loc.categoryWorld;
      case ContentType.exoplanet:          return loc.categoryExoplanet;
      case ContentType.star:               return loc.categoryStar;
      case ContentType.solarSystemMoon:    return loc.categorySolarSystemMoon;
      case ContentType.space:              return loc.categorySpace;
      case ContentType.cinemaHub:          return loc.categoryCinemaHub;
      case ContentType.classicCinema:      return loc.categoryClassicCinema;
      case ContentType.cinema80s90s:       return loc.categoryCinema80s90s;
      case ContentType.modernCinema:       return loc.categoryModernCinema;
      case ContentType.celebrityHub:       return loc.categoryCelebrityHub;
      case ContentType.scienceHub:         return loc.categoryScienceHub;
      case ContentType.dinosaur:           return loc.categoryDinosaur;
      case ContentType.spaceMission:       return loc.categorySpaceMission;
      case ContentType.battle:             return loc.categoryBattle;
      case ContentType.artHub:             return loc.categoryArtHub;
      case ContentType.painting:           return loc.categoryPainting;
      case ContentType.sculpture:          return loc.categorySculpture;
      case ContentType.architecture:       return loc.categoryArchitecture;
      case ContentType.famousArtist:       return loc.categoryFamousArtist;
      case ContentType.photographer:       return loc.categoryPhotographer;
      case ContentType.classicalComposer:  return loc.categoryClassicalComposer;
      case ContentType.nobelPrize:         return loc.categoryNobelPrize;
      case ContentType.frenchCommune:      return loc.categoryFrenchCommune;
      case ContentType.americanState:      return loc.categoryAmericanState;
      case ContentType.scienceLivingHub:   return loc.categoryScienceLivingHub;
      case ContentType.scienceNonLivingHub: return loc.categoryScienceNonLivingHub;
      case ContentType.artWorksHub:        return loc.categoryArtWorksHub;
      case ContentType.artArtistsHub:      return loc.categoryArtArtistsHub;
      case ContentType.chemicalElement:    return loc.categoryChemicalElement;
      case ContentType.volcano:            return loc.categoryVolcano;
      case ContentType.insect:             return loc.categoryInsect;
      case ContentType.bird:               return loc.categoryBird;
      case ContentType.mineral:            return loc.categoryMineral;
      case ContentType.cloud:              return loc.categoryCloud;
      case ContentType.humanBone:          return loc.categoryHumanBone;
      case ContentType.territoriesHub:     return loc.categoryTerritoriesHub;
      case ContentType.naturalWondersHub:  return loc.categoryNaturalWondersHub;
      case ContentType.humorHub:           return loc.categoryHumorHub;
      case ContentType.personalityHub:     return loc.categoryPersonalityHub;
      case ContentType.lgbtqiaPersonality: return loc.categoryLgbtqiaPersonality;
      case ContentType.pioneerWoman:       return loc.categoryPioneerWoman;
      case ContentType.legendaryAthlete:   return loc.categoryLegendaryAthlete;
      case ContentType.desert:             return loc.categoryDesert;
      case ContentType.river:              return loc.categoryRiver;
      case ContentType.sea:                return loc.categorySea;
      case ContentType.gamingHub:          return loc.categoryGamingHub;
      case ContentType.gamesHub:           return loc.categoryGamesHub;
      case ContentType.gamersHub:          return loc.categoryGamersHub;
      case ContentType.gamingAnecdote:     return loc.categoryGamingAnecdote;
      case ContentType.gamingNomination:   return loc.categoryGamingNomination;
      case ContentType.classicGame:        return loc.categoryClassicGame;
      case ContentType.worstGame:          return loc.categoryWorstGame;
      case ContentType.bannedGame:         return loc.categoryBannedGame;
      case ContentType.gamingLegend:       return loc.categoryGamingLegend;
      case ContentType.musicHub:           return loc.categoryMusicHub;
      case ContentType.musicLegend:        return loc.categoryMusicLegend;
      case ContentType.album:              return loc.categoryAlbum;
      case ContentType.instrument:         return loc.categoryInstrument;
      case ContentType.musicFestival:      return loc.categoryMusicFestival;
      case ContentType.musicAward:         return loc.categoryMusicAward;
      case ContentType.mythologyHub:       return loc.categoryMythologyHub;
      case ContentType.greekMythology:     return loc.categoryGreekMythology;
      case ContentType.norseMythology:     return loc.categoryNorseMythology;
      case ContentType.egyptianMythology:  return loc.categoryEgyptianMythology;
      case ContentType.mythologicalCreature: return loc.categoryMythologicalCreature;
    }
  }
}
