import json

# RÈGLE : q_en=None si ql=="en", q_fr=None si ql=="fr", q_es=None si ql=="es"
# fi_fr=None si titre identique à fi OU si ql=="fr"
# fi_es=None si titre identique à fi OU si ql=="es"
# fi_en=None si ql=="en"
# Toutes les années sont entre 1980 et 1999 incluses

quotes = [
    # ── FILMS EN LANGUE ANGLAISE ───────────────────────────────────────────
    {"q":"Here's Johnny!","ql":"en","fi":"The Shining","fi_fr":"Shining","fi_es":"El resplandor","ch":"Jack Torrance","ac":"Jack Nicholson","di":"Stanley Kubrick","yr":1980,"ty":None,"ti":"~01h45m — Climax","co":"Jack breaks through the bathroom door with an axe, referencing The Tonight Show","q_en":None,"q_fr":"Voilà Johnny !","q_es":"¡Aquí está Johnny!"},
    {"q":"I am your father.","ql":"en","fi":"The Empire Strikes Back","fi_fr":"L'Empire contre-attaque","fi_es":"El Imperio contraataca","ch":"Darth Vader","ac":"David Prowse / James Earl Jones (voice)","di":"Irvin Kershner","yr":1980,"ty":"sequel","ti":"~01h45m — Climax","co":"Vader reveals the shocking truth to Luke during their lightsaber duel on Cloud City, Bespin","q_en":None,"q_fr":"Je suis ton père.","q_es":"Yo soy tu padre."},
    {"q":"Do, or do not. There is no try.","ql":"en","fi":"The Empire Strikes Back","fi_fr":"L'Empire contre-attaque","fi_es":"El Imperio contraataca","ch":"Yoda","ac":"Frank Oz (voice)","di":"Irvin Kershner","yr":1980,"ty":"sequel","ti":"~01h02m — Act 2","co":"Yoda teaches Luke the philosophy of the Force during his training on Dagobah","q_en":None,"q_fr":"Fais-le ou ne le fais pas. Il n'y a pas d'essai.","q_es":"Hazlo o no lo hagas. Pero no lo intentes."},
    {"q":"It's not the years, honey. It's the mileage.","ql":"en","fi":"Raiders of the Lost Ark","fi_fr":"Les Aventuriers de l'arche perdue","fi_es":"En busca del arca perdida","ch":"Indiana Jones","ac":"Harrison Ford","di":"Steven Spielberg","yr":1981,"ty":None,"ti":"~00h22m — Act 1","co":"Indy brushes off Marion's comment about how old he looks","q_en":None,"q_fr":"Ce ne sont pas les années, chérie. C'est le kilométrage.","q_es":"No son los años, cariño. Es el kilometraje."},
    {"q":"E.T. phone home.","ql":"en","fi":"E.T. the Extra-Terrestrial","fi_fr":"E.T. l'extra-terrestre","fi_es":"E.T. el extraterrestre","ch":"E.T.","ac":"Pat Welsh (voice)","di":"Steven Spielberg","yr":1982,"ty":None,"ti":"~01h10m — Act 2","co":"E.T. tells Elliott his plan to contact his home planet using makeshift radio equipment","q_en":None,"q_fr":"E.T. téléphone maison.","q_es":"E.T. llamar a casa."},
    {"q":"Say hello to my little friend!","ql":"en","fi":"Scarface","fi_fr":"Scarface","fi_es":"Scarface","ch":"Tony Montana","ac":"Al Pacino","di":"Brian De Palma","yr":1983,"ty":None,"ti":"~02h38m — Climax","co":"Tony emerges with an M16/M203 grenade launcher during the final ambush on his mansion","q_en":None,"q_fr":"Dis bonjour à mon petit ami !","q_es":"¡Saluda a mi pequeño amigo!"},
    {"q":"Go ahead, make my day.","ql":"en","fi":"Sudden Impact","fi_fr":"Le Retour de l'inspecteur Harry","fi_es":"Impacto súbito","ch":"Harry Callahan","ac":"Clint Eastwood","di":"Clint Eastwood","yr":1983,"ty":"sequel","ti":"~00h05m — Opening","co":"Harry taunts a gunman holding a woman hostage, daring him to give him a reason to shoot","q_en":None,"q_fr":"Vas-y, fais-moi plaisir.","q_es":"Adelante, alégrame el día."},
    {"q":"I'll be back.","ql":"en","fi":"The Terminator","fi_fr":"Terminator","fi_es":"Terminator","ch":"The Terminator","ac":"Arnold Schwarzenegger","di":"James Cameron","yr":1984,"ty":None,"ti":"~00h56m — Act 2","co":"The Terminator warns a police desk sergeant before returning to destroy the station","q_en":None,"q_fr":"Je reviendrai.","q_es":"Volveré."},
    {"q":"Wax on, wax off.","ql":"en","fi":"The Karate Kid","fi_fr":"Karaté Kid","fi_es":"Karate Kid","ch":"Mr. Miyagi","ac":"Pat Morita","di":"John G. Avildsen","yr":1984,"ty":None,"ti":"~00h48m — Act 2","co":"Miyagi teaches Daniel karate through disguised chores: waxing cars and painting fences","q_en":None,"q_fr":"Encaustique là, encaustique là.","q_es":"Encera, desencera."},
    {"q":"Roads? Where we're going, we don't need roads.","ql":"en","fi":"Back to the Future","fi_fr":"Retour vers le futur","fi_es":"Regreso al futuro","ch":"Dr. Emmett Brown","ac":"Christopher Lloyd","di":"Robert Zemeckis","yr":1985,"ty":None,"ti":"~01h56m — Final scene","co":"Doc reveals the DeLorean can now fly as they prepare to travel to 2015","q_en":None,"q_fr":"Des routes ? Là où on va, on n'a pas besoin de routes.","q_es":"¿Carreteras? Donde vamos no necesitamos carreteras."},
    {"q":"Bueller? Bueller?","ql":"en","fi":"Ferris Bueller's Day Off","fi_fr":"La Folle Journée de Ferris Bueller","fi_es":"Todo en un día","ch":"Economics Teacher","ac":"Ben Stein","di":"John Hughes","yr":1986,"ty":None,"ti":"~00h06m — Opening","co":"The monotone teacher calls out to an absent Ferris Bueller to his bored class","q_en":None,"q_fr":"Bueller ? Bueller ?","q_es":"¿Bueller? ¿Bueller?"},
    {"q":"Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.","ql":"en","fi":"Ferris Bueller's Day Off","fi_fr":"La Folle Journée de Ferris Bueller","fi_es":"Todo en un día","ch":"Ferris Bueller","ac":"Matthew Broderick","di":"John Hughes","yr":1986,"ty":None,"ti":"~01h37m — Final scene","co":"Ferris breaks the fourth wall to deliver his philosophy of life to the audience","q_en":None,"q_fr":"La vie va vite. Si tu ne t'arrêtes pas pour regarder autour de toi de temps en temps, tu pourrais la rater.","q_es":"La vida pasa muy deprisa. Si no te paras a mirar a tu alrededor de vez en cuando, podrías perdértela."},
    {"q":"I feel the need... the need for speed!","ql":"en","fi":"Top Gun","fi_fr":"Top Gun","fi_es":"Top Gun","ch":"Maverick & Goose","ac":"Tom Cruise & Anthony Edwards","di":"Tony Scott","yr":1986,"ty":None,"ti":"~00h14m — Act 1","co":"Maverick and his co-pilot celebrate after a dangerous dogfight maneuver","q_en":None,"q_fr":"J'ai besoin... besoin de vitesse !","q_es":"¡Siento la necesidad... la necesidad de velocidad!"},
    {"q":"Greed, for lack of a better word, is good.","ql":"en","fi":"Wall Street","fi_fr":"Wall Street","fi_es":"Wall Street","ch":"Gordon Gekko","ac":"Michael Douglas","di":"Oliver Stone","yr":1987,"ty":None,"ti":"~00h52m — Act 2","co":"Gekko delivers his infamous shareholder speech defending corporate greed at Teldar Paper","q_en":None,"q_fr":"L'avidité, faute d'un meilleur mot, c'est bien.","q_es":"La codicia, a falta de una palabra mejor, es buena."},
    {"q":"Get to the choppah!","ql":"en","fi":"Predator","fi_fr":"Predator","fi_es":"Depredador","ch":"Major Alan Schaefer","ac":"Arnold Schwarzenegger","di":"John McTiernan","yr":1987,"ty":None,"ti":"~01h20m — Act 3","co":"Dutch orders his team to evacuate immediately as the alien Predator closes in","q_en":None,"q_fr":"Allez à l'hélicoptère !","q_es":"¡Al helicóptero!"},
    {"q":"Nobody puts Baby in a corner.","ql":"en","fi":"Dirty Dancing","fi_fr":"Dirty Dancing","fi_es":"Dirty Dancing","ch":"Johnny Castle","ac":"Patrick Swayze","di":"Emile Ardolino","yr":1987,"ty":None,"ti":"~01h36m — Final scene","co":"Johnny storms into the end-of-summer show to defend Baby against her disapproving father","q_en":None,"q_fr":"Personne ne met Baby dans un coin.","q_es":"Nadie pone a Baby en un rincón."},
    {"q":"What is your major malfunction?","ql":"en","fi":"Full Metal Jacket","fi_fr":"Full Metal Jacket","fi_es":"La chaqueta metálica","ch":"Gunnery Sergeant Hartman","ac":"R. Lee Ermey","di":"Stanley Kubrick","yr":1987,"ty":None,"ti":"~00h45m — Act 1","co":"Hartman screams at Private Pyle after discovering jelly donuts hidden in his footlocker","q_en":None,"q_fr":"C'est quoi ton gros problème ?","q_es":"¿Cuál es tu maldito problema?"},
    {"q":"Yippee-ki-yay, motherfucker.","ql":"en","fi":"Die Hard","fi_fr":"Piège de cristal","fi_es":"Jungla de cristal","ch":"John McClane","ac":"Bruce Willis","di":"John McTiernan","yr":1988,"ty":None,"ti":"~00h44m — Act 2","co":"McClane's defiant catchphrase as he taunts terrorist Hans Gruber over the radio","q_en":None,"q_fr":"Yippee-ki-yay, sale con.","q_es":"Yippee-ki-yay, maldito."},
    {"q":"I'll have what she's having.","ql":"en","fi":"When Harry Met Sally","fi_fr":"Quand Harry rencontre Sally...","fi_es":"Cuando Harry encontró a Sally...","ch":"Customer","ac":"Estelle Reiner","di":"Rob Reiner","yr":1989,"ty":None,"ti":"~00h32m — Act 1","co":"An older diner customer responds to Sally's convincing fake orgasm performance","q_en":None,"q_fr":"Je prendrai la même chose qu'elle.","q_es":"Lo mismo que ella, por favor."},
    {"q":"Carpe diem. Seize the day, boys.","ql":"en","fi":"Dead Poets Society","fi_fr":"Le Cercle des poètes disparus","fi_es":"El club de los poetas muertos","ch":"John Keating","ac":"Robin Williams","di":"Peter Weir","yr":1989,"ty":None,"ti":"~00h18m — Act 1","co":"Mr. Keating urges his students to make their lives extraordinary","q_en":None,"q_fr":"Carpe diem. Saisissez le jour, les garçons.","q_es":"Carpe diem. Aprovechad el día, chicos."},
    {"q":"Oh captain, my captain.","ql":"en","fi":"Dead Poets Society","fi_fr":"Le Cercle des poètes disparus","fi_es":"El club de los poetas muertos","ch":"Todd Anderson","ac":"Ethan Hawke","di":"Peter Weir","yr":1989,"ty":None,"ti":"~01h55m — Final scene","co":"Todd and his classmates stand on their desks to honor the dismissed Mr. Keating","q_en":None,"q_fr":"Ô capitaine, mon capitaine.","q_es":"Oh capitán, mi capitán."},
    {"q":"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.","ql":"en","fi":"The Silence of the Lambs","fi_fr":"Le Silence des agneaux","fi_es":"El silencio de los corderos","ch":"Hannibal Lecter","ac":"Anthony Hopkins","di":"Jonathan Demme","yr":1991,"ty":None,"ti":"~00h22m — Act 1","co":"Lecter describes a past victim to Clarice through his cell bars with a chilling smile","q_en":None,"q_fr":"Un agent de recensement a essayé de me tester un jour. J'ai mangé son foie avec des fèves et un excellent Chianti.","q_es":"Una vez un recaudador intentó interrogarme. Me comí su hígado con habas y un buen Chianti."},
    {"q":"Hasta la vista, baby.","ql":"en","fi":"Terminator 2: Judgment Day","fi_fr":"Terminator 2 : Le Jugement dernier","fi_es":"Terminator 2: El juicio final","ch":"T-800","ac":"Arnold Schwarzenegger","di":"James Cameron","yr":1991,"ty":"sequel","ti":"~01h33m — Act 3","co":"T-800 says goodbye to the frozen T-1000 just before shattering him","q_en":None,"q_fr":"Hasta la vista, bébé.","q_es":"Hasta la vista, baby."},
    {"q":"You can't handle the truth!","ql":"en","fi":"A Few Good Men","fi_fr":"Des hommes d'honneur","fi_es":"Algunos hombres buenos","ch":"Colonel Nathan R. Jessup","ac":"Jack Nicholson","di":"Rob Reiner","yr":1992,"ty":None,"ti":"~01h41m — Climax","co":"Colonel Jessup explodes on the witness stand when pressed about ordering the Code Red","q_en":None,"q_fr":"Tu ne peux pas supporter la vérité !","q_es":"¡No puedes manejar la verdad!"},
    {"q":"Get busy living, or get busy dying.","ql":"en","fi":"The Shawshank Redemption","fi_fr":"Les Évadés","fi_es":"Cadena perpetua","ch":"Andy Dufresne","ac":"Tim Robbins","di":"Frank Darabont","yr":1994,"ty":None,"ti":"~01h32m — Act 3","co":"Andy's letter to Red explains his philosophy and reveals he has escaped Shawshank","q_en":None,"q_fr":"Occupe-toi à vivre ou occupe-toi à mourir.","q_es":"O te ocupas de vivir o te ocupas de morir."},
    {"q":"My mama always said life was like a box of chocolates. You never know what you're gonna get.","ql":"en","fi":"Forrest Gump","fi_fr":"Forrest Gump","fi_es":"Forrest Gump","ch":"Forrest Gump","ac":"Tom Hanks","di":"Robert Zemeckis","yr":1994,"ty":None,"ti":"~00h02m — Opening","co":"Forrest quotes his mother's wisdom while waiting for a bus at a Savannah bench","q_en":None,"q_fr":"Maman disait toujours que la vie, c'est comme une boîte de chocolats : on ne sait jamais sur quoi on va tomber.","q_es":"Mamá siempre decía que la vida es como una caja de bombones: nunca sabes lo que te va a tocar."},
    {"q":"Hakuna Matata.","ql":"en","fi":"The Lion King","fi_fr":"Le Roi Lion","fi_es":"El rey león","ch":"Timon & Pumbaa","ac":"Nathan Lane & Ernie Sabella (voices)","di":"Roger Allers & Rob Minkoff","yr":1994,"ty":None,"ti":"~00h38m — Act 2","co":"Timon and Pumbaa introduce young Simba to their carefree philosophy","q_en":None,"q_fr":"Hakuna Matata.","q_es":"Hakuna Matata."},
    {"q":"The greatest trick the devil ever pulled was convincing the world he didn't exist.","ql":"en","fi":"The Usual Suspects","fi_fr":"Usual Suspects","fi_es":"Sospechosos habituales","ch":"Verbal Kint","ac":"Kevin Spacey","di":"Bryan Singer","yr":1995,"ty":None,"ti":"~01h42m — Final scene","co":"Verbal's closing remark before the shocking twist reveals his true identity","q_en":None,"q_fr":"Le plus beau coup du diable, c'est de vous avoir convaincu qu'il n'existe pas.","q_es":"El mayor truco del diablo fue convencer al mundo de que no existía."},
    {"q":"What's in the box?","ql":"en","fi":"Se7en","fi_fr":"Seven","fi_es":"Se7en (Siete)","ch":"Detective Mills","ac":"Brad Pitt","di":"David Fincher","yr":1995,"ty":None,"ti":"~01h55m — Climax","co":"Mills screams desperately as John Doe reveals the contents of the mysterious box","q_en":None,"q_fr":"Qu'est-ce qu'il y a dans la boîte ?","q_es":"¿Qué hay en la caja?"},
    {"q":"To infinity and beyond!","ql":"en","fi":"Toy Story","fi_fr":"Toy Story","fi_es":"Toy Story","ch":"Buzz Lightyear","ac":"Tim Allen (voice)","di":"John Lasseter","yr":1995,"ty":None,"ti":"~00h22m — Act 1","co":"Buzz announces his famous catchphrase while demonstrating his spaceman abilities","q_en":None,"q_fr":"Vers l'infini et au-delà !","q_es":"¡Hasta el infinito y más allá!"},
    {"q":"Show me the money!","ql":"en","fi":"Jerry Maguire","fi_fr":"Jerry Maguire","fi_es":"Jerry Maguire","ch":"Rod Tidwell","ac":"Cuba Gooding Jr.","di":"Cameron Crowe","yr":1996,"ty":None,"ti":"~00h19m — Act 1","co":"Rod makes his agent Jerry Maguire shout his demands over the phone","q_en":None,"q_fr":"Montre-moi le fric !","q_es":"¡Enséñame el dinero!"},
    {"q":"I'm the king of the world!","ql":"en","fi":"Titanic","fi_fr":"Titanic","fi_es":"Titanic","ch":"Jack Dawson","ac":"Leonardo DiCaprio","di":"James Cameron","yr":1997,"ty":None,"ti":"~00h56m — Act 2","co":"Jack stands triumphantly at the bow of the Titanic, embracing the open sea with Rose","q_en":None,"q_fr":"Je suis le roi du monde !","q_es":"¡Soy el rey del mundo!"},
    {"q":"I see dead people.","ql":"en","fi":"The Sixth Sense","fi_fr":"Sixième Sens","fi_es":"El sexto sentido","ch":"Cole Sear","ac":"Haley Joel Osment","di":"M. Night Shyamalan","yr":1999,"ty":None,"ti":"~00h49m — Act 2","co":"Cole finally whispers his terrifying secret to child psychologist Malcolm Crowe","q_en":None,"q_fr":"Je vois des morts.","q_es":"Veo muertos."},
    {"q":"The first rule of Fight Club is: you do not talk about Fight Club.","ql":"en","fi":"Fight Club","fi_fr":"Fight Club","fi_es":"El club de la lucha","ch":"Tyler Durden","ac":"Brad Pitt","di":"David Fincher","yr":1999,"ty":None,"ti":"~00h54m — Act 2","co":"Tyler lays down the sacred rules at the first real Fight Club meeting in a basement","q_en":None,"q_fr":"La première règle du Fight Club : il est interdit de parler du Fight Club.","q_es":"La primera regla del Club de la Lucha: no hablar del Club de la Lucha."},
    # ── FILMS EN LANGUE FRANÇAISE ─────────────────────────────────────────
    {"q":"Jusqu'ici tout va bien.","ql":"fr","fi":"La Haine","fi_en":"La Haine (Hate)","fi_es":"El odio","ch":"Saïd","ac":"Saïd Taghmaoui","di":"Mathieu Kassovitz","yr":1995,"ty":None,"ti":"~00h02m — Opening","co":"A man falls from a building repeating this to himself — a metaphor for society ignoring its collapse","q_en":"So far, so good.","q_fr":None,"q_es":"Hasta aquí todo va bien."},
    {"q":"Les hommes, ça s'encourage.","ql":"fr","fi":"La Haine","fi_en":"La Haine (Hate)","fi_es":"El odio","ch":"Vinz","ac":"Vincent Cassel","di":"Mathieu Kassovitz","yr":1995,"ty":None,"ti":"~00h58m — Act 2","co":"Vinz lectures Saïd on masculinity in the banlieue, showing the toxic culture at the heart of the film","q_en":"Men need encouragement.","q_fr":None,"q_es":"Los hombres se animan unos a otros."},
    {"q":"Seigneur ! Damoiseaux chevaliers, nous ne sommes pas des bêtes !","ql":"fr","fi":"Les Visiteurs","fi_en":"The Visitors","fi_es":"Los visitantes","ch":"Godefroy de Montmirail","ac":"Jean Reno","di":"Jean-Marie Poiré","yr":1993,"ty":None,"ti":"~00h35m — Act 2","co":"Godefroy discovers with horror the modern world after time-travelling to the 20th century","q_en":"Lord! Young knights, we are not animals!","q_fr":None,"q_es":"¡Señor! ¡Jóvenes caballeros, no somos bestias!"},
    {"q":"Nikita. C'est le nom d'un lapin.","ql":"fr","fi":"Nikita","fi_en":"La Femme Nikita","fi_es":"Nikita","ch":"Bob","ac":"Tchéky Karyo","di":"Luc Besson","yr":1990,"ty":None,"ti":"~00h52m — Act 2","co":"Bob gives Nikita her new identity name for her missions, taken from a rabbit he once had","q_en":"Nikita. It's the name of a rabbit.","q_fr":None,"q_es":"Nikita. Es el nombre de un conejo."},
    # ── FILMS EN LANGUE ITALIENNE ─────────────────────────────────────────
    {"q":"Buongiorno, Principessa!","ql":"it","fi":"La vita è bella","fi_en":"Life is Beautiful","fi_fr":"La vie est belle","fi_es":"La vida es bella","ch":"Guido Orefice","ac":"Roberto Benigni","di":"Roberto Benigni","yr":1997,"ty":None,"ti":"~00h18m — Act 1","co":"Guido's irresistible greeting to Dora as she falls from a barn loft into his arms","q_en":"Good morning, Princess!","q_fr":"Bonjour, Princesse !","q_es":"¡Buenos días, Princesa!"},
    {"q":"Silenzio! Silenzio! Silenzio!","ql":"it","fi":"Cinema Paradiso","fi_en":"Cinema Paradiso","fi_fr":"Cinema Paradiso","fi_es":"Cinema Paradiso","ch":"Alfredo","ac":"Philippe Noiret","di":"Giuseppe Tornatore","yr":1988,"ty":None,"ti":"~00h20m — Act 1","co":"The projectionist Alfredo desperately tries to silence the rowdy audience before projecting the film","q_en":"Silence! Silence! Silence!","q_fr":"Silence ! Silence ! Silence !","q_es":"¡Silencio! ¡Silencio! ¡Silencio!"},
    # ── FILMS EN LANGUE ESPAGNOLE ─────────────────────────────────────────
    {"q":"¡Hay que ver lo bien que está la vida cuando uno tiene dinero!","ql":"es","fi":"Mujeres al borde de un ataque de nervios","fi_en":"Women on the Verge of a Nervous Breakdown","fi_fr":"Femmes au bord de la crise de nerfs","ch":"Pepa","ac":"Carmen Maura","di":"Pedro Almodóvar","yr":1988,"ty":None,"ti":"~00h30m — Act 1","co":"Pepa ironically comments on how much better life looks when you have money, despite her crisis","q_en":"How good life looks when you have money!","q_fr":"Comme la vie est belle quand on a de l'argent !","q_es":None},
]

seen = set()
deduped = []
for q in quotes:
    if q["q"] not in seen:
        seen.add(q["q"])
        deduped.append(q)
quotes = deduped

assert all(1980 <= q["yr"] <= 1999 for q in quotes), "ERROR: found a quote outside 1980-1999!"

with open("assets/cinema/quotes_80s90s.json", "w", encoding="utf-8") as f:
    json.dump([{k: v for k, v in q.items() if k != "td"} for q in quotes], f, ensure_ascii=False, separators=(',', ':'))

print(f"{len(quotes)} répliques 80s-90s générées (toutes 1980-1999).")
