import json

# RÈGLE : q_en=None si ql=="en", q_fr=None si ql=="fr", q_es=None si ql=="es"
# fi_fr=None si titre identique à fi OU si ql=="fr"
# fi_es=None si titre identique à fi OU si ql=="es"
# fi_en=None si ql=="en" (seulement pour films non-anglais)
# Toutes les années sont STRICTEMENT inférieures à 1980

quotes = [
    # ── FILMS EN LANGUE ANGLAISE ───────────────────────────────────────────
    {"q":"It's alive! It's alive!","ql":"en","fi":"Frankenstein","fi_fr":"Frankenstein","fi_es":"Frankenstein","ch":"Dr. Henry Frankenstein","ac":"Colin Clive","di":"James Whale","yr":1931,"ty":None,"ti":"~00h45m — Act 2","co":"Dr. Frankenstein witnesses his creature come to life during a thunderstorm","q_en":None,"q_fr":"Il est vivant ! Il est vivant !","q_es":"¡Está vivo! ¡Está vivo!"},
    {"q":"I vant to be alone.","ql":"en","fi":"Grand Hotel","fi_fr":"Grand Hôtel","fi_es":"Gran Hotel","ch":"Grusinskaya","ac":"Greta Garbo","di":"Edmund Goulding","yr":1932,"ty":None,"ti":"~00h25m — Act 1","co":"The famous ballerina dismisses her admirers, becoming one of cinema's most quoted lines","q_en":None,"q_fr":"Je veux être seule.","q_es":"Quiero estar sola."},
    {"q":"Magic Mirror on the wall, who is the fairest one of all?","ql":"en","fi":"Snow White and the Seven Dwarfs","fi_fr":"Blanche-Neige et les Sept Nains","fi_es":"Blancanieves y los siete enanos","ch":"Evil Queen","ac":"Lucille La Verne (voice)","di":"David Hand","yr":1937,"ty":None,"ti":"~00h05m — Opening","co":"The vain Queen consults her enchanted mirror about her beauty","q_en":None,"q_fr":"Miroir, miroir, dis-moi qui est la plus belle ?","q_es":"Espejito, espejito, ¿quién es la más bella del reino?"},
    {"q":"Frankly, my dear, I don't give a damn.","ql":"en","fi":"Gone with the Wind","fi_fr":"Autant en emporte le vent","fi_es":"Lo que el viento se llevó","ch":"Rhett Butler","ac":"Clark Gable","di":"Victor Fleming","yr":1939,"ty":None,"ti":"~03h35m — Final scene","co":"Rhett's last words to Scarlett as he walks out after years of war and heartbreak","q_en":None,"q_fr":"Franchement, ma chère, c'est le cadet de mes soucis.","q_es":"Francamente, querida, me importa un bledo."},
    {"q":"Toto, I've a feeling we're not in Kansas anymore.","ql":"en","fi":"The Wizard of Oz","fi_fr":"Le Magicien d'Oz","fi_es":"El mago de Oz","ch":"Dorothy Gale","ac":"Judy Garland","di":"Victor Fleming","yr":1939,"ty":None,"ti":"~00h42m — Act 1","co":"Dorothy looks around Munchkinland and realizes she has been transported to a strange land","q_en":None,"q_fr":"Toto, j'ai l'impression qu'on n'est plus au Kansas.","q_es":"Toto, creo que ya no estamos en Kansas."},
    {"q":"There's no place like home.","ql":"en","fi":"The Wizard of Oz","fi_fr":"Le Magicien d'Oz","fi_es":"El mago de Oz","ch":"Dorothy Gale","ac":"Judy Garland","di":"Victor Fleming","yr":1939,"ty":None,"ti":"~01h38m — Final act","co":"Dorothy clicks her ruby slippers three times to return to Kansas","q_en":None,"q_fr":"On n'est nulle part aussi bien que chez soi.","q_es":"No hay lugar como el hogar."},
    {"q":"I'll get you, my pretty, and your little dog too!","ql":"en","fi":"The Wizard of Oz","fi_fr":"Le Magicien d'Oz","fi_es":"El mago de Oz","ch":"Wicked Witch of the West","ac":"Margaret Hamilton","di":"Victor Fleming","yr":1939,"ty":None,"ti":"~00h50m — Act 2","co":"The Witch threatens Dorothy as she tries to steal the ruby slippers","q_en":None,"q_fr":"Je t'aurai, ma belle, et ton petit chien aussi !","q_es":"¡Te atraparé, preciosa, y a tu perrito también!"},
    {"q":"As God is my witness, I'll never be hungry again!","ql":"en","fi":"Gone with the Wind","fi_fr":"Autant en emporte le vent","fi_es":"Lo que el viento se llevó","ch":"Scarlett O'Hara","ac":"Vivien Leigh","di":"Victor Fleming","yr":1939,"ty":None,"ti":"~02h15m — Act 3","co":"Scarlett vows to survive and rebuild Tara after the devastation of the Civil War","q_en":None,"q_fr":"Dieu m'est témoin, je ne souffrirai plus jamais la faim !","q_es":"¡Dios me es testigo, nunca volveré a pasar hambre!"},
    {"q":"After all, tomorrow is another day.","ql":"en","fi":"Gone with the Wind","fi_fr":"Autant en emporte le vent","fi_es":"Lo que el viento se llevó","ch":"Scarlett O'Hara","ac":"Vivien Leigh","di":"Victor Fleming","yr":1939,"ty":None,"ti":"~03h58m — Final scene","co":"Scarlett refuses to accept defeat and resolves to win Rhett back","q_en":None,"q_fr":"Après tout, demain est un autre jour.","q_es":"Después de todo, mañana será otro día."},
    {"q":"Rosebud.","ql":"en","fi":"Citizen Kane","fi_fr":"Citizen Kane","fi_es":"Ciudadano Kane","ch":"Charles Foster Kane","ac":"Orson Welles","di":"Orson Welles","yr":1941,"ty":None,"ti":"~00h02m — Opening","co":"The dying tycoon's last word, the mystery that drives the entire film","q_en":None,"q_fr":"Rosebud.","q_es":"Rosebud."},
    {"q":"The stuff that dreams are made of.","ql":"en","fi":"The Maltese Falcon","fi_fr":"Le Faucon maltais","fi_es":"El halcón maltés","ch":"Sam Spade","ac":"Humphrey Bogart","di":"John Huston","yr":1941,"ty":None,"ti":"~01h37m — Final scene","co":"Spade describes the Maltese Falcon statuette to a police detective","q_en":None,"q_fr":"C'est l'étoffe dont les rêves sont faits.","q_es":"Está hecho de la materia de los sueños."},
    {"q":"Here's looking at you, kid.","ql":"en","fi":"Casablanca","fi_fr":"Casablanca","fi_es":"Casablanca","ch":"Rick Blaine","ac":"Humphrey Bogart","di":"Michael Curtiz","yr":1942,"ty":None,"ti":"~01h42m — Climax","co":"Rick bids farewell to Ilsa at the foggy Casablanca airport","q_en":None,"q_fr":"Je te regarde, gamine.","q_es":"Aquí te miro, chiquilla."},
    {"q":"Round up the usual suspects.","ql":"en","fi":"Casablanca","fi_fr":"Casablanca","fi_es":"Casablanca","ch":"Captain Renault","ac":"Claude Rains","di":"Michael Curtiz","yr":1942,"ty":None,"ti":"~01h44m — Final scene","co":"Renault covers for Rick after the shooting of Major Strasser","q_en":None,"q_fr":"Arrêtez les suspects habituels.","q_es":"Arresten a los sospechosos de siempre."},
    {"q":"We'll always have Paris.","ql":"en","fi":"Casablanca","fi_fr":"Casablanca","fi_es":"Casablanca","ch":"Rick Blaine","ac":"Humphrey Bogart","di":"Michael Curtiz","yr":1942,"ty":None,"ti":"~01h41m — Climax","co":"Rick tells Ilsa they will always have the memory of their time together in Paris","q_en":None,"q_fr":"Nous aurons toujours Paris.","q_es":"Siempre nos quedará París."},
    {"q":"Of all the gin joints in all the towns in all the world, she walks into mine.","ql":"en","fi":"Casablanca","fi_fr":"Casablanca","fi_es":"Casablanca","ch":"Rick Blaine","ac":"Humphrey Bogart","di":"Michael Curtiz","yr":1942,"ty":None,"ti":"~00h55m — Act 2","co":"Rick mutters bitterly upon seeing Ilsa walk into his café unexpectedly","q_en":None,"q_fr":"De tous les bars de toutes les villes du monde, elle entre dans le mien.","q_es":"De todos los garitos de todas las ciudades del mundo, entra en el mío."},
    {"q":"You know how to whistle, don't you? You just put your lips together and blow.","ql":"en","fi":"To Have and Have Not","fi_fr":"Le Port de l'angoisse","fi_es":"Tener y no tener","ch":"Marie Browning","ac":"Lauren Bacall","di":"Howard Hawks","yr":1944,"ty":None,"ti":"~00h22m — Act 1","co":"The young Marie flirtatiously challenges Steve as she leaves his hotel room","q_en":None,"q_fr":"Tu sais siffler, non ? Tu poses juste les lèvres et tu souffles.","q_es":"Sabes silbar, ¿verdad? Solo juntas los labios y soplas."},
    {"q":"Every time a bell rings, an angel gets his wings.","ql":"en","fi":"It's a Wonderful Life","fi_fr":"La Vie est belle","fi_es":"¡Qué bello es vivir!","ch":"Zuzu Bailey","ac":"Karolyn Grimes","di":"Frank Capra","yr":1946,"ty":None,"ti":"~02h05m — Final scene","co":"Young Zuzu explains the meaning of a fallen bell ornament at Christmas","q_en":None,"q_fr":"Chaque fois qu'une cloche sonne, un ange reçoit ses ailes.","q_es":"Cada vez que suena una campana, un ángel recibe sus alas."},
    {"q":"Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!","ql":"en","fi":"The Treasure of the Sierra Madre","fi_fr":"Le Trésor de la Sierra Madre","fi_es":"El tesoro de Sierra Madre","ch":"Gold Hat","ac":"Alfonso Bedoya","di":"John Huston","yr":1948,"ty":None,"ti":"~00h55m — Act 2","co":"The Mexican bandit dismisses demands to show proof of authority to the prospectors","q_en":None,"q_fr":"Des insignes ? On n'a pas d'insignes ! On n'en a pas besoin !","q_es":"¿Insignias? ¡No tenemos insignias! ¡No necesitamos insignias!"},
    {"q":"All right, Mr. DeMille, I'm ready for my close-up.","ql":"en","fi":"Sunset Boulevard","fi_fr":"Boulevard du crépuscule","fi_es":"El crepúsculo de los dioses","ch":"Norma Desmond","ac":"Gloria Swanson","di":"Billy Wilder","yr":1950,"ty":None,"ti":"~01h47m — Final scene","co":"Norma descends the staircase in a delusional state, believing cameras are filming her","q_en":None,"q_fr":"Je suis prête pour mon gros plan, monsieur DeMille.","q_es":"Estoy lista para mi primer plano, señor DeMille."},
    {"q":"I am big. It's the pictures that got small.","ql":"en","fi":"Sunset Boulevard","fi_fr":"Boulevard du crépuscule","fi_es":"El crepúsculo de los dioses","ch":"Norma Desmond","ac":"Gloria Swanson","di":"Billy Wilder","yr":1950,"ty":None,"ti":"~00h25m — Act 1","co":"Norma defends her faded stardom to screenwriter Joe Gillis","q_en":None,"q_fr":"C'est moi qui suis grande. Ce sont les films qui ont rétréci.","q_es":"Soy grande. Son las películas las que se han vuelto pequeñas."},
    {"q":"Fasten your seatbelts, it's going to be a bumpy night.","ql":"en","fi":"All About Eve","fi_fr":"Ève","fi_es":"Eva al desnudo","ch":"Margo Channing","ac":"Bette Davis","di":"Joseph L. Mankiewicz","yr":1950,"ty":None,"ti":"~00h47m — Act 2","co":"Margo warns her party guests as tensions rise over the scheming Eve Harrington","q_en":None,"q_fr":"Attachez vos ceintures, la nuit va être agitée.","q_es":"Abróchense los cinturones, va a ser una noche movida."},
    {"q":"STELLA!","ql":"en","fi":"A Streetcar Named Desire","fi_fr":"Un tramway nommé Désir","fi_es":"Un tranvía llamado Deseo","ch":"Stanley Kowalski","ac":"Marlon Brando","di":"Elia Kazan","yr":1951,"ty":None,"ti":"~00h48m — Act 2","co":"Stanley screams for his wife Stella after a poker game argument turns violent","q_en":None,"q_fr":"STELLA !","q_es":"¡STELLA!"},
    {"q":"I could've been a contender.","ql":"en","fi":"On the Waterfront","fi_fr":"Sur les quais","fi_es":"La ley del silencio","ch":"Terry Malloy","ac":"Marlon Brando","di":"Elia Kazan","yr":1954,"ty":None,"ti":"~01h25m — Act 3","co":"Terry confronts his brother Charlie about how he threw his boxing career","q_en":None,"q_fr":"J'aurais pu avoir de la classe, j'aurais pu être un champion. J'aurais pu être quelqu'un au lieu d'être un tocard.","q_es":"Podría haber sido un contendiente."},
    {"q":"Well, nobody's perfect.","ql":"en","fi":"Some Like It Hot","fi_fr":"Certains l'aiment chaud","fi_es":"Con faldas y a lo loco","ch":"Osgood Fielding III","ac":"Joe E. Brown","di":"Billy Wilder","yr":1959,"ty":None,"ti":"~01h55m — Final scene","co":"Osgood's cheerful reply after Jerry reveals he is actually a man","q_en":None,"q_fr":"Eh bien, personne n'est parfait.","q_es":"Bueno, nadie es perfecto."},
    {"q":"I am Spartacus!","ql":"en","fi":"Spartacus","fi_fr":"Spartacus","fi_es":"Espartaco","ch":"Spartacus","ac":"Kirk Douglas","di":"Stanley Kubrick","yr":1960,"ty":None,"ti":"~02h28m — Climax","co":"Slaves each claim to be Spartacus to protect their leader from crucifixion","q_en":None,"q_fr":"Je suis Spartacus !","q_es":"¡Yo soy Espartaco!"},
    {"q":"A boy's best friend is his mother.","ql":"en","fi":"Psycho","fi_fr":"Psychose","fi_es":"Psicosis","ch":"Norman Bates","ac":"Anthony Perkins","di":"Alfred Hitchcock","yr":1960,"ty":None,"ti":"~00h35m — Act 1","co":"Norman justifies his obsessive devotion to his domineering mother","q_en":None,"q_fr":"Le meilleur ami d'un garçon, c'est sa mère.","q_es":"El mejor amigo de un chico es su madre."},
    {"q":"Bond. James Bond.","ql":"en","fi":"Dr. No","fi_fr":"James Bond contre Dr. No","fi_es":"Agente 007 contra el Dr. No","ch":"James Bond","ac":"Sean Connery","di":"Terence Young","yr":1962,"ty":None,"ti":"~00h18m — Act 1","co":"Bond introduces himself at a casino table for the very first time on screen","q_en":None,"q_fr":"Bond. James Bond.","q_es":"Bond. James Bond."},
    {"q":"Nothing is written.","ql":"en","fi":"Lawrence of Arabia","fi_fr":"Lawrence d'Arabie","fi_es":"Lawrence de Arabia","ch":"T.E. Lawrence","ac":"Peter O'Toole","di":"David Lean","yr":1962,"ty":None,"ti":"~00h42m — Act 1","co":"Lawrence insists fate is not predetermined before leading men across the Nefud desert","q_en":None,"q_fr":"Il n'est rien d'écrit.","q_es":"Nada está escrito."},
    {"q":"I'm sorry, Dave. I'm afraid I can't do that.","ql":"en","fi":"2001: A Space Odyssey","fi_fr":"2001 : L'Odyssée de l'espace","fi_es":"2001: Una odisea del espacio","ch":"HAL 9000","ac":"Douglas Rain (voice)","di":"Stanley Kubrick","yr":1968,"ty":None,"ti":"~01h29m — Act 2","co":"The onboard AI refuses to open the pod bay doors for astronaut Dave Bowman","q_en":None,"q_fr":"Je suis désolé Dave, je crains de ne pas pouvoir faire ça.","q_es":"Lo siento, Dave. Me temo que no puedo hacer eso."},
    {"q":"Get your stinking paws off me, you damned dirty ape!","ql":"en","fi":"Planet of the Apes","fi_fr":"La Planète des singes","fi_es":"El planeta de los simios","ch":"George Taylor","ac":"Charlton Heston","di":"Franklin J. Schaffner","yr":1968,"ty":None,"ti":"~00h38m — Act 1","co":"Taylor speaks for the first time on the Planet of the Apes, shocking his captors","q_en":None,"q_fr":"Ôtez vos sales pattes de ma personne, espèce de sale singe !","q_es":"¡Aparta tus sucias garras de mí, maldito simio asqueroso!"},
    {"q":"Mrs. Robinson, you're trying to seduce me. Aren't you?","ql":"en","fi":"The Graduate","fi_fr":"Le Lauréat","fi_es":"El graduado","ch":"Benjamin Braddock","ac":"Dustin Hoffman","di":"Mike Nichols","yr":1967,"ty":None,"ti":"~00h28m — Act 1","co":"A confused young Benjamin realizes the older Mrs. Robinson's intentions","q_en":None,"q_fr":"Madame Robinson, vous essayez de me séduire. N'est-ce pas ?","q_es":"Señora Robinson, está intentando seducirme. ¿Verdad?"},
    {"q":"What we've got here is failure to communicate.","ql":"en","fi":"Cool Hand Luke","fi_fr":"Luke la main froide","fi_es":"El zurdo","ch":"The Captain","ac":"Strother Martin","di":"Stuart Rosenberg","yr":1967,"ty":None,"ti":"~00h17m — Act 1","co":"The prison warden beats Luke after an escape attempt and lectures the other prisoners","q_en":None,"q_fr":"Ce qu'on a là, c'est un problème de communication.","q_es":"Lo que tenemos aquí es un fracaso de comunicación."},
    {"q":"They call me Mister Tibbs!","ql":"en","fi":"In the Heat of the Night","fi_fr":"Dans la chaleur de la nuit","fi_es":"En el calor de la noche","ch":"Virgil Tibbs","ac":"Sidney Poitier","di":"Norman Jewison","yr":1967,"ty":None,"ti":"~00h20m — Act 1","co":"Virgil corrects a racist white police chief who refuses to use his proper title","q_en":None,"q_fr":"On m'appelle Monsieur Tibbs !","q_es":"¡Me llaman el señor Tibbs!"},
    {"q":"We rob banks.","ql":"en","fi":"Bonnie and Clyde","fi_fr":"Bonnie et Clyde","fi_es":"Bonnie and Clyde","ch":"Clyde Barrow","ac":"Warren Beatty","di":"Arthur Penn","yr":1967,"ty":None,"ti":"~00h30m — Act 1","co":"Clyde announces who they are to their first robbery victim with cool nonchalance","q_en":None,"q_fr":"On braque des banques.","q_es":"Robamos bancos."},
    {"q":"I'm walking here! I'm walking here!","ql":"en","fi":"Midnight Cowboy","fi_fr":"Macadam Cowboy","fi_es":"Cowboy de medianoche","ch":"Ratso Rizzo","ac":"Dustin Hoffman","di":"John Schlesinger","yr":1969,"ty":None,"ti":"~00h54m — Act 2","co":"Ratso shouts at a taxi that almost hits him and Jon Voight crossing a New York street","q_en":None,"q_fr":"Je marche là ! Je marche là !","q_es":"¡Estoy caminando aquí! ¡Estoy caminando aquí!"},
    {"q":"Who are those guys?","ql":"en","fi":"Butch Cassidy and the Sundance Kid","fi_fr":"Butch Cassidy et le Kid","fi_es":"Dos hombres y un destino","ch":"Butch Cassidy","ac":"Paul Newman","di":"George Roy Hill","yr":1969,"ty":None,"ti":"~00h38m — Act 1","co":"Butch repeatedly asks who the relentless Pinkerton posse chasing them is","q_en":None,"q_fr":"Mais qui sont ces types ?","q_es":"¿Quiénes son esos tíos?"},
    {"q":"Love means never having to say you're sorry.","ql":"en","fi":"Love Story","fi_fr":"Love Story","fi_es":"Love Story","ch":"Oliver Barrett IV","ac":"Ryan O'Neal","di":"Arthur Hiller","yr":1970,"ty":None,"ti":"~01h38m — Final scene","co":"Oliver repeats Jenny's famous words to his grieving father after her death","q_en":None,"q_fr":"Aimer, c'est ne jamais avoir à dire pardon.","q_es":"Amar significa no tener que pedir perdón."},
    {"q":"You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?","ql":"en","fi":"Dirty Harry","fi_fr":"L'Inspecteur Harry","fi_es":"Harry el sucio","ch":"Harry Callahan","ac":"Clint Eastwood","di":"Don Siegel","yr":1971,"ty":None,"ti":"~00h08m — Opening act","co":"Harry taunts a wounded bank robber contemplating whether to grab his gun","q_en":None,"q_fr":"Tu dois te poser qu'une question : 'Est-ce que je tente ma chance ?' Vas-y, tu la tentes ou pas ?","q_es":"Tienes que preguntarte una cosa: ¿me siento afortunado? ¿Eh, punk?"},
    {"q":"I'm gonna make him an offer he can't refuse.","ql":"en","fi":"The Godfather","fi_fr":"Le Parrain","fi_es":"El padrino","ch":"Vito Corleone","ac":"Marlon Brando","di":"Francis Ford Coppola","yr":1972,"ty":None,"ti":"~00h18m — Act 1","co":"The Don explains how he will help Johnny Fontane get a Hollywood role","q_en":None,"q_fr":"Je vais lui faire une offre qu'il ne pourra pas refuser.","q_es":"Le haré una oferta que no podrá rechazar."},
    {"q":"Leave the gun. Take the cannoli.","ql":"en","fi":"The Godfather","fi_fr":"Le Parrain","fi_es":"El padrino","ch":"Peter Clemenza","ac":"Richard Castellano","di":"Francis Ford Coppola","yr":1972,"ty":None,"ti":"~01h08m — Act 2","co":"After a mob execution, Clemenza prioritizes the cannoli his wife requested","q_en":None,"q_fr":"Laisse le flingue. Prends les cannolis.","q_es":"Deja la pistola. Coge los cannoli."},
    {"q":"Soylent Green is people!","ql":"en","fi":"Soylent Green","fi_fr":"Soleil vert","fi_es":"Cuando el destino nos alcance","ch":"Detective Thorn","ac":"Charlton Heston","di":"Richard Fleischer","yr":1973,"ty":None,"ti":"~01h33m — Climax","co":"Thorn screams the horrifying truth about the mysterious food source to the crowd","q_en":None,"q_fr":"Le Soleil vert, c'est de la chair humaine !","q_es":"¡El Soylent Verde está hecho de personas!"},
    {"q":"Forget it, Jake. It's Chinatown.","ql":"en","fi":"Chinatown","fi_fr":"Chinatown","fi_es":"Chinatown","ch":"Lawrence Walsh","ac":"Joe Mantell","di":"Roman Polanski","yr":1974,"ty":None,"ti":"~02h10m — Final scene","co":"Walsh consoles Jake after the tragic shooting of Evelyn, accepting the corrupt world","q_en":None,"q_fr":"Laisse tomber, Jake. C'est Chinatown.","q_es":"Olvídalo, Jake. Es Chinatown."},
    {"q":"Keep your friends close but your enemies closer.","ql":"en","fi":"The Godfather Part II","fi_fr":"Le Parrain, 2e partie","fi_es":"El padrino. Parte II","ch":"Michael Corleone","ac":"Al Pacino","di":"Francis Ford Coppola","yr":1974,"ty":"sequel","ti":"~01h40m — Act 3","co":"Michael advises his adopted brother Tom Hagen on how to handle Senator Geary","q_en":None,"q_fr":"Garde tes amis près de toi, mais tes ennemis encore plus près.","q_es":"Mantén a tus amigos cerca, pero a tus enemigos aún más cerca."},
    {"q":"You're gonna need a bigger boat.","ql":"en","fi":"Jaws","fi_fr":"Les Dents de la mer","fi_es":"Tiburón","ch":"Martin Brody","ac":"Roy Scheider","di":"Steven Spielberg","yr":1975,"ty":None,"ti":"~01h22m — Act 2","co":"Brody sees the great white shark for the first time and is visibly terrified","q_en":None,"q_fr":"Vous allez avoir besoin d'un plus gros bateau.","q_es":"Vas a necesitar un barco más grande."},
    {"q":"It's just a flesh wound.","ql":"en","fi":"Monty Python and the Holy Grail","fi_fr":"Monty Python : Sacré Graal !","fi_es":"Monty Python y el Santo Grial","ch":"Black Knight","ac":"John Cleese","di":"Terry Gilliam & Terry Jones","yr":1975,"ty":None,"ti":"~00h21m — Act 1","co":"The Black Knight refuses to yield despite losing both arms in combat","q_en":None,"q_fr":"Ce n'est qu'une égratignure.","q_es":"No es más que un rasguño."},
    {"q":"I'm as mad as hell, and I'm not going to take this anymore!","ql":"en","fi":"Network","fi_fr":"Network, main basse sur la TV","fi_es":"Network, un mundo implacable","ch":"Howard Beale","ac":"Peter Finch","di":"Sidney Lumet","yr":1976,"ty":None,"ti":"~00h55m — Act 2","co":"Unhinged anchorman Howard Beale incites millions of viewers to shout out their windows","q_en":None,"q_fr":"J'en ai ras-le-bol et je ne le supporterai plus !","q_es":"¡Estoy furioso y no lo voy a aguantar más!"},
    {"q":"Yo, Adrian!","ql":"en","fi":"Rocky","fi_fr":"Rocky","fi_es":"Rocky","ch":"Rocky Balboa","ac":"Sylvester Stallone","di":"John G. Avildsen","yr":1976,"ty":None,"ti":"~01h45m — Climax","co":"Rocky, battered after the full fight, calls out for his girlfriend in the ring","q_en":None,"q_fr":"Yo, Adrian !","q_es":"¡Yo, Adrian!"},
    {"q":"You talkin' to me?","ql":"en","fi":"Taxi Driver","fi_fr":"Taxi Driver","fi_es":"Taxi Driver","ch":"Travis Bickle","ac":"Robert De Niro","di":"Martin Scorsese","yr":1976,"ty":None,"ti":"~00h58m — Act 2","co":"Travis rehearses confrontation alone in his apartment mirror","q_en":None,"q_fr":"C'est à moi que tu parles ?","q_es":"¿Me estás hablando a mí?"},
    {"q":"May the Force be with you.","ql":"en","fi":"Star Wars","fi_fr":"La Guerre des étoiles","fi_es":"La guerra de las galaxias","ch":"Han Solo","ac":"Harrison Ford","di":"George Lucas","yr":1977,"ty":None,"ti":"~01h35m — Climax","co":"Han bids farewell to Luke before the Death Star assault, not believing in the Force","q_en":None,"q_fr":"Que la Force soit avec toi.","q_es":"Que la Fuerza te acompañe."},
    {"q":"Help me, Obi-Wan Kenobi. You're my only hope.","ql":"en","fi":"Star Wars","fi_fr":"La Guerre des étoiles","fi_es":"La guerra de las galaxias","ch":"Princess Leia","ac":"Carrie Fisher","di":"George Lucas","yr":1977,"ty":None,"ti":"~00h18m — Act 1","co":"Leia's holographic message hidden inside R2-D2 pleads for the Rebel Alliance","q_en":None,"q_fr":"Aidez-moi, Obi-Wan Kenobi. Vous êtes mon seul espoir.","q_es":"Ayúdame, Obi-Wan Kenobi. Eres mi única esperanza."},
    {"q":"Tell me about it, stud.","ql":"en","fi":"Grease","fi_fr":"Grease","fi_es":"Grease","ch":"Sandy Olsson","ac":"Olivia Newton-John","di":"Randal Kleiser","yr":1978,"ty":None,"ti":"~01h38m — Final scene","co":"Sandy's cool reply to Danny after she reinvents herself at the school carnival","q_en":None,"q_fr":"Raconte-moi ça, beau gosse.","q_es":"Cuéntame, machote."},
    {"q":"I love the smell of napalm in the morning.","ql":"en","fi":"Apocalypse Now","fi_fr":"Apocalypse Now","fi_es":"Apocalypse Now","ch":"Lieutenant Colonel Kilgore","ac":"Robert Duvall","di":"Francis Ford Coppola","yr":1979,"ty":None,"ti":"~00h47m — Act 1","co":"Kilgore revels in a napalm strike on a Vietnamese village during a beach assault","q_en":None,"q_fr":"J'adore l'odeur du napalm au matin.","q_es":"Me encanta el olor del napalm por la mañana."},
    {"q":"The horror... the horror...","ql":"en","fi":"Apocalypse Now","fi_fr":"Apocalypse Now","fi_es":"Apocalypse Now","ch":"Colonel Kurtz","ac":"Marlon Brando","di":"Francis Ford Coppola","yr":1979,"ty":None,"ti":"~02h30m — Climax","co":"Kurtz's dying words after Willard's assassination, ambiguous and haunting","q_en":None,"q_fr":"L'horreur... l'horreur...","q_es":"El horror... el horror..."},
    # ── FILMS EN LANGUE FRANÇAISE ─────────────────────────────────────────
    {"q":"À bout de souffle.","ql":"fr","fi":"À bout de souffle","fi_en":"Breathless","fi_es":"Al final de la escapada","ch":"Michel Poiccard","ac":"Jean-Paul Belmondo","di":"Jean-Luc Godard","yr":1960,"ty":None,"ti":"~01h27m — Final scene","co":"Michel's last words after being shot, lying on the pavement, his final act of defiance","q_en":"Out of breath.","q_fr":None,"q_es":"Sin aliento."},
    {"q":"Je suis las. Je suis las de la fatigue des autres.","ql":"fr","fi":"Les Enfants du Paradis","fi_en":"Children of Paradise","fi_es":"Los niños del paraíso","ch":"Baptiste Deburau","ac":"Jean-Louis Barrault","di":"Marcel Carné","yr":1945,"ty":None,"ti":"~02h50m — Final act","co":"Baptiste expresses his exhaustion after years of unrequited love for Garance","q_en":"I am weary. I am weary of others' tiredness.","q_fr":None,"q_es":"Estoy cansado. Estoy cansado del cansancio de los demás."},
    # ── FILMS EN LANGUE ITALIENNE ─────────────────────────────────────────
    {"q":"Il buono, il brutto, il cattivo.","ql":"it","fi":"Il buono, il brutto, il cattivo","fi_en":"The Good, the Bad and the Ugly","fi_fr":"Le Bon, la Brute et le Truand","fi_es":"El bueno, el feo y el malo","ch":"Title","ac":"N/A","di":"Sergio Leone","yr":1966,"ty":None,"ti":"~00h01m — Title card","co":"The title itself became the most iconic phrase of the Spaghetti Western genre","q_en":"The Good, the Bad and the Ugly.","q_fr":"Le Bon, la Brute et le Truand.","q_es":"El bueno, el feo y el malo."},
    {"q":"La dolce vita.","ql":"it","fi":"La dolce vita","fi_en":"La dolce vita","fi_fr":"La dolce vita","fi_es":"La dolce vita","ch":"Title / Marcello","ac":"Marcello Mastroianni","di":"Federico Fellini","yr":1960,"ty":None,"ti":"~00h01m — Opening","co":"The title phrase, meaning the sweet life, became a universal symbol of carefree hedonism","q_en":"The sweet life.","q_fr":"La dolce vita.","q_es":"La dolce vita."},
]

assert all(q["yr"] < 1980 for q in quotes), "ERROR: found a quote with year >= 1980!"

with open("assets/cinema/quotes_classic.json", "w", encoding="utf-8") as f:
    json.dump([{k: v for k, v in q.items() if k != "td"} for q in quotes], f, ensure_ascii=False, separators=(',', ':'))

print(f"{len(quotes)} répliques Classic Hollywood générées (toutes < 1980).")
