import json

# RÈGLE : q_en=None si ql=="en", q_fr=None si ql=="fr", q_es=None si ql=="es"
# Toutes les années sont >= 2000

quotes = [
    # ── FILMS EN LANGUE ANGLAISE ───────────────────────────────────────────
    {"q":"My name is Maximus Decimus Meridius, and I will have my vengeance.","ql":"en","fi":"Gladiator","ch":"Maximus","ac":"Russell Crowe","di":"Ridley Scott","yr":2000,"ty":None,"ti":"~01h06m — Act 2","co":"Maximus removes his helmet and confronts Commodus directly in the Colosseum","q_en":None,"q_fr":"Je m'appelle Maximus Decimus Meridius et j'aurai ma vengeance.","q_es":"Me llamo Máximo Décimo Meridio y tendré mi venganza."},
    {"q":"What we do in life echoes in eternity.","ql":"en","fi":"Gladiator","ch":"Maximus","ac":"Russell Crowe","di":"Ridley Scott","yr":2000,"ty":None,"ti":"~00h12m — Act 1","co":"Maximus rallies his troops before a fierce battle in the Germanic forests","q_en":None,"q_fr":"Ce que nous faisons dans la vie résonne dans l'éternité.","q_es":"Lo que hacemos en vida tiene su eco en la eternidad."},
    {"q":"You shall not pass!","ql":"en","fi":"The Lord of the Rings: The Fellowship of the Ring","ch":"Gandalf","ac":"Ian McKellen","di":"Peter Jackson","yr":2001,"ty":None,"ti":"~01h47m — Climax","co":"Gandalf confronts the Balrog on the bridge of Khazad-dûm to protect the Fellowship","q_en":None,"q_fr":"Tu ne passeras pas !","q_es":"¡No pasarás!"},
    {"q":"Even the smallest person can change the course of the future.","ql":"en","fi":"The Lord of the Rings: The Fellowship of the Ring","ch":"Galadriel","ac":"Cate Blanchett","di":"Peter Jackson","yr":2001,"ty":None,"ti":"~02h38m — Final act","co":"Galadriel speaks to Frodo in Lothlórien, acknowledging his unlikely heroism","q_en":None,"q_fr":"Même la plus petite personne peut changer le cours du futur.","q_es":"Hasta la persona más pequeña puede cambiar el curso del futuro."},
    {"q":"It does not do to dwell on dreams and forget to live.","ql":"en","fi":"Harry Potter and the Philosopher's Stone","ch":"Albus Dumbledore","ac":"Richard Harris","di":"Chris Columbus","yr":2001,"ty":None,"ti":"~01h52m — Final act","co":"Dumbledore gently advises Harry about staring too long into the Mirror of Erised","q_en":None,"q_fr":"On ne doit pas vivre dans les rêves et oublier de vivre.","q_es":"No conviene quedarse mirando un sueño olvidándose de vivir."},
    {"q":"With great power comes great responsibility.","ql":"en","fi":"Spider-Man","ch":"Uncle Ben","ac":"Cliff Robertson","di":"Sam Raimi","yr":2002,"ty":None,"ti":"~00h45m — Act 1","co":"Uncle Ben's final advice to Peter Parker before being fatally shot that night","q_en":None,"q_fr":"De grands pouvoirs impliquent de grandes responsabilités.","q_es":"Un gran poder conlleva una gran responsabilidad."},
    {"q":"My precious.","ql":"en","fi":"The Lord of the Rings: The Two Towers","ch":"Gollum","ac":"Andy Serkis","di":"Peter Jackson","yr":2002,"ty":"sequel","ti":"~00h15m — Act 1","co":"Gollum obsessively speaks to and about the One Ring he lost to Bilbo Baggins","q_en":None,"q_fr":"Mon précieux.","q_es":"Mi tesoro."},
    {"q":"Just keep swimming.","ql":"en","fi":"Finding Nemo","ch":"Dory","ac":"Ellen DeGeneres (voice)","di":"Andrew Stanton","yr":2003,"ty":None,"ti":"~00h45m — Act 2","co":"Dory sings her optimistic mantra to Marlin to keep going during their ocean journey","q_en":None,"q_fr":"Nage, nage, nage...","q_es":"Sigue nadando, sigue nadando."},
    {"q":"I am no man.","ql":"en","fi":"The Lord of the Rings: The Return of the King","ch":"Éowyn","ac":"Miranda Otto","di":"Peter Jackson","yr":2003,"ty":"sequel","ti":"~01h56m — Climax","co":"Éowyn removes her helmet to face the Witch-king, who declared no man could slay him","q_en":None,"q_fr":"Je ne suis pas un homme.","q_es":"No soy un hombre."},
    {"q":"I can't carry it for you, but I can carry you!","ql":"en","fi":"The Lord of the Rings: The Return of the King","ch":"Samwise Gamgee","ac":"Sean Astin","di":"Peter Jackson","yr":2003,"ty":"sequel","ti":"~02h48m — Climax","co":"Sam lifts Frodo on his back to carry him up Mount Doom when Frodo can no longer walk","q_en":None,"q_fr":"Je ne peux pas le porter à ta place, mais je peux te porter, toi !","q_es":"No puedo cargarlo por ti, ¡pero sí puedo cargarte a ti!"},
    {"q":"To me, you are perfect.","ql":"en","fi":"Love Actually","ch":"Mark","ac":"Andrew Lincoln","di":"Richard Curtis","yr":2003,"ty":None,"ti":"~01h20m — Act 2","co":"Mark silently declares his secret love for Juliet through handmade signs on her doorstep","q_en":None,"q_fr":"Pour moi, tu es parfaite.","q_es":"Para mí, eres perfecta."},
    {"q":"Happiness can be found even in the darkest of times, if one only remembers to turn on the light.","ql":"en","fi":"Harry Potter and the Prisoner of Azkaban","ch":"Albus Dumbledore","ac":"Michael Gambon","di":"Alfonso Cuarón","yr":2004,"ty":"sequel","ti":"~00h10m — Opening","co":"Dumbledore addresses Hogwarts students at the start-of-term feast","q_en":None,"q_fr":"Le bonheur peut être trouvé même dans les moments les plus sombres, si l'on se souvient d'allumer la lumière.","q_es":"La felicidad puede encontrarse incluso en los momentos más oscuros, si uno recuerda encender la luz."},
    {"q":"Why do we fall? So that we can learn to pick ourselves up.","ql":"en","fi":"Batman Begins","ch":"Alfred Pennyworth","ac":"Michael Caine","di":"Christopher Nolan","yr":2005,"ty":None,"ti":"~00h30m — Act 1","co":"Alfred recalls Thomas Wayne's words to young Bruce after he falls into the bat cave","q_en":None,"q_fr":"Pourquoi tombons-nous ? Pour apprendre à nous relever.","q_es":"¿Por qué caemos? Para aprender a levantarnos."},
    {"q":"I wish I knew how to quit you.","ql":"en","fi":"Brokeback Mountain","ch":"Jack Twist","ac":"Jake Gyllenhaal","di":"Ang Lee","yr":2005,"ty":None,"ti":"~01h28m — Act 3","co":"Jack expresses his anguish to Ennis about their impossible love after years apart","q_en":None,"q_fr":"Je voudrais savoir comment te quitter.","q_es":"Ojalá supiera cómo dejarte."},
    {"q":"Some men just want to watch the world burn.","ql":"en","fi":"The Dark Knight","ch":"Alfred Pennyworth","ac":"Michael Caine","di":"Christopher Nolan","yr":2008,"ty":"sequel","ti":"~00h48m — Act 2","co":"Alfred explains the Joker's motivation to Bruce: pure chaos with no rational goal","q_en":None,"q_fr":"Certains hommes veulent juste regarder le monde brûler.","q_es":"Algunos hombres solo quieren ver el mundo arder."},
    {"q":"Why so serious?","ql":"en","fi":"The Dark Knight","ch":"The Joker","ac":"Heath Ledger","di":"Christopher Nolan","yr":2008,"ty":"sequel","ti":"~00h38m — Act 1","co":"Joker taunts a mobster before revealing how he got his scars at a crime boss meeting","q_en":None,"q_fr":"Pourquoi si sérieux ?","q_es":"¿Por qué tan serio?"},
    {"q":"I am Iron Man.","ql":"en","fi":"Iron Man","ch":"Tony Stark","ac":"Robert Downey Jr.","di":"Jon Favreau","yr":2008,"ty":None,"ti":"~01h58m — Final scene","co":"Tony defies his advisors and publicly reveals his superhero identity to the press","q_en":None,"q_fr":"Je suis Iron Man.","q_es":"Yo soy Iron Man."},
    {"q":"An idea is like a virus. Resilient. Highly contagious.","ql":"en","fi":"Inception","ch":"Cobb","ac":"Leonardo DiCaprio","di":"Christopher Nolan","yr":2010,"ty":None,"ti":"~00h50m — Act 2","co":"Cobb explains to Ariadne why inception is so dangerous once an idea takes root","q_en":None,"q_fr":"Une idée est comme un virus. Résistante. Très contagieuse.","q_es":"Una idea es como un virus. Resistente. Muy contagiosa."},
    {"q":"You mustn't be afraid to dream a little bigger, darling.","ql":"en","fi":"Inception","ch":"Eames","ac":"Tom Hardy","di":"Christopher Nolan","yr":2010,"ty":None,"ti":"~01h52m — Act 3","co":"Eames upgrades his weapon from a pistol to a grenade launcher in the dream level","q_en":None,"q_fr":"Il ne faut pas avoir peur de voir les choses en grand, chéri.","q_es":"No debes tener miedo de soñar un poco más en grande, querido."},
    {"q":"After all this time? Always.","ql":"en","fi":"Harry Potter and the Deathly Hallows Part 2","ch":"Severus Snape","ac":"Alan Rickman","di":"David Yates","yr":2011,"ty":"sequel","ti":"~01h58m — Act 3","co":"Snape's single word reveals the depth of his lifelong love for Lily Potter to Dumbledore","q_en":None,"q_fr":"Après tout ce temps ? Toujours.","q_es":"¿Después de todo este tiempo? Siempre."},
    {"q":"We accept the love we think we deserve.","ql":"en","fi":"The Perks of Being a Wallflower","ch":"Bill Anderson","ac":"Paul Rudd","di":"Stephen Chbosky","yr":2012,"ty":None,"ti":"~01h18m — Act 3","co":"Bill answers Charlie's question about why people let themselves be treated badly","q_en":None,"q_fr":"On accepte l'amour qu'on pense mériter.","q_es":"Aceptamos el amor que creemos merecer."},
    {"q":"We are Groot.","ql":"en","fi":"Guardians of the Galaxy","ch":"Groot","ac":"Vin Diesel (voice)","di":"James Gunn","yr":2014,"ty":None,"ti":"~01h45m — Climax","co":"Groot sacrifices himself to save his friends, whispering this variation of his only phrase","q_en":None,"q_fr":"Nous sommes Groot.","q_es":"Somos Groot."},
    {"q":"Avengers... assemble.","ql":"en","fi":"Avengers: Endgame","ch":"Steve Rogers","ac":"Chris Evans","di":"Anthony & Joe Russo","yr":2019,"ty":"sequel","ti":"~02h34m — Climax","co":"Captain America finally utters the legendary call as all the heroes arrive for the final battle","q_en":None,"q_fr":"Avengers... assemblez-vous !","q_es":"Vengadores... ¡uníos!"},
    {"q":"I am Iron Man.","ql":"en","fi":"Avengers: Endgame","ch":"Tony Stark","ac":"Robert Downey Jr.","di":"Anthony & Joe Russo","yr":2019,"ty":"sequel","ti":"~02h49m — Climax","co":"Tony snaps his own fingers with the Infinity Gauntlet, sacrificing himself to save the universe","q_en":None,"q_fr":"Je suis Iron Man.","q_es":"Yo soy Iron Man."},
    {"q":"I am... inevitable.","ql":"en","fi":"Avengers: Endgame","ch":"Thanos","ac":"Josh Brolin","di":"Anthony & Joe Russo","yr":2019,"ty":"sequel","ti":"~02h45m — Climax","co":"Thanos confidently snaps his fingers in the final battle, only to find his gauntlet empty","q_en":None,"q_fr":"Je suis... inévitable.","q_es":"Soy... inevitable."},
    {"q":"You were the chosen one! It was said that you would destroy the Sith, not join them! Bring balance to the Force, not leave it in darkness! You were my brother, Anakin! I loved you!","ql":"en","fi":"Star Wars: Episode III — Revenge of the Sith","ch":"Obi-Wan Kenobi","ac":"Ewan McGregor","di":"George Lucas","yr":2005,"ty":"sequel","ti":"~02h03m — Climax","co":"Obi-Wan's desperate cry after defeating Anakin on Mustafar, watching his former apprentice consumed by lava and darkness","q_en":None,"q_fr":"Tu étais l'Élu, c'était toi ! La Prophétie voulait que tu détruises les Siths, pas que tu deviennes comme eux ! Tu devais amener l'équilibre dans la Force, pas la condamner à la nuit ! Nous étions comme des frères ! Je t'aimais Anakin !","q_es":"¡Eras el Elegido, eras tú! ¡La Profecía decía que destruirías a los Sith, no que te convertirías en uno de ellos! ¡Debías traer el equilibrio a la Fuerza, no condenarla a la oscuridad! ¡Éramos como hermanos! ¡Te quería, Anakin!"},
    # ── FILMS EN LANGUE FRANÇAISE ─────────────────────────────────────────
    {"q":"Le bonheur n'est pas toujours là où on croit qu'il est.","ql":"fr","fi":"Le Fabuleux Destin d'Amélie Poulain","ch":"Narrateur","ac":"André Dussollier (voice)","di":"Jean-Pierre Jeunet","yr":2001,"ty":None,"ti":"~00h05m — Opening","co":"The narrator introduces Amélie's world, hinting that happiness is found in unexpected places","q_en":"Happiness is not always where you think it is.","q_fr":None,"q_es":"La felicidad no siempre está donde uno cree que está."},
    {"q":"Vous savez c'est quoi la différence entre vous et moi ? Moi j'ai les mains dans le cambouis.","ql":"fr","fi":"Intouchables","ch":"Driss","ac":"Omar Sy","di":"Olivier Nakache & Éric Toledano","yr":2011,"ty":None,"ti":"~00h42m — Act 1","co":"Driss challenges Philippe's refined world by highlighting the difference in their backgrounds","q_en":"You know what the difference is between you and me? I get my hands dirty.","q_fr":None,"q_es":"¿Sabes cuál es la diferencia entre tú y yo? Yo me mancho las manos."},
    {"q":"Dans le Nord, on pleure deux fois. En arrivant et en repartant.","ql":"fr","fi":"Bienvenue chez les Ch'tis","ch":"Antoine Bailleul","ac":"Kad Merad","di":"Dany Boon","yr":2008,"ty":None,"ti":"~01h15m — Act 3","co":"Antoine explains to his wife that the North of France, maligned at first, becomes beloved upon leaving","q_en":"In the North, you cry twice. When you arrive and when you leave.","q_fr":None,"q_es":"En el Norte se llora dos veces. Al llegar y al marcharse."},
    {"q":"Musique !","ql":"fr","fi":"Les Choristes","ch":"Clément Mathieu","ac":"Gérard Jugnot","di":"Christophe Barratier","yr":2004,"ty":None,"ti":"~00h48m — Act 2","co":"Mathieu raises his baton for the first time, transforming the troubled boys into a choir","q_en":"Music!","q_fr":None,"q_es":"¡Música!"},
    {"q":"La vie, c'est comme le vélo : il faut avancer pour ne pas perdre l'équilibre.","ql":"fr","fi":"La Môme","ch":"Édith Piaf","ac":"Marion Cotillard","di":"Olivier Dahan","yr":2007,"ty":None,"ti":"~01h30m — Act 3","co":"Piaf reflects on her life philosophy during one of her lucid moments despite her deteriorating health","q_en":"Life is like riding a bicycle: you have to keep moving to keep your balance.","q_fr":None,"q_es":"La vida es como montar en bicicleta: hay que seguir pedaleando para no perder el equilibrio."},
    {"q":"Non, rien de rien, non, je ne regrette rien.","ql":"fr","fi":"La Môme","ch":"Édith Piaf","ac":"Marion Cotillard","di":"Olivier Dahan","yr":2007,"ty":None,"ti":"~01h55m — Final scene","co":"Piaf's most famous song plays at the emotional climax of her biopic as she performs her iconic anthem","q_en":"No, nothing at all, no, I regret nothing.","q_fr":None,"q_es":"No, nada de nada, no, no me arrepiento de nada."},
    # ── FILMS EN LANGUE CORÉENNE ──────────────────────────────────────────
    {"q":"부자들은 착해요, 왜냐면 돈이 많으니까.","ql":"ko","fi":"Parasite","ch":"Ki-woo","ac":"Choi Woo-shik","di":"Bong Joon-ho","yr":2019,"ty":None,"ti":"~00h30m — Act 1","co":"Ki-woo comments on the Parks' kindness, realizing it's simply the luxury of the wealthy","q_en":"They're rich but they're still nice. Because they're rich.","q_fr":"Ils sont riches mais gentils quand même. Parce qu'ils sont riches.","q_es":"Son ricos pero amables de todas formas. Porque son ricos."},
    {"q":"계획이 없는 것이 최고의 계획이야.","ql":"ko","fi":"Parasite","ch":"Ki-taek","ac":"Song Kang-ho","di":"Bong Joon-ho","yr":2019,"ty":None,"ti":"~00h48m — Act 2","co":"Ki-taek explains to his son Ki-woo his philosophy: never make plans, so you'll never be disappointed","q_en":"You know what kind of plan never fails? No plan at all.","q_fr":"Tu sais quel plan ne rate jamais ? Aucun plan du tout.","q_es":"¿Sabes qué tipo de plan nunca falla? Ningún plan."},
    # ── FILMS EN LANGUE JAPONAISE ─────────────────────────────────────────
    {"q":"一度会ったことは、絶対忘れない。思い出せないだけで。","ql":"ja","fi":"Sen to Chihiro no Kamikakushi","ch":"Haku","ac":"Miyu Irino (voice)","di":"Hayao Miyazaki","yr":2001,"ty":None,"ti":"~01h52m — Final act","co":"Haku tells Chihiro that people never truly forget those they have met — the memories just take time to return","q_en":"Once you've met someone, you never really forget them. It just takes a while for your memories to return.","q_fr":"Quand on rencontre quelqu'un, on ne l'oublie jamais vraiment. Les souvenirs reviennent juste avec le temps.","q_es":"Cuando conoces a alguien, nunca lo olvidas de verdad. Solo tarda un tiempo en que los recuerdos vuelvan."},
    # ── FILMS EN LANGUE ESPAGNOLE ─────────────────────────────────────────
    {"q":"No puede haber paraíso sin infierno.","ql":"es","fi":"El laberinto del fauno","ch":"El Fauno","ac":"Doug Jones","di":"Guillermo del Toro","yr":2006,"ty":None,"ti":"~00h35m — Act 1","co":"The Faun reveals to Ofelia the dark tasks she must complete to prove herself worthy of her true kingdom","q_en":"There can be no paradise without hell.","q_fr":"Il ne peut pas y avoir de paradis sans enfer.","q_es":None},
    # ── FILMS EN LANGUE ITALIENNE ─────────────────────────────────────────
]

# Retirer les doublons sur le champ 'q'
seen = set()
deduped = []
for q in quotes:
    if q["q"] not in seen:
        seen.add(q["q"])
        deduped.append(q)
quotes = deduped

# Validation
for i, q in enumerate(quotes):
    assert isinstance(q["yr"], int), f"Entry {i} ({q['fi']}): yr must be int"
    assert q["yr"] >= 2000, f"Entry {i} ({q['fi']}): year {q['yr']} < 2000"
    assert q["ty"] is None or isinstance(q["ty"], str), f"Entry {i}: ty must be str or None"
    assert (q["q_en"] is None) == (q["ql"] == "en"), f"Entry {i} ({q['fi']}): q_en logic error"
    assert (q["q_fr"] is None) == (q["ql"] == "fr"), f"Entry {i} ({q['fi']}): q_fr logic error"
    assert (q["q_es"] is None) == (q["ql"] == "es"), f"Entry {i} ({q['fi']}): q_es logic error"

with open("assets/quotes_modern.json", "w", encoding="utf-8") as f:
    json.dump([{k: v for k, v in q.items() if k != "td"} for q in quotes], f, ensure_ascii=False, separators=(',', ':'))

td_count = sum(1 for q in quotes if q.get("td"))
if td_count:
    print(f"[TD]  {td_count} traduction(s) marquée(s) td=True à vérifier.")

print(f"{len(quotes)} répliques Modern Cinema générées (toutes >= 2000).")
