BIRDS_RAW = [
  # Accipitriformes (Eagles, Hawks, Kites)
  {"n":"Golden Eagle","ord":"Accipitriformes","fam":"Accipitridae","ha":"Mountains, open country, forests","di":"Mammals, birds, carrion","si":"66-102 cm, 1.8-2.3 m wingspan","sp":"Up to 240 km/h (150 mph) diving; ~50 km/h (31 mph) cruising","ff":"Can dive at over 240 km/h and carry prey heavier than itself; national symbol of 9 countries."},
  {"n":"Bald Eagle","ord":"Accipitriformes","fam":"Accipitridae","ha":"Near large open water, coasts, rivers","di":"Fish, waterfowl, carrion","si":"71-96 cm, 1.8-2.3 m wingspan","sp":"~120 km/h (75 mph) diving; ~56 km/h (35 mph) cruising","ff":"The national bird of the United States; its distinctive white head only develops at age 4-5."},
  {"n":"Harpy Eagle","ord":"Accipitriformes","fam":"Accipitridae","ha":"Tropical lowland rainforests","di":"Sloths, monkeys, large reptiles","si":"86-107 cm, 1.7-2.0 m wingspan","sp":"~80 km/h (50 mph)","ff":"The most powerful eagle in the world; its talons are the size of a grizzly bear's claws."},
  {"n":"Osprey","ord":"Accipitriformes","fam":"Pandionidae","ha":"Near water worldwide","di":"Fish almost exclusively","si":"50-66 cm, 1.5-1.8 m wingspan","sp":"~130 km/h (81 mph) in a dive","ff":"Dives feet-first into water and has reversible outer toes and spiny foot-pads to grip slippery fish."},
  {"n":"Red Kite","ord":"Accipitriformes","fam":"Accipitridae","ha":"Woodland edges, farmland, open country","di":"Carrion, small mammals, earthworms","si":"60-70 cm, 1.4-1.7 m wingspan","sp":"~80 km/h (50 mph)","ff":"Was extinct in England by 1871; a successful reintroduction programme starting 1989 restored thousands."},
  {"n":"Andean Condor","ord":"Cathartiformes","fam":"Cathartidae","ha":"Andean highlands and Pacific coasts","di":"Carrion of large animals","si":"100-130 cm, up to 3.3 m wingspan","sp":"~55 km/h (34 mph) soaring","ff":"Has the largest wingspan of any land bird; can glide 5 hours without flapping using thermal currents."},
  {"n":"Secretary Bird","ord":"Accipitriformes","fam":"Sagittariidae","ha":"African open grasslands and savannas","di":"Snakes, lizards, small mammals","si":"112-152 cm tall","sp":"~30 km/h (19 mph) — mostly terrestrial","ff":"Stamps prey to death with its powerful legs, delivering kicks with the force of 5× its body weight."},
  {"n":"White-tailed Eagle","ord":"Accipitriformes","fam":"Accipitridae","ha":"Large lakes, rivers, coasts","di":"Fish, waterfowl, carrion","si":"70-98 cm, 1.8-2.4 m wingspan","sp":"~70 km/h (43 mph)","ff":"Europe's largest eagle; was extinct in Britain by 1918 and successfully reintroduced from 1975."},
  # Falconiformes (Falcons)
  {"n":"Peregrine Falcon","ord":"Falconiformes","fam":"Falconidae","ha":"Cliffs, cities, open country worldwide","di":"Birds caught in flight","si":"34-58 cm, 0.9-1.2 m wingspan","sp":"Over 389 km/h (242 mph) diving — fastest animal on Earth","ff":"The fastest animal on Earth; in level flight it reaches ~100 km/h (62 mph), but its record stoop exceeds 389 km/h."},
  {"n":"Common Kestrel","ord":"Falconiformes","fam":"Falconidae","ha":"Open farmland, moorland, roadsides","di":"Voles, mice, small birds, insects","si":"27-35 cm, 0.7-0.8 m wingspan","sp":"~35-40 km/h (22-25 mph) hovering; ~60 km/h (37 mph) in flight","ff":"The only European bird able to hover in still air, using its tail as a rudder while scanning below."},
  {"n":"Merlin","ord":"Falconiformes","fam":"Falconidae","ha":"Open moorland, coasts, grasslands","di":"Small birds, dragonflies","si":"25-30 cm, 0.5-0.7 m wingspan","sp":"~90-100 km/h (56-62 mph)","ff":"The smallest European falcon; females are larger than males and may pursue prey three times their size."},
  # Strigiformes (Owls)
  {"n":"Barn Owl","ord":"Strigiformes","fam":"Tytonidae","ha":"Open farmland, meadows, woodland edges","di":"Voles, mice, shrews","si":"29-44 cm, 0.8-0.95 m wingspan","sp":"~25 km/h (16 mph) — near-silent flight","ff":"Its heart-shaped facial disc acts like a satellite dish, locating prey by sound alone in total darkness."},
  {"n":"Great Horned Owl","ord":"Strigiformes","fam":"Strigidae","ha":"Forests, deserts, cities across the Americas","di":"Rabbits, skunks, other raptors","si":"46-63 cm, 1.0-1.5 m wingspan","sp":"~65 km/h (40 mph)","ff":"Has the most diverse diet of any North American raptor; regularly kills other owls and hawks."},
  {"n":"Snowy Owl","ord":"Strigiformes","fam":"Strigidae","ha":"Arctic tundra, open fields in winter","di":"Lemmings, hares, birds","si":"53-65 cm, 1.25-1.5 m wingspan","sp":"~60 km/h (37 mph)","ff":"Active by day; lemming population cycles cause mass movements south — 'irruptions' — every few years."},
  {"n":"Eurasian Eagle-Owl","ord":"Strigiformes","fam":"Strigidae","ha":"Mountains, forests, rocky ravines","di":"Rabbits, hedgehogs, small deer","si":"58-75 cm, 1.6-2.0 m wingspan","sp":"~50 km/h (31 mph)","ff":"Europe's largest owl; can kill prey as large as young roe deer and has no natural predators as an adult."},
  # Passeriformes (Perching birds)
  {"n":"European Robin","ord":"Passeriformes","fam":"Turdidae","ha":"Woodland, gardens, hedgerows","di":"Worms, insects, berries","si":"12-14 cm","sp":"~29 km/h (18 mph)","ff":"Famously tame around gardeners; has a quantum compass using entangled electrons to navigate by Earth's magnetic field."},
  {"n":"Common Nightingale","ord":"Passeriformes","fam":"Muscicapidae","ha":"Dense thickets, woodland undergrowth","di":"Insects, worms, berries","si":"15-16.5 cm","sp":"~25 km/h (16 mph)","ff":"Sings by night as well as day; its song has 1,000+ distinct sounds and inspired Keats, Shelley, and Brahms."},
  {"n":"Barn Swallow","ord":"Passeriformes","fam":"Hirundinidae","ha":"Open countryside near water and buildings","di":"Flying insects","si":"14-19 cm, 0.3-0.35 m wingspan","sp":"~40-50 km/h (25-31 mph); bursts up to 75 km/h (47 mph)","ff":"Migrates up to 10,000 km between Europe and South Africa; navigates with an internal magnetic map."},
  {"n":"Common Raven","ord":"Passeriformes","fam":"Corvidae","ha":"Forests, mountains, arctic tundra","di":"Carrion, small animals, eggs, grains","si":"54-67 cm, 1.1-1.3 m wingspan","sp":"~48 km/h (30 mph)","ff":"Among the world's most intelligent animals; uses tools, plans for the future, and passes a mirror test."},
  {"n":"Eurasian Jay","ord":"Passeriformes","fam":"Corvidae","ha":"Woodland, parks, gardens","di":"Acorns, insects, eggs, small birds","si":"32-35 cm","sp":"~25-30 km/h (16-19 mph)","ff":"Buries up to 5,000 acorns per autumn and remembers nearly all locations — planting thousands of oak trees."},
  {"n":"Common Swift","ord":"Apodiformes","fam":"Apodidae","ha":"Skies over cities, towns and open country","di":"Flying insects and spiders","si":"16-17 cm, 0.4-0.44 m wingspan","sp":"Up to 111 km/h (69 mph) — fastest level-flying bird","ff":"Spends almost its entire life airborne — sleeping, mating, and feeding in flight; lands only to nest."},
  {"n":"European Goldfinch","ord":"Passeriformes","fam":"Fringillidae","ha":"Gardens, woodland edges, farmland","di":"Seeds, especially thistles","si":"12-13 cm","sp":"~40 km/h (25 mph)","ff":"Its slender beak is perfectly shaped to extract seeds from thistles and teasels that other birds cannot reach."},
  {"n":"Common Starling","ord":"Passeriformes","fam":"Sturnidae","ha":"Farmland, parks, urban areas","di":"Invertebrates, fruit, scraps","si":"19-22 cm","sp":"~77 km/h (48 mph)","ff":"Forms murmurations — synchronised aerial flocks of millions — where each bird tracks its 7 nearest neighbours."},
  {"n":"Eurasian Wren","ord":"Passeriformes","fam":"Troglodytidae","ha":"Dense undergrowth, woodland, gardens","di":"Insects, spiders, small invertebrates","si":"9-10 cm","sp":"~25 km/h (16 mph)","ff":"One of the loudest birds for its size; its song is 10× louder per unit mass than a rooster's crow."},
  {"n":"Song Thrush","ord":"Passeriformes","fam":"Turdidae","ha":"Woodland, gardens, hedgerows","di":"Snails, worms, berries","si":"20-22 cm","sp":"~40 km/h (25 mph)","ff":"One of very few birds that uses a tool — a stone 'anvil' to smash open snail shells."},
  # Ciconiiformes / Pelecaniformes
  {"n":"White Stork","ord":"Ciconiiformes","fam":"Ciconiidae","ha":"Open farmland, wetlands near human habitation","di":"Frogs, insects, small mammals, fish","si":"100-115 cm, 1.55-2.15 m wingspan","sp":"~45 km/h (28 mph)","ff":"Migrates up to 20,000 km between Europe and sub-Saharan Africa; returns to the same nest each year."},
  {"n":"Grey Heron","ord":"Pelecaniformes","fam":"Ardeidae","ha":"Rivers, lakes, estuaries, marshes","di":"Fish, frogs, small mammals, birds","si":"84-102 cm, 1.55-1.75 m wingspan","sp":"~47 km/h (29 mph)","ff":"Can stand motionless for hours then strike at 120 km/h (75 mph) with its spear-like bill."},
  {"n":"Great White Egret","ord":"Pelecaniformes","fam":"Ardeidae","ha":"Wetlands, rivers, coasts worldwide","di":"Fish, frogs, aquatic invertebrates","si":"80-104 cm, 1.3-1.7 m wingspan","sp":"~42 km/h (26 mph)","ff":"Was hunted nearly to extinction in the 19th century for its breeding plumes used in ladies' hats."},
  {"n":"Great Frigatebird","ord":"Suliformes","fam":"Fregatidae","ha":"Tropical ocean islands","di":"Fish, squid, stolen food","si":"86-114 cm, 2.05-2.3 m wingspan","sp":"Up to 153 km/h (95 mph)","ff":"Males inflate a bright-red throat pouch like a balloon for up to 20 minutes to attract females."},
  # Phoenicopteriformes
  {"n":"Greater Flamingo","ord":"Phoenicopteriformes","fam":"Phoenicopteridae","ha":"Saline or alkaline lakes and lagoons","di":"Algae, brine shrimp, small invertebrates","si":"110-150 cm tall","sp":"~50-60 km/h (31-37 mph)","ff":"Its pink colour comes entirely from carotenoid pigments in its food; captive flamingos fed plain diets turn white."},
  # Sphenisciformes (Penguins)
  {"n":"Emperor Penguin","ord":"Sphenisciformes","fam":"Spheniscidae","ha":"Antarctic sea ice and surrounding ocean","di":"Fish, squid, krill","si":"110-130 cm tall","sp":"Flightless — swims at up to 25 km/h (16 mph)","ff":"Breeds in -60°C (-76°F) blizzards; males fast for 4 months while incubating a single egg on their feet."},
  {"n":"Little Blue Penguin","ord":"Sphenisciformes","fam":"Spheniscidae","ha":"Coasts of southern Australia and New Zealand","di":"Small fish, squid, krill","si":"30-33 cm tall","sp":"Flightless — swims at ~6 km/h (4 mph)","ff":"The world's smallest penguin; returns to the same burrow each year and may live over 20 years."},
  {"n":"African Penguin","ord":"Sphenisciformes","fam":"Spheniscidae","ha":"Coasts and islands of southern Africa","di":"Anchovies, sardines, squid","si":"60-70 cm tall","sp":"Flightless — swims at up to 20 km/h (12 mph)","ff":"Also called the 'jackass penguin' for its donkey-like bray; listed as Endangered due to fish stock collapse."},
  # Procellariiformes (Seabirds)
  {"n":"Wandering Albatross","ord":"Procellariiformes","fam":"Diomedeidae","ha":"Southern Ocean, subantarctic islands","di":"Squid, fish, carrion","si":"107-135 cm, 2.5-3.5 m wingspan","sp":"~120 km/h (75 mph); cruises at ~55 km/h (34 mph)","ff":"Has the longest wingspan of any living bird; can circle the globe in 46 days using dynamic soaring without flapping."},
  {"n":"Atlantic Puffin","ord":"Charadriiformes","fam":"Alcidae","ha":"North Atlantic coasts and open ocean","di":"Sand eels, small fish","si":"26-29 cm","sp":"~88 km/h (55 mph)","ff":"Can carry up to 62 fish crosswise in its beak at once thanks to spines on its palate."},
  {"n":"Arctic Tern","ord":"Charadriiformes","fam":"Laridae","ha":"Arctic and subarctic coasts","di":"Small fish, invertebrates","si":"28-39 cm, 0.65-0.75 m wingspan","sp":"~40 km/h (25 mph)","ff":"Makes the longest migration of any animal — 90,000 km (56,000 mi) round trip from Arctic to Antarctic each year."},
  {"n":"Common Gannet","ord":"Suliformes","fam":"Sulidae","ha":"North Atlantic coasts and open sea","di":"Mackerel, herring, sand eels","si":"81-110 cm, 1.7-2.0 m wingspan","sp":"~100 km/h (62 mph) diving","ff":"Dives from 30 m (100 ft) at 100 km/h, hitting water like an arrow; air sacs in its skull cushion the impact."},
  {"n":"Blue-footed Booby","ord":"Suliformes","fam":"Sulidae","ha":"Pacific coasts of the Americas","di":"Fish, caught in plunge-dives","si":"76-84 cm","sp":"~97 km/h (60 mph) diving","ff":"Males show off their vivid blue feet in a high-stepping dance; brighter feet signal better health to females."},
  # Anseriformes (Waterfowl)
  {"n":"Mute Swan","ord":"Anseriformes","fam":"Anatidae","ha":"Lakes, rivers, estuaries","di":"Aquatic plants, algae, small invertebrates","si":"125-170 cm, 2.0-2.4 m wingspan","sp":"~88 km/h (55 mph)","ff":"The heaviest flying bird in the UK; young cygnets hitch rides on their parents' backs for protection."},
  {"n":"Mallard","ord":"Anseriformes","fam":"Anatidae","ha":"Wetlands, parks, rivers worldwide","di":"Seeds, aquatic plants, invertebrates","si":"50-65 cm","sp":"~55-60 km/h (34-37 mph)","ff":"Ancestor of almost all domestic duck breeds; males grow a new set of feathers after breeding season."},
  {"n":"Canada Goose","ord":"Anseriformes","fam":"Anatidae","ha":"Parks, farmland, rivers, lakes","di":"Grass, aquatic plants, grain","si":"75-110 cm, 1.3-1.8 m wingspan","sp":"~65 km/h (40 mph)","ff":"Pairs mate for life and mourn lost partners; can navigate thousands of kilometres using the sun and stars."},
  {"n":"Mandarin Duck","ord":"Anseriformes","fam":"Anatidae","ha":"Wooded ponds and rivers in East Asia","di":"Seeds, plants, small fish, insects","si":"41-49 cm","sp":"~65 km/h (40 mph)","ff":"Considered a symbol of fidelity in East Asia; the male's spectacular plumage is considered one of the most beautiful of any bird."},
  # Psittaciformes (Parrots)
  {"n":"Hyacinth Macaw","ord":"Psittaciformes","fam":"Psittacidae","ha":"Palm swamps and woodlands of South America","di":"Palm nuts, seeds, fruit","si":"100 cm, 1.2-1.4 m wingspan","sp":"~56-60 km/h (35-37 mph)","ff":"The world's largest parrot by length; its beak can crack a coconut shell and generates enormous force."},
  {"n":"Scarlet Macaw","ord":"Psittaciformes","fam":"Psittacidae","ha":"Tropical rainforests of Central and South America","di":"Seeds, nuts, fruit, clay (for minerals)","si":"81 cm, 1.0-1.1 m wingspan","sp":"~56 km/h (35 mph)","ff":"Eats toxic seeds safely by visiting clay licks — the minerals neutralise plant poisons in its digestive system."},
  {"n":"African Grey Parrot","ord":"Psittaciformes","fam":"Psittacidae","ha":"West and Central African rainforests","di":"Seeds, nuts, fruit, leaves","si":"33-41 cm","sp":"~40 km/h (25 mph)","ff":"The most cognitively advanced bird; Alex, a famous individual, learned over 100 words and could count to 6."},
  {"n":"Kakapo","ord":"Psittaciformes","fam":"Strigopidae","ha":"New Zealand forests (now only offshore islands)","di":"Plants, seeds, fruit, pollen","si":"58-64 cm","sp":"Flightless","ff":"The world's only flightless parrot and heaviest; critically endangered with only ~200 individuals remaining."},
  {"n":"Kea","ord":"Psittaciformes","fam":"Nestoridae","ha":"Alpine zones of New Zealand's South Island","di":"Plant matter, invertebrates, carrion, garbage","si":"46-50 cm","sp":"~60 km/h (37 mph)","ff":"The world's only alpine parrot; dismantles cars for entertainment and scores as high as primates in problem-solving tests."},
  # Struthioniformes / Casuariiformes (Flightless)
  {"n":"Common Ostrich","ord":"Struthioniformes","fam":"Struthionidae","ha":"African savannas and deserts","di":"Seeds, plants, insects, lizards","si":"175-275 cm tall","sp":"Flightless — runs at up to 70 km/h (43 mph); fastest bird on land","ff":"The world's largest and fastest running bird, reaching 70 km/h; its eye (5 cm / 2 in) is bigger than its brain."},
  {"n":"Emu","ord":"Casuariiformes","fam":"Casuariidae","ha":"Australian grasslands, scrublands, forests","di":"Plants, insects, small vertebrates","si":"150-190 cm tall","sp":"Flightless — runs at up to 50 km/h (31 mph)","ff":"Second largest bird; Australia lost the 'Emu War' of 1932 — soldiers failed to control wild emu populations."},
  {"n":"Southern Cassowary","ord":"Casuariiformes","fam":"Casuariidae","ha":"Tropical rainforests of New Guinea and Australia","di":"Fruit, fungi, small vertebrates","si":"127-170 cm tall","sp":"Flightless — runs at up to 50 km/h (31 mph)","ff":"Considered the world's most dangerous bird; its inner toe bears a 12 cm (5 in) dagger-like claw."},
  {"n":"North Island Brown Kiwi","ord":"Apterygiformes","fam":"Apterygidae","ha":"New Zealand forests","di":"Earthworms, insects, berries","si":"35-45 cm","sp":"Flightless — walks at ~3 km/h (2 mph)","ff":"New Zealand's national bird; has nostrils at the tip of its bill and the largest egg-to-body ratio of any bird."},
  # Trochiliformes (Hummingbirds)
  {"n":"Ruby-throated Hummingbird","ord":"Trochiliformes","fam":"Trochilidae","ha":"Eastern North America, gardens and forests","di":"Nectar, small insects","si":"7-9 cm","sp":"~48 km/h (30 mph); over 100 km/h (62 mph) in courtship dives","ff":"Beats its wings 53 times per second and is the only bird able to fly backwards, sideways, and hover."},
  {"n":"Bee Hummingbird","ord":"Trochiliformes","fam":"Trochilidae","ha":"Cuban forests and gardens","di":"Nectar, small insects","si":"5-6 cm","sp":"~40 km/h (25 mph); wings beat 80 times per second","ff":"The world's smallest bird; its egg is smaller than a coffee bean and its heart beats 1,200 times per minute."},
  {"n":"Sword-billed Hummingbird","ord":"Trochiliformes","fam":"Trochilidae","ha":"Andean cloud forests","di":"Nectar from long tubular flowers","si":"12-14 cm + 10 cm bill","sp":"~45 km/h (28 mph)","ff":"The only bird with a bill longer than its body; co-evolved with passion flowers that only it can pollinate."},
  # Piciformes (Woodpeckers & Toucans)
  {"n":"Great Spotted Woodpecker","ord":"Piciformes","fam":"Picidae","ha":"Woodland across Eurasia","di":"Insects (larvae), seeds, eggs, nestlings","si":"20-24 cm","sp":"~55 km/h (34 mph)","ff":"Drums up to 20 times per second; its brain is shock-absorbed by spongy bone and a hyoid bone that wraps around the skull."},
  {"n":"Black Woodpecker","ord":"Piciformes","fam":"Picidae","ha":"Old-growth forests of Eurasia","di":"Wood-boring beetle larvae, ants","si":"40-46 cm","sp":"~60 km/h (37 mph)","ff":"Creates nest holes later used by owls, ducks, and martens; a single bird can excavate 100 litres of wood per year."},
  {"n":"Toco Toucan","ord":"Piciformes","fam":"Ramphastidae","ha":"South American woodland and savanna","di":"Fruit, insects, eggs, small lizards","si":"55-65 cm","sp":"~65 km/h (40 mph)","ff":"Its enormous orange bill is a cooling radiator; blood flow to it increases in heat, releasing body warmth."},
  # Coraciiformes (Kingfishers & Bee-eaters)
  {"n":"Common Kingfisher","ord":"Coraciiformes","fam":"Alcedinidae","ha":"Rivers, lakes, streams in Eurasia","di":"Small fish, aquatic invertebrates","si":"16-17 cm","sp":"~40 km/h (25 mph); dives at ~90 km/h (56 mph)","ff":"Dives at high speed; its beak inspired the design of Japan's Shinkansen bullet train nose to reduce sonic booms."},
  {"n":"European Bee-eater","ord":"Coraciiformes","fam":"Meropidae","ha":"Open country, river banks, Mediterranean scrub","di":"Bees, wasps, dragonflies","si":"25-29 cm","sp":"~50 km/h (31 mph)","ff":"Catches bees in flight and rubs them against a perch to remove the sting before swallowing them."},
  {"n":"Laughing Kookaburra","ord":"Coraciiformes","fam":"Alcedinidae","ha":"Australian open woodland and gardens","di":"Insects, reptiles, small vertebrates","si":"41-47 cm","sp":"~40 km/h (25 mph)","ff":"Its distinctive 'laughing' call announces territory; family groups use it as a dawn chorus to claim their patch."},
  # Galliformes (Gamebirds)
  {"n":"Indian Peafowl","ord":"Galliformes","fam":"Phasianidae","ha":"South Asian forests and farmland","di":"Seeds, insects, small reptiles, berries","si":"100-115 cm + 140-160 cm train","sp":"~16 km/h (10 mph) walking; up to 60 km/h (37 mph) in flight","ff":"The male's train has 150-200 feathers with iridescent eyespots; Darwin found the peacock's tail troubling to his theory."},
  {"n":"Common Pheasant","ord":"Galliformes","fam":"Phasianidae","ha":"Farmland, woodland edges, scrub","di":"Seeds, berries, insects, small animals","si":"55-90 cm","sp":"~60-70 km/h (37-43 mph) in bursts","ff":"Originally from Asia, introduced to Europe by Romans; now one of the world's most widely distributed gamebirds."},
  {"n":"Rock Ptarmigan","ord":"Galliformes","fam":"Phasianidae","ha":"Arctic and alpine tundra","di":"Buds, leaves, berries, seeds","si":"31-35 cm","sp":"~50 km/h (31 mph)","ff":"Changes plumage three times a year — brown in summer, white in winter — a camouflage evolution unique among birds."},
  # Charadriiformes (Shorebirds)
  {"n":"Bar-tailed Godwit","ord":"Charadriiformes","fam":"Scolopacidae","ha":"Arctic tundra (breeding), tidal flats (wintering)","di":"Invertebrates, marine worms","si":"37-41 cm","sp":"~100 km/h (62 mph) average over migration","ff":"Flies non-stop from Alaska to New Zealand — 11,000+ km (7,000 mi) in 11 days — the longest non-stop flight of any bird."},
  {"n":"Eurasian Oystercatcher","ord":"Charadriiformes","fam":"Haematopodidae","ha":"Coasts, estuaries, inland grasslands","di":"Mussels, cockles, worms","si":"40-45 cm","sp":"~60 km/h (37 mph)","ff":"Can live over 40 years; uses one of two tactics to open shellfish — stabbing or hammering — and teaches it to chicks."},
  # Columbiformes (Pigeons & Doves)
  {"n":"Rock Dove","ord":"Columbiformes","fam":"Columbidae","ha":"Cliffs, cities worldwide","di":"Seeds, grain, scraps","si":"29-37 cm","sp":"Up to 148 km/h (92 mph) — homing pigeon record","ff":"Ancestor of the domestic pigeon; used in both World Wars as a messenger and awarded the Dickin Medal for bravery."},
  {"n":"Victoria Crowned Pigeon","ord":"Columbiformes","fam":"Columbidae","ha":"Lowland forests of New Guinea","di":"Fallen fruit, seeds, invertebrates","si":"66-74 cm","sp":"~25 km/h (16 mph)","ff":"The world's largest pigeon; named for Queen Victoria due to its extraordinary lacy blue crest."},
  # Cuculiformes
  {"n":"Common Cuckoo","ord":"Cuculiformes","fam":"Cuculidae","ha":"Woodland, farmland, moorland","di":"Hairy caterpillars (especially toxic species other birds avoid)","si":"32-36 cm","sp":"~58 km/h (36 mph)","ff":"A brood parasite — lays eggs in other birds' nests; the chick evicts host eggs and is raised by unsuspecting foster parents."},
  # Trogoniformes
  {"n":"Resplendent Quetzal","ord":"Trogoniformes","fam":"Trogonidae","ha":"Cloud forests of Central America","di":"Fruit (especially wild avocados), insects","si":"36-40 cm + 65 cm tail feathers","sp":"~35 km/h (22 mph)","ff":"Considered the most beautiful bird in the Americas; sacred to the Maya and Aztec — tail feathers were worth more than gold."},
  # Passeriformes cont.
  {"n":"Superb Lyrebird","ord":"Passeriformes","fam":"Menuridae","ha":"Australian temperate rainforests","di":"Insects, worms, spiders","si":"74-98 cm","sp":"~25 km/h (16 mph) — mostly ground-dwelling","ff":"The world's greatest mimic — reproduces chainsaws, camera shutters, and other bird species with perfect accuracy."},
  {"n":"Eurasian Blackbird","ord":"Passeriformes","fam":"Turdidae","ha":"Woodland, gardens, hedgerows","di":"Worms, berries, insects","si":"24-25 cm","sp":"~40 km/h (25 mph)","ff":"One of the first birds to sing each morning; males sing 170+ distinct phrases, often incorporating urban sounds."},
  {"n":"House Sparrow","ord":"Passeriformes","fam":"Passeridae","ha":"Human habitations worldwide","di":"Seeds, grain, insects","si":"14-16 cm","sp":"~45 km/h (28 mph)","ff":"Has lived alongside humans for 10,000 years; found on every continent except Antarctica."},
  # Pelecaniformes
  {"n":"Great White Pelican","ord":"Pelecaniformes","fam":"Pelecanidae","ha":"Large freshwater lakes, rivers, deltas","di":"Fish","si":"140-180 cm, 2.3-2.8 m wingspan","sp":"~56 km/h (35 mph)","ff":"Its pouch holds 13 litres (3.4 gallons) — three times its stomach; groups form a semicircle to herd fish before scooping."},
  # Bucerotiformes (Hornbills)
  {"n":"Great Hornbill","ord":"Bucerotiformes","fam":"Bucerotidae","ha":"Forests of South and Southeast Asia","di":"Fruit, small animals, insects","si":"94-102 cm","sp":"~40 km/h (25 mph)","ff":"The female seals herself inside a tree cavity for months, fed through a small hole by the male, until chicks hatch."},
  # Passeriformes (Birds of Paradise)
  {"n":"Magnificent Bird-of-Paradise","ord":"Passeriformes","fam":"Paradisaeidae","ha":"Hill forests of New Guinea","di":"Fruit, arthropods","si":"19 cm (+ ornamental plumes)","sp":"~30 km/h (19 mph)","ff":"The male clears a display court, then performs an extraordinary dance with iridescent plumes to attract females."},
  # Pelecaniformes
  {"n":"Shoebill","ord":"Pelecaniformes","fam":"Balaenicipitidae","ha":"Papyrus swamps of Central Africa","di":"Lungfish, baby crocodiles, small mammals","si":"110-140 cm tall","sp":"~45 km/h (28 mph)","ff":"Strikes with a shoe-shaped bill as wide as a human's foot; stands motionless for hours — nicknamed the 'whalehead stork'."},
]
