# Key legend
# n    : name
# cat  : category (Genus / Species / Feature / Special / Variety)
# alt  : altitude — WMO metric standard (km/m)
# vol  : typical volume or dimensions
# cond : formation conditions (temperature, humidity, region)
# ap   : appearance
# aw   : associated weather
# ff   : famous for
# im   : image URL (added by generator)

CLOUDS = [
    # ── Genera ───────────────────────────────────────────────────────────────
    {"n":"Cirrus","cat":"Genus","alt":"High level (5-13 km)",
     "vol":"Isolated filaments 10-200 km long, 100-500 m thick; large sheet ~500-5,000 km³",
     "cond":"Temperature -20 °C to -60 °C; very low humidity; composed entirely of ice crystals",
     "ap":"Thin wispy white filaments or delicate curls; often iridescent at sunset",
     "aw":"Fair weather; if thickening and spreading, warm front approaching within 12-24 h",
     "ff":"First cloud type formally classified by Luke Howard in 1803; composed entirely of ice crystals"},

    {"n":"Cirrocumulus","cat":"Genus","alt":"High level (5-13 km)",
     "vol":"Sheet 200-2,000 km², 100-400 m thick; individual cloudlets < 1 km across; ~20-800 km³",
     "cond":"Temperature below -20 °C; supercooled water droplets briefly present at cloud tops",
     "ap":"Small rippled or granular white puffs in regular rows; no shading; each element < finger-width at arm's length",
     "aw":"Usually fair; short-lived; extensive coverage indicates unstable high-altitude air",
     "ff":"Forms the 'mackerel sky'; the rarest of the ten official cloud genera"},

    {"n":"Cirrostratus","cat":"Genus","alt":"High level (5-13 km)",
     "vol":"Sheet 500-5,000 km wide, 0.5-2 km thick; ~10,000-100,000 km³",
     "cond":"Temperature -20 °C to -60 °C; ice crystals from spreading cirrus or jet-stream moisture",
     "ap":"Thin transparent white or grey veil covering large areas; sun and moon visible through it",
     "aw":"22° solar or lunar halo; rain or snow likely within 12-24 hours",
     "ff":"Creates halos around the sun and moon; can cover the entire sky without being noticed"},

    {"n":"Altocumulus","cat":"Genus","alt":"Mid level (2-7 km)",
     "vol":"Sheets 100-1,000 km², 200-700 m thick; individual elements 1-5 km wide",
     "cond":"Temperature -5 °C to +10 °C; mixed water-ice; unstable mid-level air",
     "ap":"Grey and white patchy layers or rolls with shading; elements larger than cirrocumulus",
     "aw":"Generally stable; castellanus variety signals afternoon thunderstorms",
     "ff":"Most common mid-level cloud; lenticularis variety regularly mistaken for UFOs"},

    {"n":"Altostratus","cat":"Genus","alt":"Mid level (2-7 km)",
     "vol":"Sheet 500-5,000 km wide, 1-4 km thick; ~50,000-500,000 km³",
     "cond":"Temperature 0 °C to -20 °C; widespread lifting of moist air ahead of a front",
     "ap":"Uniform grey or blue-grey sheet; sun appears as through frosted glass; no halo possible",
     "aw":"Continuous widespread rain or snow; thickens into nimbostratus",
     "ff":"The 'watery sun' effect — sun dimly visible but no shadows cast on the ground"},

    {"n":"Nimbostratus","cat":"Genus","alt":"Multi-level (base 0-4 km, extends to 8 km)",
     "vol":"Sheet 200-2,000 km wide, 2-4 km thick; ~100,000-500,000 km³",
     "cond":"Temperature -10 °C to +5 °C; deep layer of ascending moist air; active frontal system",
     "ap":"Dark thick featureless grey layer; ragged base; no defined edges",
     "aw":"Continuous moderate-to-heavy rain or snow; low visibility; can persist for many hours",
     "ff":"The archetypal 'rainy day' cloud; thick enough to completely block sunlight"},

    {"n":"Stratocumulus","cat":"Genus","alt":"Low level (0-2 km)",
     "vol":"Sheets 500-5,000 km wide, 200-800 m thick; individual cells 1-3 km across",
     "cond":"Temperature +5 °C to +20 °C; shallow convection capped by a temperature inversion",
     "ap":"Grey/white patches, sheets or rolls with darker areas between elements",
     "aw":"Light drizzle; mostly overcast without significant precipitation",
     "ff":"Most common cloud type on Earth; covers ~23% of global ocean surface at any given time"},

    {"n":"Stratus","cat":"Genus","alt":"Low level (0-600 m)",
     "vol":"Sheet 100-2,000 km wide, 100-600 m thick; ~1,000-50,000 km³",
     "cond":"Temperature near 0 °C; high near-surface humidity; light winds; nocturnal radiative cooling",
     "ap":"Uniform featureless grey layer with a flat base; resembles lifted fog",
     "aw":"Drizzle; possible light freezing drizzle; dense enough to block sunlight",
     "ff":"When stratus forms at ground level it becomes fog — both phenomena share exactly the same mechanism"},

    {"n":"Cumulus","cat":"Genus","alt":"Low level (base 0.5-3 km)",
     "vol":"Individual cloud 0.5-3 km wide, 0.5-3 km tall; ~0.1-10 km³",
     "cond":"Temperature +5 °C to +35 °C; surface heating generating convective thermals; humidity > 70%",
     "ap":"White puffy cotton-ball clouds with flat dark bases and rounded cauliflower tops",
     "aw":"Fair weather (small); showers or thunderstorms if vertical development is significant",
     "ff":"The universally recognised 'classic cloud shape'; children draw cumulus instinctively"},

    {"n":"Cumulonimbus","cat":"Genus","alt":"Multi-level (base 0.5 km, anvil to 18 km)",
     "vol":"Tower 5-20 km wide, 10-18 km tall; ~500-5,000 km³ for a large storm",
     "cond":"Temperature > +20 °C at surface; CAPE > 1,000 J/kg; deep atmospheric moisture",
     "ap":"Massive tower with flat dark base and flat glaciated anvil top",
     "aw":"Severe thunderstorms, large hail, tornadoes, flash flooding, lightning",
     "ff":"Most powerful cloud on Earth; can release more energy than a nuclear bomb; updrafts > 180 km/h"},

    # ── Species ───────────────────────────────────────────────────────────────
    {"n":"Cirrus fibratus","cat":"Species","alt":"High level (6-13 km)",
     "vol":"Filaments 10-300 km long, 50-200 m thick; large sheet ~50-3,000 km³",
     "cond":"Temperature below -40 °C; strong jet-stream winds dispersing ice crystals",
     "ap":"Long thin filaments like white hair or horse tails across a blue sky",
     "aw":"Usually fair weather; first sign of an approaching warm front",
     "ff":"'Mare's tails' — the most common cirrus species; the trailing hook points into the wind"},

    {"n":"Cirrus uncinus","cat":"Species","alt":"High level (6-13 km)",
     "vol":"Isolated hooks 1-50 km long; extended sheet ~100-5,000 km³",
     "cond":"Temperature below -40 °C; wind shear between ice-crystal trails and slower air below",
     "ap":"Hook or comma shapes; the curved end points upward",
     "aw":"Approaching warm front 12-24 hours away",
     "ff":"The hook forms as ice crystals fall into slower winds below; reliable frontal precursor"},

    {"n":"Cirrus spissatus","cat":"Species","alt":"High level (6-13 km)",
     "vol":"Dense patch 20-200 km wide, 0.3-1 km thick; ~200-2,000 km³",
     "cond":"Temperature below -50 °C; remnant of cumulonimbus anvil glaciation",
     "ap":"Dense greyish cirrus patch; thick enough to slightly veil the sun",
     "aw":"Post-storm; can persist for hours after the parent thunderstorm has dissipated",
     "ff":"The densest cirrus cloud — a residual 'ghost' of a spent cumulonimbus"},

    {"n":"Altocumulus lenticularis","cat":"Species","alt":"Mid level (2-7 km)",
     "vol":"Individual cloud 2-20 km wide, 200-500 m thick; ~1-50 km³",
     "cond":"Temperature -5 °C to +5 °C; strong steady winds over mountains; stable layered atmosphere",
     "ap":"Smooth lens or saucer shape; stationary over ridges despite strong winds; sharp edges",
     "aw":"Strong winds aloft; dry air at altitude; turbulence near the cloud",
     "ff":"The most frequently reported 'UFO' cloud; can stack into multi-layered 'pile of plates'"},

    {"n":"Altocumulus castellanus","cat":"Species","alt":"Mid level (2-7 km)",
     "vol":"Towers 0.5-2 km wide, 0.5-2 km tall; sheet 50-500 km wide",
     "cond":"Temperature -5 °C to +5 °C; conditional instability at mid-levels; morning moisture",
     "ap":"Turrets or castle battlements growing upward from a common flat base",
     "aw":"Morning sighting is a reliable predictor of afternoon thunderstorms",
     "ff":"'Castle clouds' — forecasters use early-morning sightings as a thunderstorm warning"},

    {"n":"Altocumulus floccus","cat":"Species","alt":"Mid level (2-7 km)",
     "vol":"Tufts 0.2-1 km wide; sheet 50-300 km; ~5-100 km³",
     "cond":"Temperature -5 °C to +5 °C; atmospheric instability and turbulence at altitude",
     "ap":"Ragged tufted cloudlets each with a trailing virga streak; woolly appearance",
     "aw":"Pre-convective environment; thunderstorm development likely",
     "ff":"Often appears hours before a convective outbreak; looks like tufts of cotton hanging in the sky"},

    {"n":"Stratocumulus lenticularis","cat":"Species","alt":"Low level (0.5-2 km)",
     "vol":"Individual cloud 2-15 km wide, 200-600 m thick; ~2-30 km³",
     "cond":"Temperature +5 °C to +15 °C; mountain lee waves; stable boundary layer",
     "ap":"Low lens-shaped clouds aligned with mountain wave crests; smooth surfaces",
     "aw":"Gusty winds near mountains; moderate turbulence",
     "ff":"Stationary despite strong winds — the orographic wave continuously reforms the cloud"},

    {"n":"Cumulus humilis","cat":"Species","alt":"Low level (0.5-2 km)",
     "vol":"Isolated cloud 0.3-1 km wide, 200-500 m tall; ~0.01-0.2 km³",
     "cond":"Temperature +10 °C to +30 °C; weak thermals; humidity 50-70%; no significant instability",
     "ap":"Small flat-based clouds wider than tall; bright white tops; well-separated",
     "aw":"Fair weather; no precipitation; typically dissolve by evening",
     "ff":"Classic 'fair-weather cumulus'; their spacing reveals the spacing of boundary-layer thermals"},

    {"n":"Cumulus congestus","cat":"Species","alt":"Low level to mid (0.5-8 km)",
     "vol":"Tower 1-5 km wide, 3-8 km tall; ~5-100 km³",
     "cond":"Temperature +15 °C to +35 °C; CAPE 500-1,500 J/kg; high humidity above the freezing level",
     "ap":"Towering cauliflower-shaped pillar; crisp white edges; dark flat base",
     "aw":"Heavy showers; may develop into cumulonimbus within 30 minutes",
     "ff":"'Towering cumulus' — the last stage before a cloud becomes a thunderstorm"},

    {"n":"Cumulonimbus capillatus","cat":"Species","alt":"Multi-level (0.5-15 km)",
     "vol":"Tower 5-20 km wide, 10-15 km tall; anvil 100-500 km wide; ~1,000-10,000 km³",
     "cond":"Temperature > +20 °C at surface; CAPE > 1,500 J/kg; anvil glaciation at -40 °C",
     "ap":"Fibrous silky anvil spreading downwind; tall tower with glaciated upper portion",
     "aw":"Severe thunderstorms; large hail; possible tornadoes; lightning",
     "ff":"Mature thunderstorm stage; the anvil can extend 300 km downwind and persist after the storm ends"},

    {"n":"Cumulonimbus calvus","cat":"Species","alt":"Multi-level (0.5-10 km)",
     "vol":"Tower 3-15 km wide, 6-10 km tall; ~100-1,000 km³",
     "cond":"Temperature +18 °C to +30 °C at surface; CAPE 500-1,500 J/kg; top approaching -10 °C",
     "ap":"Smooth bald cauliflower top — water droplets not yet glaciated into ice",
     "aw":"Building thunderstorm; heavy rain beginning; transition to capillatus imminent",
     "ff":"The transition stage — actively glaciating; top changes from crisp white to silky within minutes"},

    # ── Features & Supplementary ──────────────────────────────────────────────
    {"n":"Mammatus","cat":"Feature","alt":"Below Cb anvil (3-15 km)",
     "vol":"Individual pouches 0.5-3 km across; mammatus field 50-300 km wide",
     "cond":"Temperature -20 °C to -40 °C at cloud level; strong downdrafts in cumulonimbus anvil",
     "ap":"Pouch-like lobes hanging below cloud base; smooth or ragged; rows of rounded sacs",
     "aw":"Severe weather below the associated cumulonimbus; often post-storm",
     "ff":"From Latin 'mamma' (breast/udder); formed by sinking air — the opposite of normal cloud formation"},

    {"n":"Arcus (Shelf cloud)","cat":"Feature","alt":"Low level (0.3-2 km)",
     "vol":"Shelf 10-500 km long, 0.5-2 km thick; ~500-5,000 km³",
     "cond":"Temperature contrast at gust front; cold outflow undercuts warm moist inflow",
     "ap":"Dark wedge-shaped shelf attached to the front of a storm; ragged underside",
     "aw":"Thunderstorm gust front; sudden temperature drop; gusty winds 50-100 km/h",
     "ff":"Can stretch for hundreds of kilometres; appears as a 'wall' advancing across the landscape"},

    {"n":"Virga","cat":"Feature","alt":"Various levels",
     "vol":"Streaks 0.5-5 km long, 0.5-3 km wide below cloud base",
     "cond":"Dry sub-cloud layer; low humidity below cloud base; precipitation evaporates in descent",
     "ap":"Wispy streaks or curtains of precipitation hanging below cloud base; never reaching the ground",
     "aw":"Dry atmosphere below; downdrafts can create gusty surface winds (dry microbursts)",
     "ff":"From Latin 'virga' (rod/branch); precipitation literally evaporates mid-air; 'jellyfish' appearance from a distance"},

    {"n":"Pileus","cat":"Feature","alt":"Variable — above a rapidly growing cumulus",
     "vol":"Cap 0.5-5 km wide, 100-500 m thick; ~0.05-1 km³",
     "cond":"Moist stable layer above a powerful updraft; forced lifting by a rising cumulonimbus tower",
     "ap":"Smooth iridescent cap or hood briefly sitting above a rising cumulus tower",
     "aw":"Rapid cloud growth; cumulonimbus development often within minutes",
     "ff":"One of the most transient clouds — disappears within minutes as the tower grows through it"},

    {"n":"Asperitas","cat":"Feature","alt":"Low to mid level (0.5-5 km)",
     "vol":"Sheet 50-500 km wide, 100-500 m thick; chaotic undulations over hundreds of km²",
     "cond":"Post-convective turbulence; wave instability below cloud base; no specific temperature requirement",
     "ap":"Chaotic dramatic wave-like undulations on the cloud underside; dark and threatening appearance",
     "aw":"Turbulent air; post-convective environment; not necessarily raining",
     "ff":"Newest cloud classification (2017) — first addition to WMO atlas in 60 years; from Latin for 'rough sea'"},

    {"n":"Fluctus","cat":"Feature","alt":"Various levels",
     "vol":"Wave crests 0.5-3 km long; lifespan < 5 minutes; extent 10-100 km",
     "cond":"Strong vertical wind shear between cloud layer and faster air above; wave instability",
     "ap":"Short-lived breaking wave crests along a cloud edge; curl and dissipate rapidly",
     "aw":"Wind shear; turbulence near the cloud",
     "ff":"Kelvin-Helmholtz instability made visible; identical physics to ocean waves breaking on a shore"},

    {"n":"Cavum (Fallstreak hole)","cat":"Feature","alt":"Mid to high level (3-9 km)",
     "vol":"Circular hole 1-50 km across in the cloud layer; ~10-2,500 km² of open sky",
     "cond":"Supercooled water clouds at -10 °C to -20 °C; aircraft or ice-crystal seeding triggers chain freezing",
     "ap":"Large circular or elliptical gap punched in a cloud layer; virga below; iridescent edges",
     "aw":"Clear within the hole; no direct weather impact",
     "ff":"An aircraft punching through a supercooled cloud triggers chain-reaction freezing; once mistaken for UFOs"},

    {"n":"Murus (Wall cloud)","cat":"Feature","alt":"Low level (0.3-1.5 km)",
     "vol":"Lowering 1-10 km wide, 100-800 m of descent below the main base",
     "cond":"Temperature +15 °C to +30 °C; strong rotating updraft in supercell; high near-surface humidity",
     "ap":"Persistent lowering of a cumulonimbus base; often slowly rotating; ragged edges",
     "aw":"Tornado precursor; most intense updraft region of a supercell",
     "ff":"Tornado forecasters watch wall clouds closely — sustained rotation indicates a developing mesocyclone"},

    {"n":"Tuba (Funnel cloud)","cat":"Feature","alt":"Low level (0-3 km)",
     "vol":"Funnel 100-1,000 m in diameter, 0.5-5 km long",
     "cond":"Strong mesocyclone rotation; pressure drop in the vortex; high humidity",
     "ap":"Cone or finger of cloud descending from storm base toward the ground",
     "aw":"Tornado warning if it touches the ground; waterspout if over water",
     "ff":"Officially becomes a tornado the moment the condensation funnel or debris cloud reaches the ground"},

    {"n":"Incus (Anvil cloud)","cat":"Feature","alt":"Tropopause (8-16 km)",
     "vol":"Anvil 100-500 km wide, 1-3 km thick; ~10,000-50,000 km³",
     "cond":"Temperature -40 °C to -60 °C; ice crystals spread by jet-level winds at the tropopause",
     "ap":"Flat spreading ice-crystal canopy at the top of a cumulonimbus; points downwind",
     "aw":"Severe thunderstorm below; indicates storm movement direction",
     "ff":"From Latin 'incus' (anvil); can spread 500 km downwind and persist hours after the storm"},

    {"n":"Velum","cat":"Feature","alt":"Variable — same level as the parent cloud",
     "vol":"Veil 5-200 km wide, 100-500 m thick; ~500-10,000 km²",
     "cond":"Moist stable layer at mid-levels; large cumulus or cumulonimbus growing through it",
     "ap":"Thin horizontal veil or sheet attached to or draped around a rising cumulus tower",
     "aw":"Indicates a deep moist layer; parent cloud likely to become severe",
     "ff":"Distinct from pileus — velum is a persistent veil the tower grows through, not a transient cap"},

    {"n":"Pannus","cat":"Feature","alt":"Below precipitating cloud (0-2 km)",
     "vol":"Ragged fragments a few hundred metres to 2 km wide",
     "cond":"Temperature near 0 °C; heavy precipitation evaporating and re-saturating air below the cloud",
     "ap":"Dark grey ragged fragments beneath nimbostratus or cumulonimbus; scud-like appearance",
     "aw":"Active precipitation overhead; turbulent low-level winds",
     "ff":"Also called 'scud'; forms as precipitation evaporates and the air immediately below the cloud re-saturates"},

    # ── Special Clouds ────────────────────────────────────────────────────────
    {"n":"Noctilucent cloud (NLC)","cat":"Special","alt":"Mesosphere (~80-85 km)",
     "vol":"Sheet 1-3 km thick, regional extent 1,000-10,000 km²; visible only at night",
     "cond":"Temperature below -120 °C in the mesosphere; water vapour on meteoric dust; latitudes 50-65° in summer",
     "ap":"Electric blue, silver or white filaments visible only in deep twilight after sunset",
     "aw":"No weather impact; indicator of mesospheric conditions",
     "ff":"Highest clouds in Earth's atmosphere — 80 km up; increasing in frequency and area due to climate change"},

    {"n":"Nacreous cloud","cat":"Special","alt":"Polar stratosphere (15-25 km)",
     "vol":"Sheet 1-3 km thick, extent 100-1,000 km; visible at twilight",
     "cond":"Temperature below -78 °C; polar stratospheric vortex; winter/early spring above 60° latitude",
     "ap":"Vivid iridescent pastel colours (mother-of-pearl) in layered sheets; visible at twilight",
     "aw":"No precipitation; catalyse ozone-destroying chemical reactions",
     "ff":"Among the most beautiful clouds; their ice crystals accelerate the reactions that destroy the ozone layer"},

    {"n":"Pyrocumulonimbus","cat":"Special","alt":"Multi-level (2-15 km)",
     "vol":"Tower 5-20 km wide, 10-15 km tall; can inject smoke into the stratosphere; ~500-5,000 km³",
     "cond":"Temperature > +40 °C at fire surface; extreme updraft from wildfire or volcanic eruption; low humidity",
     "ap":"Dark rapidly growing convective column above a fire; develops an anvil; fire-orange base",
     "aw":"Fire-generated thunderstorms; dry lightning igniting new fires; unpredictable fire behaviour",
     "ff":"Can inject smoke into the stratosphere where it persists for months; Australia's 2019-20 fires generated > 1,000"},

    {"n":"Morning Glory","cat":"Special","alt":"Very low level (100-300 m)",
     "vol":"Tube 1-3 km in diameter, 100-1,000 km long; ~100-3,000 km³ per roll",
     "cond":"Cool overnight temperatures; atmospheric bore from Gulf of Carpentaria sea breeze; humid tropical air",
     "ap":"One or several solitary tubular roll clouds spanning the horizon; roll forward as they travel",
     "aw":"Strong low-level roll winds 60 km/h; sharp temperature drop",
     "ff":"Predictable only in Burketown, Australia; attracts glider pilots globally; extremely rare elsewhere"},

    {"n":"Orographic cap cloud","cat":"Special","alt":"Mountain summit level (variable)",
     "vol":"Cap 1-10 km wide, 100-500 m thick; ~0.1-2 km³; continuously reformed",
     "cond":"Moist airflow forced to rise over a mountain; condensation level at or below the summit",
     "ap":"Stationary cloud draped over or clinging to a mountain peak",
     "aw":"Wet and cloudy on windward slope; warm dry foehn wind on the leeward side",
     "ff":"Appears to 'sit' permanently on the mountain — air condenses upwind, then warms and evaporates downwind"},

    {"n":"Contrail","cat":"Special","alt":"High level (8-12 km)",
     "vol":"Trail 5-200 km long, 0.1-2 km wide; ~0.5-200 km³; can spread into artificial cirrus",
     "cond":"Temperature below -40 °C; relative humidity near ice saturation; water vapour from jet engines",
     "ap":"Bright white linear streaks across a clear blue sky; may persist minutes or hours",
     "aw":"Persistent contrails indicate high humidity aloft; spreading trails signal incoming moisture",
     "ff":"Short for 'condensation trail'; persistent spreading contrails contribute to artificial high-level cloud cover"},

    {"n":"Ship track","cat":"Special","alt":"Low level (0.5-2 km)",
     "vol":"Track 1-5 km wide, 10-500 km long; modifies cloud properties over ~5-2,500 km²",
     "cond":"Low-level marine stratus; clean marine air; ship exhaust aerosols acting as cloud condensation nuclei",
     "ap":"Bright white linear streaks crossing a stratocumulus deck; visible from space",
     "aw":"No direct weather impact; slightly alters regional cloud lifetime and reflectivity",
     "ff":"Ship exhaust creates brighter longer-lasting clouds; visible from satellites as threads across ocean"},

    {"n":"Fog","cat":"Special","alt":"Surface level (0-30 m)",
     "vol":"Sheet 1-500 km wide, 10-300 m thick; ~10-15,000 km³ for a dense fog bank",
     "cond":"Temperature near the dewpoint at the surface; clear skies for radiative cooling; calm winds < 5 km/h",
     "ap":"Uniform white or grey cloud at ground level; objects invisible beyond 1 km",
     "aw":"Near-zero visibility; possible drizzle; airport and road closures",
     "ff":"Meteorologically, fog is simply stratus touching the ground; defined by visibility < 1 km"},

    # ── Varieties ─────────────────────────────────────────────────────────────
    {"n":"Altocumulus undulatus","cat":"Variety","alt":"Mid level (2-5 km)",
     "vol":"Sheet 100-2,000 km wide, 200-700 m thick; ~20,000-200,000 km³",
     "cond":"Temperature -5 °C to +5 °C; stable air with gentle wind shear; atmospheric gravity waves",
     "ap":"Parallel undulating rows of altocumulus aligned perpendicular to upper winds",
     "aw":"Stable conditions; no significant precipitation; may indicate an approaching front",
     "ff":"Classic textbook example of atmospheric gravity waves made visible by cloud condensation"},

    {"n":"Cirrocumulus undulatus","cat":"Variety","alt":"High level (6-12 km)",
     "vol":"Sheet 100-3,000 km wide, 100-400 m thick; ~10,000-100,000 km³",
     "cond":"Temperature below -20 °C; wind shear at upper levels creating gravity waves",
     "ap":"Fine regular ripple pattern of tiny cloudlets; 'mackerel' or 'herring-bone' sky",
     "aw":"Wind shear aloft; generally fair weather",
     "ff":"The classic 'mackerel sky'; ancient sailors' rhyme: 'Mackerel sky, not 24 hours dry'"},

    {"n":"Cloud streets (Cumulus radiatus)","cat":"Variety","alt":"Low level (0.5-3 km)",
     "vol":"Rows 10-500 km long, 1-3 km wide, 0.5-2 km tall; ~5-300 km³ per street",
     "cond":"Temperature +10 °C to +30 °C; steady wind; warm ocean or land surface driving boundary-layer rolls",
     "ap":"Long parallel rows of cumulus clouds converging toward the horizon like a runway",
     "aw":"Fair weather below the rows; used by glider pilots for long-distance soaring",
     "ff":"'Cloud streets' — boundary-layer convection rolls; most spectacular over warm tropical oceans"},

    {"n":"Stratocumulus opacus","cat":"Variety","alt":"Low level (0.5-2 km)",
     "vol":"Sheet 200-5,000 km wide, 200-800 m thick; ~40,000-500,000 km³",
     "cond":"Temperature +5 °C to +15 °C; strong subsidence inversion trapping marine or continental air",
     "ap":"Opaque thick dark grey sheet completely obscuring the sun; featureless base",
     "aw":"Overcast; possible drizzle; persistent in autumn and winter especially near coasts",
     "ff":"Responsible for the gloomy grey winter sky; can persist for days under a blocking high-pressure system"},
]
