import json, sys
sys.stdout.reconfigure(encoding="utf-8")

# n=species, strat=reproduction strategy, typ=viviparous/oviparous/ovoviviparous/asexual,
# gest=gestation or incubation duration, fa=fact
# No images: nature-documentary facts only, text-only card (avoids any risk of a
# species' lead Wikipedia photo depicting mating rather than a neutral portrait)
species = [
    {"n":"Seahorse","strat":"Male pregnancy","typ":"Ovoviviparous (male-brooded)","gest":"2 to 4 weeks","fa":"Males carry fertilized eggs in a specialized brood pouch until the young are born"},
    {"n":"Anglerfish","strat":"Parasitic mating","typ":"Oviparous","gest":"Not well documented in the wild","fa":"In many deep-sea species, the tiny male permanently fuses to the much larger female, sharing her bloodstream for life"},
    {"n":"Kangaroo","strat":"Embryonic diapause","typ":"Viviparous","gest":"About 31 to 36 days (extendable via diapause)","fa":"Can pause the development of an embryo until conditions are favorable, effectively delaying birth"},
    {"n":"Pacific Salmon","strat":"Semelparity","typ":"Oviparous","gest":"6 to 20 weeks to hatch, depending on water temperature","fa":"Most species die within days or weeks of spawning once, having used all their energy reserves for the journey upstream"},
    {"n":"Common Octopus","strat":"Maternal self-sacrifice","typ":"Oviparous","gest":"1 to 3 months to hatch","fa":"Females stop eating to guard their eggs for months and typically die shortly after they hatch"},
    {"n":"Emperor Penguin","strat":"Paternal incubation","typ":"Oviparous","gest":"About 65 to 75 days incubation","fa":"Males incubate the single egg on their feet through the Antarctic winter for about two months without eating"},
    {"n":"Clownfish","strat":"Sequential hermaphroditism (protandry)","typ":"Oviparous","gest":"6 to 10 days to hatch","fa":"All clownfish are born male; the dominant individual in a group changes into the sole breeding female"},
    {"n":"Wrasse","strat":"Sequential hermaphroditism (protogyny)","typ":"Oviparous","gest":"Often under 2 weeks, varies by species","fa":"Many species start life as females, with the largest individual changing into a male when the group's male dies"},
    {"n":"Komodo Dragon","strat":"Facultative parthenogenesis","typ":"Oviparous","gest":"About 7 to 8.5 months incubation","fa":"Females can produce viable offspring without a male, a rare capability among reptiles"},
    {"n":"Aphid","strat":"Parthenogenesis with live birth","typ":"Viviparous (in parthenogenetic phase)","gest":"About 1 to 2 weeks per generation","fa":"Females can give birth to genetically identical live young without ever mating, especially in favorable seasons"},
    {"n":"Praying Mantis","strat":"Sexual cannibalism","typ":"Oviparous","gest":"3 to 6 weeks to hatch","fa":"Females sometimes eat the male during or after mating, though this happens less often in the wild than in captivity"},
    {"n":"Redback Spider","strat":"Male self-sacrifice","typ":"Oviparous","gest":"2 to 4 weeks to hatch","fa":"Males often position themselves to be eaten by the female during mating, which may prolong the mating act"},
    {"n":"Common Cuckoo","strat":"Brood parasitism","typ":"Oviparous","gest":"11 to 13 days incubation (by host)","fa":"Lays its eggs in the nests of other bird species, tricking them into raising cuckoo chicks as their own"},
    {"n":"Brown-headed Cowbird","strat":"Brood parasitism","typ":"Oviparous","gest":"10 to 12 days incubation (by host)","fa":"Like the cuckoo, lays eggs in other species' nests and never raises its own young"},
    {"n":"Platypus","strat":"Egg-laying mammal (monotreme)","typ":"Oviparous","gest":"About 10 days external incubation after ~28 days in utero","fa":"One of only a few mammal species that lay eggs instead of giving live birth"},
    {"n":"Echidna","strat":"Egg-laying mammal (monotreme)","typ":"Oviparous","gest":"About 10 days external incubation in a pouch","fa":"Lays a single soft-shelled egg, which it carries in a temporary pouch until it hatches"},
    {"n":"American Alligator","strat":"Temperature-dependent sex determination","typ":"Oviparous","gest":"About 65 days incubation","fa":"The temperature of the nest during incubation determines whether the hatchlings become male or female"},
    {"n":"Green Sea Turtle","strat":"Temperature-dependent sex determination","typ":"Oviparous","gest":"45 to 70 days incubation","fa":"Warmer sand produces mostly females, while cooler sand produces mostly males"},
    {"n":"Giant Panda","strat":"Narrow fertility window","typ":"Viviparous","gest":"95 to 160 days (highly variable due to delayed implantation)","fa":"Females are fertile for only about 24 to 72 hours once a year, making captive breeding notoriously difficult"},
    {"n":"Honey Bee","strat":"Single mating flight","typ":"Oviparous","gest":"About 21 days from egg to adult worker","fa":"A queen mates with multiple drones during one flight early in life and stores the sperm to fertilize eggs for years"},
    {"n":"Leafcutter Ant","strat":"Single mating flight","typ":"Oviparous","gest":"Several weeks from egg to adult","fa":"Queens store sperm from a single nuptial flight and use it to fertilize eggs for the rest of their decade-plus lifespan"},
    {"n":"African Elephant","strat":"Longest mammalian gestation","typ":"Viviparous","gest":"About 22 months","fa":"Pregnancy lasts about 22 months, the longest gestation period of any land mammal"},
    {"n":"Virginia Opossum","strat":"Very short gestation","typ":"Viviparous","gest":"About 12 to 13 days","fa":"Gestation lasts only about 12 to 13 days, among the shortest of any mammal"},
    {"n":"Humpback Whale","strat":"Long-distance migration for breeding","typ":"Viviparous","gest":"About 11 to 12 months","fa":"Travels thousands of miles between feeding and breeding grounds each year"},
    {"n":"Poison Dart Frog","strat":"Paternal transport of young","typ":"Oviparous","gest":"10 to 18 days to hatch as tadpoles","fa":"In many species, the male carries tadpoles on his back to water after they hatch"},
    {"n":"Pipefish","strat":"Male pregnancy","typ":"Ovoviviparous (male-brooded)","gest":"2 to 4 weeks","fa":"A close relative of the seahorse in which males also carry fertilized eggs until they hatch"},
    {"n":"Midwife Toad","strat":"Paternal egg-carrying","typ":"Oviparous","gest":"3 to 7 weeks carried by the male before hatching","fa":"Males wrap strings of fertilized eggs around their hind legs and carry them until they are ready to hatch"},
    {"n":"Surinam Toad","strat":"Eggs embedded in skin","typ":"Oviparous","gest":"About 12 to 20 weeks embedded in the skin","fa":"Fertilized eggs are pressed into the skin on the female's back, where they develop until fully formed toadlets emerge"},
    {"n":"Giant Pacific Octopus","strat":"Mass egg-laying","typ":"Oviparous","gest":"About 6 to 10 months incubation","fa":"A single female can lay as many as 100,000 eggs in one clutch"},
    {"n":"Ocean Sunfish","strat":"Extreme egg output","typ":"Oviparous","gest":"External fertilization, rapid larval development","fa":"Females can release up to 300 million eggs in a single spawning, more than any other known vertebrate"},
    {"n":"Hammerhead Shark","strat":"Facultative parthenogenesis","typ":"Viviparous (typically)","gest":"About 10 to 11 months","fa":"Some captive females with no access to males have produced viable offspring on their own"},
    {"n":"New Mexico Whiptail","strat":"Obligate parthenogenesis","typ":"Oviparous (parthenogenetic)","gest":"About 7 to 8 weeks incubation","fa":"This entire species consists only of females, which reproduce through cloning without any males"},
    {"n":"Bonobo","strat":"Non-reproductive sexual behavior","typ":"Viviparous","gest":"About 8 months (230 to 240 days)","fa":"Uses sexual behavior extensively for social bonding and conflict resolution, not only for reproduction"},
    {"n":"Black Widow Spider","strat":"Sexual cannibalism","typ":"Oviparous","gest":"2 to 4 weeks to hatch","fa":"Females occasionally eat the male after mating, though it happens far less often than popular belief suggests"},
    {"n":"Mallard Duck","strat":"Complex genital coevolution","typ":"Oviparous","gest":"26 to 30 days incubation","fa":"Males and females have evolved unusually complex reproductive anatomy in response to one another"},
    {"n":"Bowerbird","strat":"Elaborate courtship display","typ":"Oviparous","gest":"19 to 24 days incubation","fa":"Males build and decorate intricate structures called bowers purely to attract a mate"},
    {"n":"Peacock","strat":"Elaborate courtship display","typ":"Oviparous","gest":"About 28 days incubation","fa":"The male's large, colorful tail feathers evolved specifically to attract peahens"},
    {"n":"Bird-of-Paradise","strat":"Elaborate courtship display","typ":"Oviparous","gest":"17 to 21 days incubation","fa":"Males perform highly choreographed dances and displays that vary dramatically between species"},
    {"n":"Firefly","strat":"Bioluminescent mate attraction","typ":"Oviparous","gest":"3 to 4 weeks from egg to larva","fa":"Uses specific patterns of light flashes to signal and identify potential mates of the same species"},
    {"n":"Galapagos Tortoise","strat":"Long reproductive lifespan","typ":"Oviparous","gest":"120 to 180 days incubation","fa":"Can continue breeding for over a century thanks to its exceptionally long overall lifespan"},
    {"n":"Naked Mole-Rat","strat":"Eusociality with a single breeding queen","typ":"Viviparous","gest":"About 70 days","fa":"Only one queen in the colony reproduces, similar to the social structure of bees and ants"},
    {"n":"Termite","strat":"Long-lived egg-laying queen","typ":"Oviparous","gest":"30 to 90 days from egg to adult, depending on caste","fa":"A queen can live for decades and lay eggs continuously, produced by a king that remains with her for life"},
    {"n":"Coral","strat":"Synchronized mass spawning","typ":"Oviparous (broadcast spawning)","gest":"Days to weeks as free-swimming larvae","fa":"Many species release eggs and sperm into the water simultaneously on just one or two nights a year, timed to the lunar cycle"},
    {"n":"Starfish","strat":"Asexual regeneration alongside sexual reproduction","typ":"Oviparous, with some asexual regeneration","gest":"About 2 to 3 weeks as larvae","fa":"Can reproduce sexually but some species can also regenerate an entire new individual from a single detached arm"},
    {"n":"Hydra","strat":"Asexual budding","typ":"Asexual (budding), sexual reproduction also possible","gest":"A bud detaches within days","fa":"Can reproduce by growing a small clone as a bud on its body, which eventually detaches to live independently"},
    {"n":"Marsupial Frog","strat":"Dorsal egg-carrying pouch","typ":"Oviparous (pouch-carried)","gest":"Varies by species, from weeks to direct development","fa":"Females carry developing eggs in a pouch on their back until they emerge as froglets or tadpoles"},
    {"n":"Leafy Sea Dragon","strat":"Male pregnancy","typ":"Ovoviviparous (male-brooded)","gest":"4 to 6 weeks","fa":"A relative of the seahorse in which the male also carries fertilized eggs on his tail until they hatch"},
    {"n":"Giant Anteater","strat":"Long gestation for body size","typ":"Viviparous","gest":"About 190 days","fa":"Pregnancy lasts around 190 days, unusually long relative to its size, typically producing a single offspring"},
    {"n":"Wandering Albatross","strat":"Lifelong monogamy with infrequent breeding","typ":"Oviparous","gest":"About 78 days incubation","fa":"Pairs mate for life and typically breed only once every two years due to the long chick-rearing period"},
    {"n":"Banana Slug","strat":"Hermaphroditic mating","typ":"Oviparous (hermaphroditic)","gest":"1 to 6 months to hatch, depending on conditions","fa":"Each individual has both male and female reproductive organs and can exchange sperm with a mating partner"},
    {"n":"Earthworm","strat":"Hermaphroditic mating","typ":"Oviparous (hermaphroditic)","gest":"2 to 4 weeks in a protective cocoon","fa":"Has both male and female reproductive organs but still needs to pair with another earthworm to reproduce"},
    {"n":"Sea Anemone","strat":"Sexual and asexual reproduction","typ":"Oviparous, or asexual splitting","gest":"Days to weeks as free-swimming larvae","fa":"Can reproduce sexually by releasing eggs and sperm, or asexually by splitting its own body in two"},
    {"n":"Burying Beetle","strat":"Cooperative biparental care","typ":"Oviparous","gest":"About 1 week to hatch","fa":"Both parents cooperate to prepare a buried carcass and feed their larvae, unusual among insects"},
    {"n":"Emperor Tamarin","strat":"Cooperative breeding","typ":"Viviparous","gest":"About 140 to 145 days","fa":"Other members of the family group help carry and care for the offspring, not just the parents"},
    {"n":"Guppy","strat":"Live-bearing fish","typ":"Ovoviviparous","gest":"About 21 to 30 days","fa":"Gives birth to dozens of free-swimming live young rather than laying eggs"},
    {"n":"Great White Shark","strat":"Intrauterine cannibalism (oophagy)","typ":"Ovoviviparous","gest":"About 11 months","fa":"Developing embryos feed on unfertilized eggs released by the mother inside the womb"},
    {"n":"Sand Tiger Shark","strat":"Embryonic cannibalism (adelphophagy)","typ":"Ovoviviparous","gest":"9 to 12 months","fa":"The strongest embryo in each uterus typically eats its smaller siblings before birth, leaving only one or two survivors per side"},
    {"n":"Chinchilla","strat":"Long gestation for a rodent","typ":"Viviparous","gest":"About 111 days","fa":"Has one of the longest gestation periods of any rodent, producing well-developed young"},
    {"n":"Guinea Pig","strat":"Precocial young","typ":"Viviparous","gest":"59 to 72 days","fa":"Gives birth to fully furred young capable of walking and eating solid food within hours"},
    {"n":"Blue Whale","strat":"Largest newborn of any animal","typ":"Viviparous","gest":"About 10 to 12 months","fa":"Gives birth to the largest newborn of any animal, with calves already weighing several tonnes"},
    {"n":"Giraffe","strat":"Standing birth","typ":"Viviparous","gest":"About 15 months","fa":"Gives birth standing up, meaning newborn calves fall roughly 1.5 meters to the ground"},
    {"n":"Chicken","strat":"Domesticated egg-laying","typ":"Oviparous","gest":"About 21 days incubation","fa":"One of the most farmed birds in the world, selectively bred for continuous, frequent egg-laying"},
    {"n":"Ostrich","strat":"Largest bird egg","typ":"Oviparous","gest":"42 to 46 days incubation","fa":"Lays the largest egg of any living bird, though it is the smallest egg relative to the parent's body size"},
    {"n":"Hummingbird","strat":"Smallest bird eggs","typ":"Oviparous","gest":"14 to 19 days incubation","fa":"Lays some of the smallest eggs of any bird, often no larger than a coffee bean"},
    {"n":"Ball Python","strat":"Maternal thermoregulation of eggs","typ":"Oviparous","gest":"55 to 60 days incubation","fa":"Females coil tightly around their eggs and can generate slight heat through muscle contractions to protect them"},
    {"n":"Veiled Chameleon","strat":"Extended incubation","typ":"Oviparous","gest":"6 to 9 months, sometimes over a year","fa":"Eggs can take many months to hatch, among the longest incubation periods of any reptile"},
    {"n":"Viviparous Lizard","strat":"Live birth (unusual among lizards)","typ":"Viviparous","gest":"About 2 to 3 months","fa":"Named specifically for giving live birth, an unusual trait shared by only a minority of lizard species"},
    {"n":"Tsetse Fly","strat":"Live birth (rare among insects)","typ":"Viviparous","gest":"About 9 days of internal development per larva","fa":"Gives birth to a single, already well-developed larva at a time rather than laying many eggs"},
    {"n":"Emperor Scorpion","strat":"Maternal carrying of young","typ":"Viviparous","gest":"About 7 to 9 months","fa":"Young ride on their mother's back for one to two weeks after birth before venturing out on their own"},
    {"n":"Rattlesnake","strat":"Live birth in a venomous snake","typ":"Ovoviviparous","gest":"90 to 167 days, depending on species","fa":"Gives birth to live young rather than laying eggs, unlike many other snake species"},
    {"n":"Boa Constrictor","strat":"Live birth in a large constrictor","typ":"Ovoviviparous","gest":"100 to 120 days","fa":"Gives birth to dozens of live young at once instead of laying eggs"},
    {"n":"Fruit Fly","strat":"Extremely rapid life cycle","typ":"Oviparous","gest":"About 8 to 10 days from egg to adult","fa":"Its remarkably fast life cycle makes it one of the most widely used organisms in genetics research"},
    {"n":"Plains Zebra","strat":"Long gestation similar to horses","typ":"Viviparous","gest":"About 360 to 390 days","fa":"Foals can stand and run within an hour of birth, a crucial adaptation for life among predators"},
    {"n":"Wolf Spider","strat":"Maternal carrying of young","typ":"Oviparous","gest":"2 to 3 weeks to hatch, then carried by the mother","fa":"Carries her egg sac attached to her spinnerets, and the spiderlings ride on her back after hatching"},
    {"n":"Giant Water Bug","strat":"Paternal egg-carrying (insect)","typ":"Oviparous","gest":"1 to 2 weeks carried by the male","fa":"Females glue their eggs directly onto the back of the male, who carries and aerates them until they hatch"},
]

with open("assets/science/species_reproduction.json", "w", encoding="utf-8") as f:
    json.dump(species, f, ensure_ascii=False, separators=(',', ':'))

print(f"{len(species)} species reproduction entries generated.")
