INSECTS_RAW = [
  # Coleoptera (Beetles)
  {"n":"Ladybug","ord":"Coleoptera","fam":"Coccinellidae","ha":"Gardens, meadows, forests","di":"Aphids, scale insects","si":"4-8 mm","ff":"A single ladybug can eat up to 5,000 aphids in its lifetime."},
  {"n":"Stag Beetle","ord":"Coleoptera","fam":"Lucanidae","ha":"Deciduous forests","di":"Tree sap, decaying wood (larvae)","si":"25-75 mm","ff":"Males use their enormous antler-like mandibles to wrestle rivals for mating rights."},
  {"n":"Hercules Beetle","ord":"Coleoptera","fam":"Dynastinae","ha":"Tropical rainforests","di":"Decaying wood, fruit","si":"50-170 mm","ff":"One of the world's largest insects; the horn alone can be longer than its body."},
  {"n":"Goliath Beetle","ord":"Coleoptera","fam":"Cetoniinae","ha":"African tropical forests","di":"Tree sap, ripe fruit","si":"50-110 mm","ff":"Among the heaviest insects on Earth, weighing up to 100 g as larvae."},
  {"n":"Firefly","ord":"Coleoptera","fam":"Lampyridae","ha":"Meadows, forest edges, wetlands","di":"Nectar, other insects","si":"5-25 mm","ff":"Produces cold light (bioluminescence) with nearly 100% efficiency — no heat is wasted."},
  {"n":"Bombardier Beetle","ord":"Coleoptera","fam":"Carabidae","ha":"Grasslands, forests","di":"Other insects","si":"10-25 mm","ff":"Fires a boiling chemical spray at 100°C from its abdomen up to 500 times per second."},
  {"n":"Dung Beetle","ord":"Coleoptera","fam":"Scarabaeidae","ha":"Savannas, grasslands, forests","di":"Animal dung","si":"10-30 mm","ff":"Ancient Egyptians worshipped the scarab; dung beetles navigate using the Milky Way."},
  {"n":"Longhorn Beetle","ord":"Coleoptera","fam":"Cerambycidae","ha":"Forests worldwide","di":"Wood, plant tissue (larvae)","si":"10-60 mm","ff":"Some species have antennae three times the length of their body."},
  {"n":"Jewel Beetle","ord":"Coleoptera","fam":"Buprestidae","ha":"Forests, shrublands","di":"Plant nectar, wood (larvae)","si":"3-80 mm","ff":"Its iridescent elytra have been used in jewellery and embroidery for thousands of years."},
  {"n":"Tiger Beetle","ord":"Coleoptera","fam":"Carabidae","ha":"Sandy beaches, forest paths","di":"Ants, spiders, small insects","si":"8-20 mm","ff":"One of the fastest running insects, reaching up to 9 km/h — proportionally faster than a cheetah."},
  {"n":"Diving Beetle","ord":"Coleoptera","fam":"Dytiscidae","ha":"Freshwater ponds, streams","di":"Aquatic invertebrates, tadpoles, small fish","si":"15-40 mm","ff":"Carries an air bubble under its elytra to breathe underwater."},
  {"n":"Weevil","ord":"Coleoptera","fam":"Curculionidae","ha":"Crops, forests, stored grains","di":"Plant material, seeds","si":"1-40 mm","ff":"With over 60,000 species, weevils form the largest family in the animal kingdom."},
  {"n":"Click Beetle","ord":"Coleoptera","fam":"Elateridae","ha":"Forests, meadows","di":"Plant roots, other insects (larvae)","si":"7-20 mm","ff":"Snaps a spine on its body to flip itself upright with an audible click, reaching heights of 30 cm."},
  {"n":"Ground Beetle","ord":"Coleoptera","fam":"Carabidae","ha":"Soil, leaf litter, gardens","di":"Other insects, worms","si":"5-35 mm","ff":"Many species can run at impressive speeds and are important predators of crop pests."},
  {"n":"Bark Beetle","ord":"Coleoptera","fam":"Curculionidae","ha":"Coniferous and deciduous forests","di":"Bark and wood of trees","si":"1-9 mm","ff":"Bark beetle outbreaks have killed billions of trees across North America since the 1990s."},
  # Lepidoptera (Butterflies & Moths)
  {"n":"Monarch Butterfly","ord":"Lepidoptera","fam":"Nymphalidae","ha":"Meadows, gardens, forests","di":"Milkweed nectar (adults), milkweed leaves (caterpillars)","si":"89-102 mm wingspan","ff":"Migrates up to 4,800 km from Canada to Mexico each year — one of nature's greatest journeys."},
  {"n":"Swallowtail Butterfly","ord":"Lepidoptera","fam":"Papilionidae","ha":"Gardens, woodlands, meadows","di":"Flower nectar (adults), leaves (caterpillars)","si":"65-100 mm wingspan","ff":"Named for the elongated tail extensions on hindwings; caterpillars mimic bird droppings for camouflage."},
  {"n":"Blue Morpho Butterfly","ord":"Lepidoptera","fam":"Nymphalidae","ha":"Tropical rainforests of South America","di":"Rotting fruit, tree sap","si":"120-200 mm wingspan","ff":"Its vivid blue colour comes not from pigment but from microscopic scales that refract light."},
  {"n":"Atlas Moth","ord":"Lepidoptera","fam":"Saturniidae","ha":"Tropical forests of Asia","di":"Does not eat as adult (no mouthparts)","si":"250-300 mm wingspan","ff":"Has no mouth as an adult; lives only 1-2 weeks solely to reproduce, fuelled by larval fat reserves."},
  {"n":"Luna Moth","ord":"Lepidoptera","fam":"Saturniidae","ha":"Deciduous forests of North America","di":"Does not eat as adult","si":"75-105 mm wingspan","ff":"Its long tail-like hindwing extensions confuse bat echolocation, spinning sound away from its body."},
  {"n":"Death's-head Hawkmoth","ord":"Lepidoptera","fam":"Sphingidae","ha":"Olive groves, gardens, wasteland","di":"Flower nectar, honey (raids beehives)","si":"80-120 mm wingspan","ff":"Named for the skull-like marking on its thorax; it squeaks when disturbed and invades beehives."},
  {"n":"Peppered Moth","ord":"Lepidoptera","fam":"Geometridae","ha":"Woodlands, urban trees","di":"Tree bark lichens (caterpillars)","si":"45-62 mm wingspan","ff":"The classic textbook example of natural selection: industrial pollution caused dark variants to thrive."},
  {"n":"Silk Moth","ord":"Lepidoptera","fam":"Bombycidae","ha":"Mulberry forests (domesticated)","di":"Mulberry leaves (caterpillars)","si":"40-60 mm wingspan","ff":"Has been domesticated for 5,000 years; a single cocoon can unravel into 1,500 m of continuous silk thread."},
  {"n":"Painted Lady Butterfly","ord":"Lepidoptera","fam":"Nymphalidae","ha":"Open habitats worldwide","di":"Thistle, clover, asters","si":"45-73 mm wingspan","ff":"Undertakes a 14,400 km round-trip migration from Europe to sub-Saharan Africa — six generations complete it."},
  {"n":"Six-spot Burnet Moth","ord":"Lepidoptera","fam":"Zygaenidae","ha":"Meadows, coastal grasslands","di":"Bird's-foot trefoil (caterpillars)","si":"25-35 mm wingspan","ff":"Its vivid red spots warn predators that it contains cyanide produced from the plants it eats."},
  # Hymenoptera (Bees, Wasps & Ants)
  {"n":"European Honey Bee","ord":"Hymenoptera","fam":"Apidae","ha":"Meadows, gardens, orchards worldwide","di":"Nectar and pollen","si":"10-15 mm","ff":"A single colony can contain 60,000 bees; one bee produces only 1/12 teaspoon of honey in its lifetime."},
  {"n":"Bumblebee","ord":"Hymenoptera","fam":"Apidae","ha":"Meadows, gardens, alpine areas","di":"Nectar and pollen","si":"8-25 mm","ff":"Can fly in temperatures too cold for honey bees by vibrating flight muscles to warm up."},
  {"n":"Red Wood Ant","ord":"Hymenoptera","fam":"Formicidae","ha":"Coniferous and mixed forests","di":"Insects, honeydew, seeds","si":"4-9 mm","ff":"Builds mound nests up to 2 m tall housing over 1 million individuals; mounds can be 700 years old."},
  {"n":"Fire Ant","ord":"Hymenoptera","fam":"Formicidae","ha":"Disturbed areas, grasslands, urban","di":"Seeds, insects, small vertebrates","si":"2-6 mm","ff":"Forms living rafts during floods by linking their bodies together, trapping air bubbles to stay afloat."},
  {"n":"Leaf-cutter Ant","ord":"Hymenoptera","fam":"Formicidae","ha":"Tropical and subtropical forests","di":"Fungus grown on leaf mulch","si":"1-16 mm","ff":"Discovered agriculture 50 million years before humans; their fungal gardens produce antibiotics."},
  {"n":"Driver Ant","ord":"Hymenoptera","fam":"Formicidae","ha":"African tropical forests","di":"Almost any animal prey","si":"3-13 mm","ff":"Colonies of up to 22 million ants move as a single 'super-organism' capable of killing large vertebrates."},
  {"n":"Bullet Ant","ord":"Hymenoptera","fam":"Formicidae","ha":"Rainforests of Central and South America","di":"Nectar, small arthropods","si":"18-30 mm","ff":"Delivers the most painful insect sting on the Schmidt scale; the pain reportedly lasts 24 hours."},
  {"n":"Tarantula Hawk","ord":"Hymenoptera","fam":"Pompilidae","ha":"Deserts, scrublands","di":"Nectar (adults); tarantulas (larvae)","si":"25-50 mm","ff":"Paralyses tarantulas with a sting rated among the world's most painful, then lays a single egg on them."},
  {"n":"Jewel Wasp","ord":"Hymenoptera","fam":"Ampulicidae","ha":"Tropical and subtropical regions","di":"Cockroaches (larvae), nectar (adults)","si":"15-22 mm","ff":"Injects a mind-controlling venom directly into a cockroach's brain, turning it into a docile food supply."},
  {"n":"European Hornet","ord":"Hymenoptera","fam":"Vespidae","ha":"Forests, parks, orchards","di":"Insects, tree sap, fruit","si":"18-35 mm","ff":"Europe's largest eusocial wasp; can sting multiple times and hunts by night, unlike most wasps."},
  {"n":"Yellow Jacket","ord":"Hymenoptera","fam":"Vespidae","ha":"Meadows, forests, urban areas","di":"Insects, sugary foods, carrion","si":"10-16 mm","ff":"Aggressive defenders of their nests; can communicate the location and size of food sources to nestmates."},
  {"n":"Carpenter Ant","ord":"Hymenoptera","fam":"Formicidae","ha":"Forests, wooden structures","di":"Insects, honeydew, sugary foods","si":"6-13 mm","ff":"Excavates galleries in wood not for food but for nesting; a colony can survive over 25 years."},
  # Diptera (Flies)
  {"n":"House Fly","ord":"Diptera","fam":"Muscidae","ha":"Human habitations worldwide","di":"Decaying organic matter, excrement","si":"6-7 mm","ff":"Tastes food with its feet (1,000× more sensitive than the human tongue) and vomits digestive juice onto it."},
  {"n":"Horse Fly","ord":"Diptera","fam":"Tabanidae","ha":"Near livestock, water bodies","di":"Blood (females), nectar (males)","si":"6-25 mm","ff":"Females cut skin with scissors-like mouthparts; their bite is one of the most painful insect bites."},
  {"n":"Hoverfly","ord":"Diptera","fam":"Syrphidae","ha":"Flowers, gardens, meadows","di":"Pollen, nectar (adults); aphids (larvae)","si":"8-18 mm","ff":"Mimics bees and wasps for protection despite being harmless; hovers motionless in the air for minutes."},
  {"n":"Tsetse Fly","ord":"Diptera","fam":"Glossinidae","ha":"Sub-Saharan African savannas","di":"Blood of vertebrates","si":"8-17 mm","ff":"Transmits sleeping sickness (trypanosomiasis); has kept large areas of Africa free from cattle farming."},
  {"n":"Mosquito","ord":"Diptera","fam":"Culicidae","ha":"Near standing water worldwide","di":"Blood (females), nectar (males)","si":"3-6 mm","ff":"Responsible for more human deaths than any other animal — over 700,000 per year through malaria alone."},
  {"n":"Robber Fly","ord":"Diptera","fam":"Asilidae","ha":"Open habitats, forests, deserts","di":"Other insects (caught in flight)","si":"3-50 mm","ff":"Catches prey in mid-air and injects a venom that liquefies the victim's insides within seconds."},
  {"n":"Crane Fly","ord":"Diptera","fam":"Tipulidae","ha":"Grasslands, gardens, wetlands","di":"Plant roots (larvae), rarely eats as adult","si":"10-60 mm","ff":"Despite resembling a giant mosquito, crane flies are harmless — most adults don't even eat."},
  # Odonata (Dragonflies & Damselflies)
  {"n":"Emperor Dragonfly","ord":"Odonata","fam":"Aeshnidae","ha":"Large ponds, lakes, slow rivers","di":"Flying insects, small fish","si":"70-84 mm","ff":"One of Europe's largest dragonflies; patrols fixed territories for hours, rarely landing."},
  {"n":"Common Blue Damselfly","ord":"Odonata","fam":"Coenagrionidae","ha":"Ponds, canals, slow rivers","di":"Small flying insects","si":"29-31 mm","ff":"Males are blue and black; females mimic darker variants of males to avoid unwanted mating attempts."},
  {"n":"Giant Petaltail","ord":"Odonata","fam":"Petaluridae","ha":"Swamps, bogs, wet forests","di":"Large insects, small vertebrates","si":"75-100 mm","ff":"One of the world's largest dragonflies, belonging to one of the oldest odonate lineages — 150 million years."},
  {"n":"Banded Demoiselle","ord":"Odonata","fam":"Calopterygidae","ha":"Streams and rivers with clear water","di":"Small aquatic and flying insects","si":"45-48 mm","ff":"Males perform elaborate fluttering courtship dances over water, folding and spreading iridescent wings."},
  # Orthoptera (Grasshoppers & Crickets)
  {"n":"Desert Locust","ord":"Orthoptera","fam":"Acrididae","ha":"Arid and semi-arid regions of Africa and Asia","di":"All plant material","si":"40-60 mm","ff":"Swarms of billions can strip 35,000 tonnes of vegetation per day, threatening food security for millions."},
  {"n":"Field Cricket","ord":"Orthoptera","fam":"Gryllidae","ha":"Grasslands, gardens, hedgerows","di":"Plants, small invertebrates","si":"17-25 mm","ff":"Only males chirp; the frequency of their chirps is temperature-dependent — you can calculate temperature from it."},
  {"n":"Katydid","ord":"Orthoptera","fam":"Tettigoniidae","ha":"Tropical forests, meadows","di":"Leaves, flowers, small insects","si":"25-75 mm","ff":"Masters of camouflage, mimicking leaves down to fake bite marks and fungal spots to avoid predators."},
  {"n":"Mole Cricket","ord":"Orthoptera","fam":"Gryllotalpidae","ha":"Moist soil near water","di":"Roots, worms, small insects","si":"25-45 mm","ff":"Digs acoustic chambers that amplify its mating calls like a megaphone, audible up to 500 m away."},
  {"n":"Giant Weta","ord":"Orthoptera","fam":"Anostostomatidae","ha":"New Zealand forests","di":"Leaves, fruit, small invertebrates","si":"70-100 mm","ff":"One of the world's heaviest insects at up to 71 g; surviving on islands without mammalian predators."},
  # Mantodea (Praying Mantises)
  {"n":"European Mantis","ord":"Mantodea","fam":"Mantidae","ha":"Mediterranean shrublands, gardens","di":"Insects, small vertebrates","si":"40-75 mm","ff":"Can rotate its head 180°; females sometimes devour the male during or after mating."},
  {"n":"Orchid Mantis","ord":"Mantodea","fam":"Hymenopodidae","ha":"Rainforests of Southeast Asia","di":"Insects, small vertebrates","si":"25-38 mm","ff":"Mimics orchid flowers so convincingly that pollinators land on it — one of nature's most spectacular disguises."},
  {"n":"Dead Leaf Mantis","ord":"Mantodea","fam":"Mantidae","ha":"Tropical forests","di":"Insects","si":"55-65 mm","ff":"Its body, wing venation, and even fake bite marks mimic a dead leaf perfectly from every angle."},
  # Phasmatodea (Stick & Leaf Insects)
  {"n":"Stick Insect","ord":"Phasmatodea","fam":"Phasmatidae","ha":"Tropical and subtropical forests","di":"Leaves and bark","si":"50-300 mm","ff":"The world's longest insect (Chan's megastick) reaches 64 cm with legs extended."},
  {"n":"Leaf Insect","ord":"Phasmatodea","fam":"Phylliidae","ha":"Tropical forests of South and Southeast Asia","di":"Leaves of forest trees","si":"40-100 mm","ff":"Mimics a leaf so precisely — including veins, uneven edges, and mould spots — that predators walk right past."},
  # Hemiptera (True Bugs)
  {"n":"Water Strider","ord":"Hemiptera","fam":"Gerridae","ha":"Calm freshwater surfaces","di":"Trapped insects, larvae","si":"10-20 mm","ff":"Walks on water using surface tension; tiny hairs on its feet trap air, creating water-repellent cushions."},
  {"n":"Assassin Bug","ord":"Hemiptera","fam":"Reduviidae","ha":"Forests, gardens, dry habitats","di":"Other insects, occasionally blood","si":"10-40 mm","ff":"Injects dissolving saliva into prey, then sucks out liquefied contents; some species transmit Chagas disease."},
  {"n":"Shield Bug","ord":"Hemiptera","fam":"Pentatomidae","ha":"Gardens, woodland edges, crops","di":"Plant sap, some prey on insects","si":"8-18 mm","ff":"Named for their heraldic shield shape; emits a foul smell from glands when threatened — the 'stink bug'."},
  {"n":"Cicada","ord":"Hemiptera","fam":"Cicadidae","ha":"Forests and scrublands worldwide","di":"Tree xylem sap","si":"18-60 mm","ff":"Some North American species spend 13 or 17 years underground before emerging in synchronised mass events."},
  {"n":"Aphid","ord":"Hemiptera","fam":"Aphididae","ha":"Plants worldwide","di":"Plant sap","si":"1-10 mm","ff":"Can reproduce without males (parthenogenesis); one aphid could theoretically give rise to billions in a summer."},
  {"n":"Giant Water Bug","ord":"Hemiptera","fam":"Belostomatidae","ha":"Freshwater ponds, slow streams","di":"Insects, tadpoles, small fish, frogs","si":"25-65 mm","ff":"Grabs prey larger than itself, injects digestive enzymes, and sucks out the dissolved tissue."},
  # Blattodea (Cockroaches)
  {"n":"Madagascar Hissing Cockroach","ord":"Blattodea","fam":"Blaberidae","ha":"Decaying logs in Madagascan forests","di":"Decaying plant material","si":"50-75 mm","ff":"Produces a loud hiss by forcing air through modified breathing holes; males use it to fight rivals."},
  {"n":"American Cockroach","ord":"Blattodea","fam":"Blattidae","ha":"Warm, damp buildings worldwide","di":"Almost any organic material","si":"35-40 mm","ff":"Can survive up to a week without its head — it dies from dehydration, not from the decapitation itself."},
  # Termitidae (Termites)
  {"n":"Mound-building Termite","ord":"Blattodea","fam":"Termitidae","ha":"African and Australian savannas","di":"Dead plant material, wood","si":"5-15 mm","ff":"Builds mounds up to 9 m tall with internal ventilation shafts maintaining a constant 31°C inside."},
  # Neuroptera
  {"n":"Antlion","ord":"Neuroptera","fam":"Myrmeleontidae","ha":"Sandy soils in warm regions","di":"Ants and small insects (larvae)","si":"25-40 mm","ff":"Larvae dig conical sand traps and bury themselves at the bottom, ambushing insects that fall in."},
  {"n":"Lacewing","ord":"Neuroptera","fam":"Chrysopidae","ha":"Gardens, meadows, forests","di":"Aphids, mites, small insects","si":"10-30 mm","ff":"Lays eggs on silk stalks to prevent larvae from eating each other before hatching."},
  # Trichoptera (Caddisfly)
  {"n":"Caddisfly","ord":"Trichoptera","fam":"Limnephilidae","ha":"Freshwater streams and rivers","di":"Algae, detritus (larvae); does not eat much as adult","si":"5-25 mm","ff":"Larvae build protective cases from gravel, twigs, or sand; some species inspire biomimicry research."},
  # Siphonaptera (Fleas)
  {"n":"Cat Flea","ord":"Siphonaptera","fam":"Pulicidae","ha":"Domestic environments worldwide","di":"Blood of mammals","si":"1-3 mm","ff":"Can jump 150× its own height — proportionally one of the greatest jumps in the animal kingdom."},
  # Dermaptera (Earwigs)
  {"n":"Common Earwig","ord":"Dermaptera","fam":"Forficulidae","ha":"Gardens, leaf litter, under bark","di":"Plants, small insects, decaying matter","si":"12-15 mm","ff":"Exhibits rare maternal care among insects — mothers guard and clean their eggs until hatching."},
  # Zygentoma (Silverfish)
  {"n":"Silverfish","ord":"Zygentoma","fam":"Lepismatidae","ha":"Dark, humid buildings worldwide","di":"Starch, paper, fabric, moulds","si":"12-19 mm","ff":"Among the most evolutionarily ancient insects, virtually unchanged for 400 million years; has no wings."},
  # Ephemeroptera (Mayflies)
  {"n":"Mayfly","ord":"Ephemeroptera","fam":"Ephemeridae","ha":"Near clean freshwater rivers and lakes","di":"Algae and detritus (nymphs); does not eat as adult","si":"5-30 mm","ff":"Adults live only a few hours to days — enough to reproduce — after spending up to 3 years as aquatic nymphs."},
]
